---
title: Часто задаваемые вопросы по FreeBSD
authors:
  - author: Проект документирования FreeBSD
copyright: 1995-2023 The FreeBSD Russian Documentation Project
description: Часто задаваемые вопросы по FreeBSD
trademarks: ["freebsd", "ieee", "linux", "microsoft", "openbsd", "netbsd", "general"]
bookOrder: 5
tags: ["FAQ", "FreeBSD FAQ"]
layout: single
---

// Original EN revision (29.12.2023): 4348bf7a124dad60a08bfab3dcfabc103e8c63ac

= Часто задаваемые вопросы по FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/faq/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Аннотация

Этот документ является так называемым FAQ (Frequently Asked Questions), то есть списком часто задаваемых вопросов по FreeBSD.
Мы приложили все усилия, чтобы сделать этот FAQ информативным настолько, насколько это вообще возможно.

Самая последняя редакция этого документа всегда доступна на extref:{faq}[Web-сайте FreeBSD].
Его также можно сгрузить в виде одного
большого файла в формате link:.[HTML] по HTTP или в различных других форматах с
https://download.freebsd.org/doc/[FTP-сервера FreeBSD].

'''

toc::[]

[[introduction]]
== Вступление

Добро пожаловать в мир FreeBSD!
Этот раздел даёт исчерпывающую обзорную информацию о том, что такое FreeBSD, о её происхождении, целях, примерах использования и сообществе, за ней стоящим.

Изучите истоки происхождения её названия, узнайте, как принять участие в этом проекте и исследуйте богатую экосистему FreeBSD в контексте операционных систем с открытым кодом.

[[what-is-FreeBSD]]
=== Что такое FreeBSD?

FreeBSD является UNIX(R)-подобной операционной системой общего назначения, известной своей исключительной стабильностью, безопасностью и производительностью.
Она разрабатывается отдельным сообществом добровольцев и основана на дистрибутиве BSD (Berkeley Software Distribution) операционной системы UNIX.

FreeBSD обеспечивает мощное и настраиваемое окружение, подходящее для широкого спектра применений, от серверов и встраиваемых систем до сетевого оборудования и настольных компьютеров.
Её приверженность принципам открытого кода гарантирует прозрачность процесса разработки и его направленность на сотрудничество, делая FreeBSD надёжным выбором для тех, кто ищет надёжную операционную систему с высоким уровнем адаптивности.

[[why-called-FreeBSD]]
=== Почему система называется FreeBSD?

Имя "FreeBSD" происходит от корней системы, ведущих в дистрибутив BSD (Berkeley Software Distribution) операционной системы UNIX, известной своим вкладом в мир программного обеспечения с открытым кодом.
"Free" во FreeBSD выражает её приверженность принципам свободного программного обеспечения с открытым кодом, что даёт пользователям свободу изучать, модифицировать и распространять код.

Следует отметить, что слово "free" используется здесь в двух смыслах: один означает "бесплатно", а другой "делать всё, что хотите".

[[FreeBSD-goals]]
=== В чём заключается цель Проекта FreeBSD?

У Проекта FreeBSD имеется ясная и неизменная цель: создать высококачественную UNIX-подобную операционную систему с открытым кодом, обладающую превосходными показателями производительности, безопасности и надёжности.

Он нацелен на предоставление платформы общего назначения, подходящей для решения широкого спектра вычислительных задач, от серверов и рабочих станций до встраиваемых систем и шире.
Разработка FreeBSD ведётся с высоким уровнем приверженности принципам открытого кода и способствует совместной работе, когда вклад мирового сообщества разработчиков помогает формировать и улучшать операционную систему.
Такое внимание к качеству, свободе и надёжности является тем, что выделяет FreeBSD и поддерживает её постоянный успех как проекта с открытым кодом.

[[FreeBSD-usecases]]
=== В каких целях хорошо использовать FreeBSD?

FreeBSD является универсальной операционной системой, которая превосходно работает в различных областях применения.
В частности, она хорошо подходит для организации cерверов, когда стабильность и производительность делают её популярным решением для размещения веб-серверов, баз данных и сетевых приложений.
Надёжно работающие функции информационной безопасности FreeBSD также позиционируют её как сильного кандидата для организации межсетевых экранов и создания устройств обеспечения безопасности.
Кроме серверных решений, FreeBSD может быть адаптирована к работе в специальных условиях, включая встраиваемые системы и игровые консоли.
Её гибкость, надёжность и открытая природа делают FreeBSD привлекательным выбором для решения широкого круга задач информатизации.
 
[[responsible]]
=== Кто отвечает за FreeBSD?

FreeBSD является проектом с открытым кодом, движимым сообществом и имеющим децентрализованную структуру управления.
Её развитие и поддержка осуществляется глобальным сообществом преданных делу добровольцев, разработчиков и организаций, взаимодействующих ради улучшения и расширения операционной системы.

Ключевые решения, касающиеся проекта FreeBSD, такие как общее направление движения проекта или выдача разрешений на добавление кода в дерево исходных текстов, принимаются управляющей командой (Core Team), состоящей из 9 человек.

Такая направленность на взаимное сотрудничество и сообщество стало фундаментом успеха FreeBSD и её живучести в качестве надёжной и устойчивой UNIX-подобной операционной системы.

[[how-to-contribute]]
=== Как я могу внести свой вклад во FreeBSD? Что я могу сделать, чтобы помочь?

Мы принимаем все виды помощи: документацию, код и даже изображения.
Обратитесь к информации о extref:{contributing}[Помощи FreeBSD] для получения совета о том, как сделать это.

И спасибо за то, что вы задумались об этом вопросе!

[[bsd-license-restrictions]]
=== Имеет ли лицензия FreeBSD какие-либо ограничения?

FreeBSD распространяется на условиях https://www.FreeBSD.org/copyright/freebsd-license/[Лицензии BSD], которая известна своим разрешающим характером.

Эта лицензия накладывает очень мало ограничений на то, как вы можете использовать FreeBSD:

* Не заявляйте, что автором являетесь вы.
* Не предъявляйте претензий, если что-то перестало работать.
* Не удаляйте и не изменяйте лицензию.

Такая лицензия подразумевает, что вы можете свободно модифицировать, распространять и даже продавать FreeBSD без того, чтобы *в обязательном порядке публиковать свои модификации как открытый код*.
Однако при распространении FreeBSD имеются минимальные условия, такие как сохранение исходного текста лицензии и оговорок.
В целом Лицензия BSD обеспечивает высокий уровень свободы и гибкости, делая FreeBSD привлекательным выбором для широкого спектра применений и проектов.

Код в нашем дереве исходных текстов, который подпадает под условия лицензии https://www.FreeBSD.org/copyright/COPYING[GNU General Public License (GPL)] или https://www.FreeBSD.org/copyright/COPYING.LIB[GNU Library General Public License (LGPL)], имеет несколько больше ограничений, по крайней мере с точки зрения принудительного доступа к исходных текстам, а не наоборот.

[[replace-current-OS]]
=== Может ли FreeBSD заменить используемую мной операционную систему?

Для многих пользователей и администраторов это так.
Однако на этот вопрос нельзя ответить однозначно.

FreeBSD является мощной операционной системой универсального назначения, которая может выступить заменой или сосуществовать с многими другими операционными системами, в зависимости от специфических потребностей пользователей и администраторов.
Однако решение о возможности замены вашей текущей операционной системы на FreeBSD зависит от таких факторов, как аппаратное обеспечение, требования к программному обеспечению и опыт работы с FreeBSD.

Хотя она является мощной и многофункциональной альтернативой, необходимо оценить специфичные для вас варианты использования и требования к совместимости до того, как выполнять переход.

Если какое-либо приложение доступно только для определённой операционной системы, то эта операционная система не может быть заменена просто так.

Для пользователей, переходящих на FreeBSD с другого UNIX-подобного окружения, она окажется похожей.
Пользователи систем, отличных от UNIX, типа Windows(R), должны быть готовы к тому, чтобы потратить какое-то дополнительное время на изучение способов решения задач в UNIX.

[[run-popular-software]]
=== Работает ли во FreeBSD популярное программное обеспечение с открытым кодом?

Да, FreeBSD хорошо подходит для работы с распространённым программным обеспечением с открытым кодом.
Её совместимость с широким набором приложений и библиотек делает её привлекательным выбором для тех, кто планирует внедрять и использовать пакеты открытого программного обеспечения.
FreeBSD обеспечивает мощное и стабильное окружение, которое поддерживает различные языки программирования, базы данных, веб-серверы и прочее программное обеспечение, часто используемое в сообществве открытого программного обеспечения.
Её система портов и пакетов упрощает установку и управление таким программным обеспечением, гарантируя пользователям простой доступ и запуск их излюбленных инструментов с открытым кодом и приложений во FreeBSD с минимальными сложностями.

[[install-software]]
=== Как я могу установить программное обеспечение во FreeBSD?

FreeBSD предлагает несколько способов установки программного обеспечения.
Один из самых широко используемых способов предполагает использование встроенного менеджера пакетов man:pkg[8], который упрощает процесс, сгружая и устанавливая предварительно построенные бинарные пакеты.
Другим способом является компиляция и установка программного обеспечения из исходных текстов при помощи коллекции портов man:ports[7], которая обеспечивает гибкий и настраиваемый способ установки программного обеспечения.

Документация FreeBSD содержит подробное руководство обоих методов, гарантируя, что пользователи могут легко расширять возможности их системы нужным им программным обеспечением.

[[differences-to-other-bsds]]
=== В чём состоит разница между FreeBSD, NetBSD, OpenBSD и другими операционными системами BSD с открытым кодом?

FreeBSD, NetBSD, OpenBSD и DragonFly BSD все являются частью семейства BSD с открытым кодом и имеют общую UNIX-подобную основу, однако каждая имеет собственные отличные от других направленность и приоритеты.
Эти отличия отражают уникальные цели каждого из проектов, и хотя у них есть общие черты, их специфичные сильные стороны и склонности соответствуют различным областям применения и специализаций внутри экосистемы BSD.

[[freebsd-linux-distribution]]
=== Является ли FreeBSD дистрибутивом Linux(R)?

Нет, FreeBSD - это *не* дистрибутив Linux.

Хотя и FreeBSD, и Linux являются UNIX-подобными операционными системами и имеют много общего, у них разные ядра.
Linux использует ядро Linux, в то время как FreeBSD использует ядро FreeBSD, основанное на дистрибутиве Berkeley Software Distribution (BSD) операционной системы UNIX.

FreeBSD и Linux обе имеют собственные уникальные сообщества разработчиков, циклы выпуска релизов и системные архитектуры, что делает их различными и независимыми операционными системами.

FreeBSD, если сравнивать её с дистрибутивами Linux, обладает своим собственным набором преимуществ, в том числе отличающуюся модель лицензирования, архитектуру системы и пользовательский набор утилит.

[[run-linux-programs-freebsd]]
=== Возможно ли во FreeBSD запускать программы для Linux?

Да, FreeBSD имеет слой совместимости, известный как _linuxulator_ ((man:linux[4]), который обеспечивает функционирование во FreeBSD многих программ для Linux.
Эта функция облегчает исполнение широкого набора бинарных файлов Linux без необходимости в отдельном окружении Linux.

Впрочем, важно отметить, что большое количество широко используемого программного обеспечения с открытым кодом *имеет специальные версии для FreeBSD*, доступные через систему портов и пакетов.

[[installing-freebsd]]
== Установка FreeBSD

Процесс установки FreeBSD является первичным шагом к использованию мощи этой надёжной операционной системы с открытым кодом.
Этот раздел содержит необходимую информацию о том, где получить FreeBSD, подробные инструкции по установке и погружение в такие концепции, как FreeBSD-CURRENT и FreeBSD-STABLE.
Он также углубляется в графики выпуска релизов и снэпшотов, инструменты настройки после установки, способы поиска пакетов и отвечает на общие вопросы, касающиеся обновлений пакетов.

[[where-get]]
=== Где можно получить FreeBSD?

FreeBSD свободно доступна к сгрузке с link:https://www.FreeBSD.org/where/[официального веб-сайта FreeBSD].

Кроме этого, FreeBSD может быть также доступна на различных зеркалирующих сайтах, обеспечивающих её доступность пользователям во всём мире.
link:https://www.FreeBSD.org/where/[Официальный веб-сайт] является первичным и самым надёжным источником получения последних релизов и обновлений FreeBSD, что делает его идеальной отправной точкой для путешествия во FreeBSD.

[[install-instructions-location]]
=== Где находятся инструкции по установке FreeBSD?

Инструкции по установке можно найти в Руководстве в extref:{handbook}bsdinstall/[Главе об установке FreeBSD].

[[current]]
=== В чём состоит концепция FreeBSD-CURRENT?

FreeBSD-CURRENT представляет ветку разработки операционной системы FreeBSD.
Это самая актуальная версия FreeBSD, в которой ведётся активная разработка.

Хотя она включает самые передовые возможности, улучшения и экспериментальные изменения, эта версия может быть не всегда такой же стабильной, как FreeBSD-STABLE или релизные версии.

FreeBSD-CURRENT используется в качестве платформы для разработчиков и энтузиастов, которые хотят внести свой вклад в будущее FreeBSD и оставаться на переднем крае её разработки, несмотря на то, что она может время от времени претерпевать существенные изменения и *не рекомендуется для систем в промышленной эксплуатации*.

[[stable]]
=== В чём состоит концепция FreeBSD-STABLE?

Ветка FreeBSD-STABLE, если сравнивать её с CURRENT, является более стабильной ветвью разработки.
Она содержит код, который проходит дополнительное тестирование и улучшение перед его переносом в ветку RELEASE.
STABLE является хорошим выбором для тех, кто хочет отслеживать разработку FreeBSD, но предпочитает окружение более стабильное, нежели CURRENT.

[[release-freq]]
=== Когда выпускаются релизы FreeBSD?

В среднем {re} выпускает новый старший релиз FreeBSD примерно каждые 18 месяцев, а новый минорный релиз примерно каждые 8 месяцев.
Даты выпуска релизов объявляются весьма заблаговременно, чтобы люди, работающие над системой, знали, когда их проекты должны быть завершены и протестированы.
Каждому релизу предшествует период тестирования, гарантирующий то, что добавление новых функций не снизило стабильности работы релиза.

[[snapshot-freq]]
=== Когда выпускаются снэпшоты FreeBSD?

Снэпшоты FreeBSD, как правило, создаются на регулярной основе для всех активно разрабатываемых веток.
Эти снэпшоты соответствуют состоянию исходного текста FreeBSD и соответствующих двоичных пакетов в какой-то момент времени.
Частота создания таких снэпшотов может варьироваться, однако часто это происходит еженедельно или каждые две недели.
Подобные снэпшоты дают пользователям возможность доступа к последним разработкам и изменениям, выполненными во FreeBSD, помогая им отслеживать состояние проекта.

[[general-configuration-tool]]
=== Существует ли инструмент для выполнения задач настройки после установки?

Да. man:bsdconfig[8] предоставляет удобный интерфейс для настройки FreeBSD после установки.

[[search-software-freebsd]]
=== Как можно найти программное обеспечение для установки во FreeBSD?

Поиск программного обеспечения для установки во FreeBSD легко осуществляется при помощи менеджера пакетов man:pkg[8] и команды `pkg search`.

Пользователи могут применять эту команду для поиска доступных пакетов по ключевым словам, названиям пакетов или описаниям.
Эта функция помогает пользователям быстро найти нужное им программное обеспечение в огромной коллекции поротов и пакетов FreeBSD, упрощая процесс добавления новых приложений и инструментов в их системы FreeBSD.

[[latest-packages-freebsd]]
=== Почему в моей системе FreeBSD отсутствуют самые последние пакеты?

Доступность самых последних пакетов во FreeBSD может зависеть от различных факторов, включая частоту обновления репозитория пакетов и конкретной используемой версии FreeBSD.

Следует также добавить, что для портов FreeBSD существуют две ветки.
Самая часто обновляемая называется `latest`, а самая стабильная называется `quarterly`.
Для того, чтобы использовать самые последние пакеты, потребуется настроить ветку `latest`.
Информацию о том, как настраивать ветки, можно найти в link:{handbook}ports/[главе о портах] Руководства.

[[hardware]]
== Аппаратное обеспечение

В разделе об аппаратном обеспечении рассматривается совместимость FreeBSD с различными конфигурациями оборудования.
В этом разделе рассматриваются различные вопросы, в том числе поддерживаемые архитектуры, максимальная ёмкость ОЗУ, масштабируемость процессоров, совместимость с графическими адаптерами, поддержка адаптеров Wi-Fi и включение поддержки сетевых адаптеров 10 Gigabit Ethernet.
Планируете ли вы разворачивать FreeBSD на серверах, рабочих станциях или специализированном оборудовании, этот раздел даст обзор возможностей и ограничений FreeBSD, раскрывая информацию о вариантах и конфигурациях оборудования.

[[architectures-support]]
=== Какие архитектуры поддерживает FreeBSD?

FreeBSD может похвастаться широким набором поддерживаемых архитектур, что делает её гибким решением для различных аппаратных сред.
Её совместимость расширена до таких архитектур, как `amd64`, `arm64`, `riscv` и других.

Полный список поддерживаемых архитектур можно найти на странице, посвящённой link:https://www.FreeBSD.org/platforms/[платформам].

[[ram-support]]
=== Какой объём ОЗУ поддерживает FreeBSD?

FreeBSD как операционная система в целом поддерживает настолько большой объём физической памяти (ОЗУ), насколько позволяет платформа, на которой она работает.
Имейте в виду, что разные платформы имеют разные ограничения для оперативной памяти.

К примеру, платформы `amd64` поддерживают вплоть до 4 ТБ физической памяти.

[[cpu-support]]
=== Сколько процессоров поддерживает FreeBSD?

Поддержка процессоров во FreeBSD в разных архитектурах различна.
В системах amd64 и arm64 FreeBSD может эффективно использовать ресурсы до 1024 процессоров.
В случае систем, построенных на основе powerpc, FreeBSD поддерживает вплоть до 256 процессоров, тогда как в системах risc-v она может эффективно использовать вплоть до 16 процессоров.

[[graphics-cards-support]]
=== Какие графические адаптеры поддерживает FreeBSD?

Хорошо поддерживаются популярные поставщики графических решений, такие как Intel(R), AMD(R) или NVIDIA(R).

Список поддерживаемых графических адаптеров link:https://wiki.freebsd.org/Graphics/Intel-GPU-Matrix[Intel] и link:https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[AMD] можно найти во FreeBSD Wiki.

[[wifi-support]]
=== Какие адаптеры Wi-Fi поддерживаются во FreeBSD?

Уточнение совместимости FreeBSD с различными адаптерами Wi-Fi облегчает подключение вашей системы к беспроводным сетям.

Список USB-устройств Wi-Fi, о которых известно, что они хорошо работают с FreeBSD:

* USB-адаптеры RT5370 (поддерживает режим hostap)
* TP-Link TL-WDN3200 (RT5592, man:if_run[4])
* TP-Link TL-WN725N v2 (RTL8188EU, man:rtwn[4])
* TP-Link Archer T4U (RTL8812AU, man:rtwn[4])
* D-Link DWA-131 (RTL8192CU, man:rtwn[4])
* D-Link DWA-171 rev A1 (RTL8821AU, man:rtwn[4])
* ASUS USB-N10 NANO (RTL8188CUS, man:rtwn[4])

Список устройств Mini PCIe Wi-Fi, о которых известно, что они хорошо работают с FreeBSD:

* Realtek RTL8188CE Mini PCIe

[[gigabit-ethernet-network-support]]
=== Поддерживает ли FreeBSD сетевые адаптеры 10 Gigabit Ethernet?

FreeBSD обеспечивает надёжную поддержку сетевых адаптеров 10 Gigabit Ethernet, что делает её жизнеспособным выбором для высокоскоростных сетевых сред.
Ядро FreeBSD содержит драйверы для широкой линейки адептеров 10 Gigabit Ethernet различных производителей, гарантируя бесшовную интеграцию и оптимальную производительность сети.

Дополнительную информацию можно получить во link:https://wiki.freebsd.org/Networking/10GbE[FreeBSD Wiki].

[[documentation-support]]
== Документация и поддержка

Этот раздел содержит ценные материалы для тех, кто ищет возможности для углубления своих знаний о FreeBSD.
В нём освещается широкий спектр вопросов, включая список рекомендуемых книг для изучения FreeBSD, предложения коммерческих тренингов и поддержки, вводные тренинги для понимания внутреннего устройства FreeBSD и места поиска поддержки в сообществе FreeBSD.

[[books]]
=== Какие есть хорошие книги о FreeBSD?

Энтузиасты FreeBSD и те, кто занимаются её изучением, могут найти большой набор информативных книг, посвящённых этой операционной системе.
В этих книгах освещаются вопросы, варьирующихся от основ FreeBSD до глубоких вопросов системного администрирования и разработки.

Среди всех прочих достойны внимания "Absolute FreeBSD: The Complete Guide To FreeBSD" (автор Michael W. Lucas) и "FreeBSD Mastery series" (автором также является Michael W. Lucas).
Эти материалы дают ценное погружение и знания, помогающие пользователям всех уровней оттачивать свои знания FreeBSD и максимально использовать её потенциал.

Кроме этих книг, Проект FreeBSD формирует большой набор документации, доступной в онлайне на link:https://docs.FreeBSD.org/[Портале документации].

[[training]]
=== Где можно пройти тренинги и получить поддержку FreeBSD на коммерческой основе?

Для тех, кому нужны профессиональные тренинги и поддержка FreeBSD, несколько коммерческих поставщиков могут предложить свои услуг на заказ.
Проект FreeBSD ведёт link:https://www.freebsd.org/commercial/[список компаний], у которых можно запросить поддержку.

[[learn-advanced]]
=== Как можно получить больше информации о внутренней организации FreeBSD?

Для более глубокого погружения во внутренние механизмы работы FreeBSD заинтересованные лица могут обратиться к материалам, подобным "The Design And Implementation Of The FreeBSD Operating System".
extref:{arch-handbook}[FreeBSD Architecture Handbook] является ещё одним значимым источником, который содержит подробную информацию об архитектуре FreeBSD, организации системы и принципам проектирования.

Кроме того, анализ исходного кода FreeBSD, доступного через репозиторий исходных текстов FreeBSD, даёт существенное погружение в компоненты кода этой операционной системы.

[[help-freebsd-system]]
=== Как получить помощь в самой системе FreeBSD?

Получить помощь внутри системы FreeBSD несложно.
FreeBSD имеет огромный объём встроенной документации, доступной при помощи команды man:man[1], предлагающей всеобъемлющую информацию о различных командах и компонентах системы.

Вдобавок extref:{handbook}[Руководство по FreeBSD], доступное как в онлайне, так и локально в системе, служит ценным источником для получения подробных инструкций.

При возникновении специфичных проблем поиск помощи в сообществе FreeBSD с помощью списков рассылки, форумов или IRC может дать своевременное решение и идеи от опытных пользователей и разработчиков FreeBSD.

[[community-questions]]
== Вопросы о сообществе

Изучите этот раздел для выяснения способов влиться в сообщество FreeBSD.

Изучите информацию о каналах IRC, посвящённых FreeBSD, для ведения обсуждений в реальном времени, веб-форумах для обмена идеями и доступе к спискам рассылки и новостным группам FreeBSD для глубоких обсуждений и получения свежих новостей.

[[irc]]
=== Существуют ли каналы IRC (Internet Relay Chat), посвящённые FreeBSD?

Да, большинство из крупнейших сетей IRC имеют канал обсуждения FreeBSD, а на wiki-странице FreeBSD размещён актуальный link:https://wiki.freebsd.org/IRC/Channels[список каналов IRC].

Все эти каналы разные и не связаны друг с другом.
Так как стили общения в них отличаются, попробуйте каждый и найдите тот, что соответствует вашему.

[[forums]]
=== Существуют ли веб-форумы для обсуждения FreeBSD?

Официальные форумы FreeBSD размещены на главной странице link:https://forums.FreeBSD.org/[Форумов FreeBSD].

[[mailing]]
=== Где я могу найти информацию о списках рассылки FreeBSD?

Открыто доступные списки рассылки можно найти на странице link:https://lists.freebsd.org/[списков рассылки FreeBSD].

[[misc]]
== Разные вопросы

Ознакомьтесь с разнообразными интересными и практическими запросами о FreeBSD, покрывающие темы от выбора оболочки командной строки до странностей системы и даже имени символа FreeBSD.

[[minimal-sh]]
=== Почему /bin/sh так минималистична? Почему во FreeBSD не используется bash или другая оболочка командной строки?

Многим людям требуется создавать скрипты командного процессора, которые должны быть переносимы между многими системами.
Именно поэтому POSIX(R) с величайшмими подробностями описывает оболочку командной строки и утилиты.
Большинство скриптов написаны на языке командного процессора Bourne (man:sh[1]), в том числе потому что несколько важных программных интерфейсов указывают на использование оболочки Bourne для интерпретации команд.
По причине того, что командный процессор Bourne так часто и широко используется, для него важна возможность быстрого запуска, отсутствие неопределённостей в поведении и низкая нагрузка на оперативную память.

Имеющаяся в системе реализация является результатом наших усилий по обеспечению соответствия максимальному количеству этих требований.
Для того, что оставить размер `/bin/sh` небольшим, в ней не реализованы многие из удобных функций, имеющихся в других командных процессорах.

Вот почему вам доступны другие более функционально богатые оболочки типа `bash`, `scsh`, man:tcsh[1] и `zsh`.


[[keyboard-delete-key]]
=== Как задействовать клавишу удаления в sh и csh?

При использовании оболочки Bourne Shell добавьте следующие строки в файл [.filename]#~/.shrc#:

[.programlisting]
....
bind ^[[3~ ed-delete-next-char # для xterm
....

При использовании оболочки C Shell добавьте следующие строки в файл [.filename]#~/.cshrc#:

[.programlisting]
....
bindkey ^[[3~ delete-char # для xterm
....

[[forgot-root-pw]]
=== Я забыл пароль системного админситратора root! Что мне делать?

Без паники!
Перезапустите систему, введите `boot -s` в строке приглашения `Boot:` для перехода в однопользовательский режим.
При появлении вопроса об используемой оболочке нажмите kbd:[Enter], после чего отобразится приглашение #.
Введите команду `mount -urw /` для повторного монтирования корневой файловой системы в режиме чтения/записи, а затем запустите команду `mount -a` для монтирования всех файловых систем.
Выполните команду `passwd root` для изменения пароля пользователя `root`, а затем выполните man:exit[1] для продолжения процесса загрузки.

[TIP]
====
Если при переходе в однопользовательский режим вам всё ещё предлагается ввести пароль пользователя `root`, это значит, что консоль была помечена небезопасной (`insecure`) в файле [.filename]#/etc/ttys#.
В этом случае потребуется выполнить загрузку с установочного диска FreeBSD, выбрать [.guimenuitem]#Live CD# или [.guimenuitem]#Shell# в начале процессу установки и выполнить указанные выше команды.
В таком случае смонтируйте конкретный раздел диска и примените для него chroot.
К примеру, замените `mount -urw /` на `mount /dev/ada0p1 /mnt; chroot /mnt` для системы, располагающейся на _ada0p1_.
====

[TIP]
====
Если корневой раздел не может быть смонтирован в однопользовательском режиме, то, возможно, разделы зашифрованы и их невозможно смонтировать без ключа доступа.
Для получения дополнительной информации обратитесь к разделу о шифровании дисков в extref:{handbook}disks/[Руководстве, disks-encrypting] по FreeBSD.
====

[[rcconf-readonly]]
=== Я ошибся в файле rc.conf или каком-то другом файле запуска системы, и теперь я не могу его отредактировать, потому что файловая системы доступна только для чтения. Что мне делать?

Перезапустите системы при помощи команды `boot -s` в приглашении загрузчика для перехода в однопользовательский режим.
После получения запроса на указание маршрута к оболочке, нажмите kbd:[Enter] и запустите команду `mount -urw /` для перемонтирования корневой файловой системы в режиме чтения/записи.
Вам может также понадобиться выполнить команду `mount -a -t ufs` для монтирования файловой системы, в которой находится ваш текстовый редактор.
Если этот текстовый редактор размещён в сетевой файловой системе, то либо настройте сеть вручную перед монтированием сетевой файловой системы, либо используйте редактор, доступный в локальной файловой системе, такой как man:ed[1].

Для того, чтобы использовать полноэкранный редактор, такой как man:vi[1] или man:emacs[1], выполните команду `ex port TERM=xterm`, чтобы эти редакторы могли загрузить корректные данные из базы данных man:termcap[5].

После выполнения этих шагов отредактируйте файл [.filename]#/etc/rc.conf# для исправления синтаксической ошибки.
Сообщение об ошибке, отображаемое сразу после сообщений загрузки ядра, должна указать на номер строки в файле, содержащей ошибку.

[[free-memory-amount]]
=== Каков объём доступной свободной памяти?

Есть пара видов "свободной памяти".
Самым распространённым является объём памяти, доступный прямо сейчас без высвобождения уже используемой памяти.
Это размер очереди свободных страниц плюс объём некоторых других зарезервированных страниц.
Этот объём экспортируется через man:sysctl[8]-переменную `vm.stats.vm.v_free_count`, отображаемую, например, командой man:top[1].
Другим видом "свободной памяти" является общий объём виртуальной памяти, доступный пользовательским процессам, и который зависит от суммы размера файла подкачки и доступной к использованию памяти.
Возможно описать и другие виды "свободной памяти", однако это относительно бесполезное занятие, ведь более важно быть уверенным, что уровень подкачки страниц сохраняется низким, и избегать исчерпания места для пространства подкачки.

[[timezone]]
=== Время отображается некорректно. Как изменить часовой пояс?

Воспользуйтесь утилитой man:tzsetup[8].


[[more-swap]]
=== FreeBSD использует большой объём памяти подкачки, даже когда в компьютере остаётся свободная память. Почему?

FreeBSD будет проактивно перемещать полностью простаивающие, неиспользуемые страницы основной памяти в подкачку для того, чтобы обеспечить доступность дополнительных объёмов основной памяти для активного использования.
Такое плотное использование подкачки балансируется использованием дополнительной свободной памяти для кэширования.

Обратите внимание на то, что хотя FreeBSD ведёт себя с этой точки зрения проактивно, она не предпринимает намеренных действий по выгрузке страниц в пространство подкачки, если система действительно простаивает.
Таким образом, вся система не окажется в пространстве подкачки, если оставить её на ночь без нагрузки.


[[top-freemem]]
=== Почему утилита top показывает очень малый объём свободной памяти, даже когда запущено очень небольшое количество программ?

Простое объяснение заключается в том, что свободная память является памятью, которая тратится впустую.

Любая память, которая активно не используется программами, используется ядром FreeBSD как дисковый кэш.
Значения, отображаемые man:top[1] и помеченные как `Inact` и `Laundry`, соответствуют кэшированным данным разной степени устаревания.
Наличие таких кэшированных данных означает, что системе не нужно повторно обращаться к медленному диску за недавними данными, таким образом увеличивая общую производительность.
В целом низкое значение показателей памяти `Free`, отображаемое в man:top[1], является хорошим признаком, если это значение не _очень_ низкое.

[[daemon-name]]
=== Как зовут этого симпатичного мелкого красного парня?

Имени у него нет, и все зовут его просто "даемон BSD".
Если вы настаиваете на использовании имени, то называйте его "beastie".
Заметьте, что "beastie" произносится как "BSD".

Больше информации о даемоне BSD находится на его http://www.mckusick.com/beastie/index.html[домашней странице].


[[use-beastie]]
=== Могу ли я использовать изображение даемона BSD?

Вполне может быть.
Авторскими правами на даемона BSD владеет Маршалл Кирк МакКузик.
Для получения подробных условий использования обратитесь к его http://www.mckusick.com/beastie/mainpage/copyright.html[Декларации об использовании образа даемона BSD].

Если кратко, то изображение может быть использовано подобающим образом и для личных нужд, пока действует соответствующее разрешение.
Перед тем, как использовать логотип в коммерческих целях, обратитесь к {mckusick} для получения разрешения.
Дополнительную информацию можно найти на http://www.mckusick.com/beastie/index.html[домашней странице даемона BSD].

[[bikeshed-painting]]
=== Почему я должен беспокоиться о цвете велосипедного сарая?

На самом деле, очень и очень краткий ответ на этот вопрос заключается в том, что вы этого делать не должны.
Если давать более подробный ответ, то ваше умение делать велосипедные сараи не должно означать, что вы должны препятствовать другим делать их просто потому, что вам не нравится цвет, в который они собираются их окрашивать.
Эта метафора означает, что вам не нужно обсуждать каждую мелочь просто потому, что вы знаете о ней достаточно много, чтобы принять участие в обсуждении.
Замечено, что объём шума, генерируемый при появлении некоторого изменения, находится в обратной зависимости от сложности самого изменения.

Более подробный и полный ответ заключается в том, что после очень долгих споров вокруг того, должна ли утилита man:sleep[1] обрабатывать дробное число секунд, заданное в качестве параметра, {phk} опубликовал длинное сообщение, озаглавленное как link:http://www.bikeshed.com[Велосипедный сарай (любого цвета) на зелёной траве...].

[[funnies]]
== Юмор от FreeBSD

Отвлекитесь от технических вопросов и погрузитесь в шутливую сторону FreeBSD.

[[very-very-cool]]
=== Насколько горяча FreeBSD?

[qanda]
Кто-нибудь делал замеры температуры при работе FreeBSD?::
Нет, однако мы провели различные вкусовые тесты у добровольцев с завязанными глазами, которые до этого приняли по 250 микрограмм LSD-25.
35% участников заявили, что FreeBSD имеет вкус апельсина, тогда как вкус Linux(R) был похож на сиреневый туман.
Ни одна из групп не отметила значительной разницы в температуре.

Если серьёзно, то FreeBSD использует ACPI (Advanced Configuration and Power Interface), и потому может переводить ЦП в режим низкого энергопотребления.
 
[[dev-null]]
=== Куда направляются данные, записываемые в /dev/null?

Они отправляются в специальную сточную трубу для данных в ЦП, где преобразуются в тепло, выдуваемое через охлаждающие вентиляторы.
Вот почему охлаждение ЦП становится всё более важным; так как люди привыкают ко всё более быстрым процессорам, они всё менее заботятся о данных, и всё большее их количество оканчивает свой путь в [.filename]#/dev/null#, перегревая ЦП.
Если вы удалите [.filename]#/dev/null# (что фактически отключит трубу данных в ЦП), то ваш процессор может охладиться, но система начнет переполняться излишними данными и начнёт работать с ошибками.
Если у вас быстрое сетевое подключение, вы можете охладить CPU, читая данные из [.filename]#/dev/random# и посылая их куда-нибудь; однако вы рискуете перегреть ваше сетевое соединение и [.filename]#/# или разозлить вашего провайдера, так как большинство данных преобразуется в тепло на его оборудовании, но, как правило, у него хорошее охлаждение, так что если вы не перестараетесь, то всё должно быть в порядке.

[[punk-my-friend]]
=== Мой коллега проводит слишком много времени за компьютером. Как отвадить его от этого занятия?

Установите пакет package:games/sl[] и дождитесь момента, когда он ошибочно
введёт `sl` вместо `ls`.

[[acknowledgments]]
== Наши благодарности

За последние десятиления этот документ с ответами на часто задаваемые вопросы претерпел бесчисленное количество пересмотров и улучшений, осуществлённых разнородной группой контрибуторов.
