#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: head/ru_RU.KOI8-R/Makefile 38886 2012-05-25 14:40:55Z taras $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/Makefile,v 1.3 2004/02/21 15:25:00 andy Exp $
#
# Original revision: r38886
#

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = ru

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
