//
// The FreeBSD Russian Documentation Project
//
// Original EN revision: SVN 47566 (partial!)
//

---
title: Глава 6. X Window System
part: Часть I. В начале
prev: books/handbook/ports
next: books/handbook/partii
showBookMenu: true
weight: 8
path: "/books/handbook/"
---

[[x11]]
= X Window System
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/x11/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[x11-synopsis]]
== Обзор

Процедура установки FreeBSD при помощи bsdinstall не предусматривает автоматической установки графического пользовательского интерфейса.
Эта глава описывает процесс установки и настройки пакета Xorg, предоставляющий X Window System с открытым кодом, обеспечивающий графическую среду работы.
Затем она объясняет, как найти и установить оболочку рабочего стола или оконный менеджер.

[TIP]
====
Пользователи, предпочитающие метод установки, при котором Xorg настраивается автоматически и предлагаются варианты выбора оконных менеджеров, должны обратить внимание на веб-сайт link:http://www.pcbsd.org/[pcbsd.org].
====

Для получения дополнительной информации об оборудовании, которое поддерживается в Xorg, обратитесь к веб-сайту link:http://www.x.org/[x.org].

После чтения этой главы вы будете знать:

* О различных компонентах X Window System и их взаимодействии.
* Как установить и настроить Xorg.
* Как установить и настроить несколько оконных менеджеров и оболочек рабочего стола.
* Как установить и использовать различные оконные менеджеры.
* Как использовать шрифты TrueType(R) в Xorg.
* Как настроить вашу систему на графический интерфейс входа (XDM).

Перед чтением этой главы вам требуется:

* Знать, как устанавливать дополнительное программное обеспечение сторонних разработчиков в соответствии с описанием в разделе crossref:ports[ports, Установка приложений. Порты и пакеты].

[[x-understanding]]
== Терминология

Хотя нет необходимости вникать во все тонкости различных компонент X Window System и взаимодействия между ними, некоторые базовые знания об этих компонентах могут быть полезными.

X-сервер::
X изначально разрабатывалась, чтобы быть системой, ориентированной на работу в сети, и использует модель "клиент-сервер".
В этой модели "X-сервер" работает на компьютере с клавиатурой, монитором и мышью.
Область ответственности сервера включает управление дисплеем, обработку ввода с клавиатуры и мыши, а также обработку ввода и вывода с других устройств, таких, как планшет или видеопроектор.
Некоторых это запутывает, потому что терминология X в точности противоположна тому, что они ожидают.
Они полагают, что "X-сервером" будет являться большая мощная машина в конце коридора, а "X-клиентом" выступает компьютер на их рабочем столе.

X-клиент::
Каждое X-приложение, такое, как XTerm или Firefox, является "клиентом".
Клиент посылает сообщения серверу, такие, как "Пожалуйста, нарисуй окно со следующими координатами", а сервер посылает в ответ сообщения типа "Пользователь только что щёлкнул мышью на кнопке OK".

При использовании дома или в офисе, сервер и клиенты X, как правило, работают на том же самом компьютере.
Однако можно также запустить X-сервер на более слабом компьютере, а приложения X запускать на более мощной системе.
При таком сценарии коммуникации между X-клиентом и сервером осуществляются по сети.

оконный менеджер::
X не определяет, как окна должны выглядеть на экране, как их двигать мышью, какие комбинации клавиш должны использоваться для переключения между окнами, как должны выглядеть заголовки окон, должны ли в них быть кнопки для закрытия и так далее.
Вместо этого X делегирует ответственность за это отдельному приложению управления окнами.
Существуют link:http://xwinman.org/[десятки оконных менеджеров].
Каждый оконный менеджер реализует собственный внешний вид и подход к управлению: некоторые поддерживают виртуальные рабочие столы, некоторые позволяют изменять назначения комбинаций клавиш для управления рабочим окружением, в некоторых есть кнопка "Пуск", а некоторые поддерживают "темы", позволяя полностью менять образ рабочего окружения.
Оконные менеджеры находятся в категории [.filename]#x11-wm# Коллекции Портов.

Каждый оконный менеджер использует собственный механизм настройки.
Некоторые предполагают наличие вручную созданного конфигурационного файла, тогда как другие предоставляют графические инструменты для выполнения большинства задач по настройке.

оболочки рабочего стола::
KDE и GNOME рассматриваются как оболочки для организации рабочего стола, так как они включают в себя полный набор приложений для выполнения повседневной работы.
Сюда могут входить офисные пакеты, web-браузеры и игры.

политика фокусирования::
Менеджер окон отвечает за политику фокусирования мыши.
Эта политика предоставляет некоторый механизм, который определяет, какое окно активно обрабатывает нажатия клавиш, а также визуально отображает, какое окно является в настоящий момент активным.

Одна из политик фокусирования называется "фокусирование по щелчку".
В такой модели окно становится активным после получения щелчка мыши.
В политике "фокус следует за мышью" фокус получает окно, находящееся под указателем мыши, и этот фокус меняется при указании на другое окно.
Если мышь находится поверх корневого окна, то фокусирование производится на этом окне.
В модели "нечёткого фокусирования" при перемещении мыши на корневое окно фокус остаётся на последнем используемом окне.
При нечётком фокусовании фокус меняется только при перемещении курсора на новое окно, и не меняется при выходе из текущего окна.
В политике "фокусирования по щелчку" активное окно появится поверх всех других окон.
Все нажатия клавиш при этом будут направляться в это окно, даже если указатель переместился на другое окно.

Разные оконные менеджеры поддерживают разные модели фокусирования.
Все они поддерживают фокусирование по щелчку, и большинство также поддерживает другие политики.
Обратитесь к документации по оконному менеджеру для выяснения доступности моделей фокусирования.

виджеты::
Виджет - это термин, употребляемый для любых объектов пользовательского интерфейса, на которые можно щёлкать или которыми можно манипулировать каким-либо образом.
Сюда включаются кнопки, зависимые и независимые опции, иконки и списки.
Библиотека виджетов представляет собой набор виджетов, используемых для создания графических приложений.
Существует несколько популярных библиотек виджетов, среди которых Qt, используемый в KDE, и GTK+, применяемый в GNOME.
В результате приложения будут иметь разный внешний вид в зависимости от того, какая библиотека использовалась для создания приложения.

XXX
[[x-install]]
== Установка X11

Версией X11 по умолчанию для FreeBSD является Xorg. Xorg это сервер X дистрибутива открытой реализации X Window System, выпущенной X.Org Foundation. Xorg основан на коде XFree86(TM) 4.4RC2 и X11R6.6. Версия Xorg, доступная на данный момент из коллекции портов FreeBSD: 7.7.

Для сборки и установки Xorg из Коллекции портов, выполните:

[source,shell]
....
# cd /usr/ports/x11/xorg
# make install clean
....

[NOTE]
====
Перед сборкой полной версии Xorg удостоверьтесь в наличии хотя бы 4 GB свободного места.
====

Кроме того, X11 может быть установлен непосредственно из пакетов. Бинарные пакеты, устанавливаемые man:pkg_add[1], доступны и для X11. Когда man:pkg_add[1] используется для удаленной загрузки пакетов, номер версии пакета необходимо удалить. man:pkg_add[1] автоматически установит последнюю версию приложения.

Таким образом, для загрузки и установки пакета Xorg, просто наберите:

[source,shell]
....
# pkg_add -r xorg
....

[NOTE]
====
В примерах выше будет установлен полный дистрибутив X11, включая серверы, клиенты, шрифты и так далее. Также доступны и отдельные пакеты и порты для различных частей X11.
====

В оставшейся части главы будет рассказано о том, как сконфигурировать X11 и настроить рабочее окружение.

[[x-config]]
== Конфигурация X11

=== Перед тем, как начать

Перед настройкой X11 необходима следующая информация о конфигурируемой системе:

* Характеристики монитора
* Набор микросхем, используемый в видеоадаптере
* Объём видеопамяти

Характеристики монитора используются в X11 для определения рабочего разрешения и частоты. Эти характеристики обычно могут быть получены из документации, которая прилагается к монитору или с сайта производителя. Тут нужны два диапазона значений, для частоты горизонтальной развёртки и для частоты вертикальной синхронизации.

Набор микросхем графического адаптера определяет, модуль какого драйвера использует X11 для работы с графическим оборудованием. Для большинства типов микросхем это может быть определено автоматически, но все же его полезно знать на тот случай, когда автоматическое определение не работает правильно.

Объём видеопамяти графического адаптера определяет разрешение и глубину цвета, с которым может работать система. Это важно, чтобы пользователь знал ограничения системы.

=== Конфигурирование X11

Начиная с версии 7.3, Xorg зачастую может работать без какого-либо файла настройки, для его запуска достаточно просто набрать:

[source,shell]
....
% startx
....

Начиная с версии 7.4, Xorg может использовать HAL для автоматического поиска клавиатуры и мыши. Порты package:sysutils/hal[] и package:devel/dbus[] будут инсталлированы как зависимости package:x11/xorg[], но для их включения необходимо иметь следующие записи в [.filename]#/etc/rc.conf# file:

[.programlisting]
....
hald_enable="YES"
dbus_enable="YES"
....

Эти сервисы должны быть запущены (вручную или при загрузки системы) до последующей загрузки Xorg конфигурации.

Автоматическая конфигурация не всегда может сработать на некотором оборудовании, либо создать не совсем ту настройку, которая желаема. В этих случаях, необходима ручная настройка конфигурации.

[NOTE]
====
Такие оконные менеджеры, как GNOME, KDE или Xfce имеют собственные утилиты, позволяющие пользователю легко устанавливать такие параметры, как разрешение экрана. Поэтому, если конфигурация по-умолчанию не подходящая и вы планируете инсталлировать эти оконные менеджеры, просто можете продолжить настройку рабочей среды, используя их собственные утилиты для установок параметров экрана.
====

Процесс настройки X11 является многошаговым. Первый шаг заключается в построении начального конфигурационного файла. Работая с правами суперпользователя, просто запустите:

[source,shell]
....
# Xorg -configure
....

При этом в каталоге [.filename]#/root# будет создан скелет конфигурационного файла X11 под именем [.filename]#xorg.conf.new# (там, куда после man:su[1] или непосредственного входа будет указывать переменная `$HOME`). Программа X11 сделает попытку распознать графическое оборудование системы и запишет конфигурационный файл, загружающий правильные драйверы для обнаруженного оборудования в системе.

Следующим шагом является тестирование существующей конфигурации для проверки того, что Xorg может работать с графическим оборудованием в настраиваемой системе. Для этого выполните:

[source,shell]
....
# Xorg -config xorg.conf.new
....

Начиная с Xorg 7.4 и выше, это тестирование покажет лишь черный экран, что делает диагностику не совсем полноценным. Старое поведение будет доступно при использовании опции `retro`

[source,shell]
....
# Xorg -config xorg.conf.new -retro
....

Если появилась чёрно-белая сетка и курсор мыши в виде X, то настройка была выполнена успешно. Для завершения тестирования просто нажмите одновременно kbd:[Ctrl+Alt+Backspace].

[NOTE]
====
Данная комбинация включена по-умолчанию до Xorg версии 7.3. Для включения этого в версии 7.4 и выше, вы должны ввести следующую команду в любом эмуляторе X терминала:

[source,shell]
....
% setxkbmap -option terminate:ctrl_alt_bksp
....

или создать конфигурационный файл клавиатуры для hald называемый [.filename]#x11-input.fdi# и сохранить его в [.filename]#/usr/local/etc/hal/fdi/policy# директории. Данный файл должен содержать следующие строчки:

[.programlisting]
....
<?xml version="1.0" encoding="utf-8"?>
<deviceinfo version="0.2">
  <device>
    <match key="info.capabilities" contains="input.keyboard">
	  <merge key="input.x11_options.XkbOptions" type="string">terminate:ctrl_alt_bksp</merge>
    </match>
  </device>
</deviceinfo>
....

Вам может потребоваться перезагрузка системы для вступления параметров hald в силу.
====

Если мышь не работает, ее необходимо настроить. Обратитесь к crossref:install[mouse,Настройка мыши (Mouse Settings)] в главе об установке FreeBSD. Дополнительно, начиная с версии 7.4, секция `InputDevice` в [.filename]#xorg.conf# игнорируется в пользу автоматического поиска устройств. Для возвращения старого поведения, добавьте следующие строчки в секции `ServerLayout` или `ServerFlags`:

[.programlisting]
....
Option "AutoAddDevices" "false"
....

Устройства ввода могут конфигурированы затем как в предыдущих версиях, вместе с другими необходимыми опциями (такими, как переключение раскладок клавиатуры например).

[NOTE]
====
Как ранее уже сообщалось, начиная с версии 7.4, по-умолчанию, hald демон будет пытаться распознать вашу клавиатуру автоматически. Есть возможность, что раскладка вашей клавиатуры или ее модель будут определены некорректно. Такие оконные менеджеры как GNOME, KDE или Xfce содержат свои инструменты для конфигурирования клавиатур. Тем не менее, можно установить параметры клавиатуры непосредственно с помощью утилиты man:setxkbmap[1] или через haldконфигурационные правила.

Например, если вы хотите использовать клавиши PC 102 клавиатуры, идущая с французской раскладкой, мы должны создать конфигурационный файл клавиатуры для hald называемый [.filename]#x11-input.fdi# и сохранить в [.filename]#/usr/local/etc/hal/fdi/policy# директории. Этот файл должен содержать следующие строчки:

[.programlisting]
....
<?xml version="1.0" encoding="utf-8"?>
<deviceinfo version="0.2">
  <device>
    <match key="info.capabilities" contains="input.keyboard">
	  <merge key="input.x11_options.XkbModel" type="string">pc102</merge>
	  <merge key="input.x11_options.XkbLayout" type="string">fr</merge>
    </match>
  </device>
</deviceinfo>
....

Если этот файл уже существует, просто скопируйте и добавьте эти строчки в данный файл.

Вы должны будете перезагрузить систему, чтобы заставить hald применить настройки.

Есть возможность проделать ту же конфигурацию из X терминала или скрипт следующей командой:

[source,shell]
....
% setxkbmap -model pc102 -layout fr
....

Файл [.filename]#/usr/local/shared/X11/xkb/rules/base.lst# содержит список различных клавиатур, доступные опции и раскладки.
====

Теперь выполните тонкую настройку в файле [.filename]#xorg.conf.new# по своему вкусу. Откройте файл в текстовом редакторе, таком, как man:emacs[1] или man:ee[1]. Сначала задайте частоты для монитора. Они обычно обозначаются как частоты горизонтальной и вертикальной синхронизации. Эти значения добавляются в файл [.filename]#xorg.conf.new# в раздел `"Monitor"`:

[.programlisting]
....
Section "Monitor"
        Identifier   "Monitor0"
        VendorName   "Monitor Vendor"
        ModelName    "Monitor Model"
        HorizSync    30-107
        VertRefresh  48-120
EndSection
....

Ключевых слов `HorizSync` и `VertRefresh` может и не оказаться в файле конфигурации. Если их нет, то они должны быть добавлены, с указанием корректных значений горизонтальной частоты синхронизации после ключевого слова `HorizSync` и вертикальной частоты синхронизации после ключевого слова `VertRefresh`. В примере выше были введены частоты монитора настраиваемой системы.

X позволяет использовать возможности технологии DPMS (Energy Star) с поддерживающими её мониторами. Программа man:xset[1] управляет временными задержками и может явно задавать режимы ожидания, останова и выключения. Если вы хотите включить использование возможностей DPMS вашего монитора, вы должны добавить следующую строку в раздел, описывающий монитор:

[.programlisting]
....
Option       "DPMS"
....

Пока файл конфигурации [.filename]#xorg.conf.new# открыт в редакторе, выберите желаемые разрешение и глубину цвета, которые будут использоваться по умолчанию. Они задаются в разделе `"Screen"`:

[.programlisting]
....
Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
        DefaultDepth 24
        SubSection "Display"
                Viewport  0 0
                Depth     24
                Modes     "1024x768"
        EndSubSection
EndSection
....

Ключевое слово `DefaultDepth` описывает глубину цвета, с которой будет работа по умолчанию. Это значение может быть переопределено при помощи параметра командной строки `-depth` для man:Xorg[1]. Ключевое слово `Modes` описывает разрешение, с которым нужно работать при данной глубине цвета. Заметьте, что поддерживаются только те стандартные режимы VESA, что определены графическим оборудованием настраиваемой системы. В примере выше глубина цвета по умолчанию равна двадцати четырём битам на пиксел. При такой глубине цвета принимается разрешение в 1024 на 768 точек.

Наконец, запишите конфигурационный файл и протестируйте его при помощи тестового режима, описанного выше.

[NOTE]
====
При решении проблем могут помочь лог файлы X11, в которых находится информация по каждому устройству, к которому подключен сервер X11. Лог файлам Xorg названия даются в формате [.filename]#/var/log/Xorg.0.log#. Имена лог файлам могут даваться от [.filename]#Xorg.0.log# до [.filename]#Xorg.8.log# и так далее.
====

Если все в порядке, то конфигурационный файл нужно установить в общедоступное место, где его сможет найти man:Xorg[1]. Обычно это [.filename]#/etc/X11/xorg.conf# или [.filename]#/usr/local/etc/X11/xorg.conf#.

[source,shell]
....
# cp xorg.conf.new /etc/X11/xorg.conf
....

Теперь процесс настройки X11 завершен. Xorg теперь можно запустить с помощью man:startx[1]. X11 можно также запустить через man:xdm[1].

=== Тонкие вопросы настройки

==== Конфигурирование при работе с графическими чипсетами Intel(R) i810

Конфигурирование при работе с интегрированными наборами микросхем Intel(R) i810 требует наличия [.filename]#agpgart#, программного интерфейса AGP, посредством которого X11 будет управлять адаптером. Подробности смотрите на странице справочника man:agp[4].

Это позволит конфигурировать графическое оборудование точно так же, как и любой другой графический адаптер. Заметьте, что для систем, у которых драйвер man:agp[4] в ядро не вкомпилирован, попытка погрузить модуль с помощью man:kldload[8] окончится неудачно. Этот драйвер должен оказаться в ядре во время загрузки, либо вкомпилированным, либо подгруженным посредством [.filename]#/boot/loader.conf#.

==== Настройка широкоэкранного режима

Для этого раздела необходимо несколько больше навыков настройки. Если после использования описанных выше инструментов настройки в результате рабочей конфигурации не получается, в лог файлах достаточно информации для доведения конфигурации до рабочего уровня. Для настройки используется текстовый редактор.

Существующие широкоэкранные стандарты (WSXGA, WSXGA+, WUXGA, WXGA, WXGA+, и т.д.) поддерживают форматы изображения 16:10 и 10:9, которые могут быть проблемными. Для формата 16:10, например, возможны следующие разрешения экрана:

* 2560x1600
* 1920x1200
* 1680x1050
* 1440x900
* 1280x800

Иногда достаточно добавить одно из этих разрешений в качестве параметра `Mode` в раздел `Section "Screen"` вот так:

[.programlisting]
....
Section "Screen"
Identifier "Screen0"
Device     "Card0"
Monitor    "Monitor0"
DefaultDepth 24
SubSection "Display"
	Viewport  0 0
	Depth     24
	Modes     "1680x1050"
EndSubSection
EndSection
....

Xorg может извлечь информацию о разрешении из монитора посредством I2C/DDC, так что у него есть данные, какие частоты и разрешения может поддерживать монитор.

Если эти `ModeLines` не определены в драйверах, может потребоваться дополнительная настройка Xorg. Используя [.filename]#/var/log/Xorg.0.log#, можно извлечь достаточно информации для создания рабочей строки `ModeLine` вручную. Просто обратитесь к следующей информации:

[.programlisting]
....
(II) MGA(0): Supported additional Video Mode:
(II) MGA(0): clock: 146.2 MHz   Image Size:  433 x 271 mm
(II) MGA(0): h_active: 1680  h_sync: 1784  h_sync_end 1960 h_blank_end 2240 h_border: 0
(II) MGA(0): v_active: 1050  v_sync: 1053  v_sync_end 1059 v_blanking: 1089 v_border: 0
(II) MGA(0): Ranges: V min: 48  V max: 85 Hz, H min: 30  H max: 94 kHz, PixClock max 170 MHz
....

Эта информация называется EDID. Создание `ModeLine` из сводится к расположению номеров в правильном порядке:

[.programlisting]
....
ModeLine <name> <clock> <4 horiz. timings> <4 vert. timings>
....

Для нашего примера `ModeLine` в `Section "Monitor"` будет выглядеть так:

[.programlisting]
....
Section "Monitor"
Identifier      "Monitor1"
VendorName      "Bigname"
ModelName       "BestModel"
ModeLine        "1680x1050" 146.2 1680 1784 1960 2240 1050 1053 1059 1089
Option          "DPMS"
EndSection
....

После завершения редактирования конфигурации, X должен запуститься в новом широкоэкранном разрешении.

[[x-fonts]]
== Использование шрифтов в X11

[[type1]]
=== Шрифты Type1

Шрифты, используемые по умолчанию и распространяемые вместе с X11, вряд ли можно назвать идеально подходящими для применения в обычных издательских приложениях. Большие презентационные шрифты выглядят рвано и непрофессионально, а мелкие шрифты в man:getenv[3] вообще невозможно разобрать. Однако есть некоторое количество свободно распространяемых высококачественных шрифтов Type1 (PostScript(R)), которые можно без изменений использовать с X11. К примеру, в наборе шрифтов URW (package:x11-fonts/urwfonts[]) имеются высококачественные версии стандартных шрифтов type1 (Times Roman(TM), Helvetica(TM), Palatino(TM) и другие). В набор Freefonts (package:x11-fonts/freefonts[]) включено ещё больше шрифтов, однако большинство из них предназначено для использования в программном обеспечении для работы с графикой, например, Gimp, и они не вполне пригодны для использования в качестве экранных шрифтов. Кроме того, X11 с минимальными усилиями может быть настроена на использование шрифтов TrueType(R). Более детальная информация находится на странице справочной системы man:X[7] и в <<truetype,разделе о шрифтах TrueType(R)>> ниже.

Для установки вышеупомянутых коллекций шрифтов Type1 из коллекции портов выполните следующие команды:

[source,shell]
....
# cd /usr/ports/x11-fonts/urwfonts
# make install clean
....

То же самое нужно будет сделать для коллекции freefont и других. Чтобы X-сервер обнаруживал этих шрифты, добавьте соответствующую строку в файл настройки X сервера ([.filename]#/etc/X11/xorg.conf#), которая должна выглядеть так:

[.programlisting]
....
FontPath "/usr/local/lib/X11/fonts/URW/"
....

Либо из командной строки при работе с X выполните:

[source,shell]
....
% xset fp+ /usr/local/lib/X11/fonts/URW
% xset fp rehash
....

Это сработает, но будет потеряно, когда сеанс работы с X будет закрыт, если эта команда не будет добавлена в начальный файл ([.filename]#~/.xinitrc# в случае обычного сеанса через `startx` или [.filename]#~/.xsession# при входе через графический менеджер типа XDM). Третий способ заключается в использовании нового файла [.filename]#/usr/local/etc/fonts/local.conf#: посмотрите раздел об <<antialias,антиалиасинге>>.

[[truetype]]
=== Шрифты TrueType(R)

В Xorg имеется встроенная поддержка шрифтов TrueType(R). Имеются два модуля, которые могут обеспечить эту функциональность. В нашем примере используется модуль freetype, потому что он в большей степени похож на другие механизмы для работы с шрифтами. Для включения модуля freetype достаточно в раздел `"Module"` файла [.filename]#/etc/X11/xorg.conf# добавить следующую строчку.

[.programlisting]
....
Load  "freetype"
....

Теперь создайте каталог для шрифтов TrueType(R) (к примеру, [.filename]#/usr/local/lib/X11/fonts/TrueType#) и скопируйте все шрифты TrueType(R) в этот каталог. Имейте в виду, что напрямую использовать шрифты TrueType(R) с Macintosh(R) нельзя; для использования с X11 они должны быть в формате UNIX(R)/MS-DOS(R)/Windows(R). После того, как файлы будут скопированы в этот каталог, воспользуйтесь утилитой ttmkfdir для создания файла [.filename]#fonts.dir#, который укажет подсистеме вывода шрифтов X на местоположение этих новых файлов. `ttmkfdir` имеется в Коллекции Портов FreeBSD: package:x11-fonts/ttmkfdir[].

[source,shell]
....
# cd /usr/local/lib/X11/fonts/TrueType
# ttmkfdir -o fonts.dir
....

После этого добавьте каталог со шрифтами TrueType(R) к маршруту поиска шрифтов. Это делается точно также, как описано выше для шрифтов <<type1,Type1>>, то есть выполните

[source,shell]
....
% xset fp+ /usr/local/lib/X11/fonts/TrueType
% xset fp rehash
....

или добавьте строку `FontPath` в файл [.filename]#xorg.conf#.

Это всё. Теперь man:getenv[3], Gimp, StarOffice(TM) и все остальные X-приложения должны увидеть установленные шрифты TrueType(R). Очень маленькие (как текст веб-страницы на дисплее с высоким разрешением) и очень большие (в StarOffice(TM)) шрифты будут теперь выглядеть гораздо лучше.

[[antialias]]
=== Антиалиасинг шрифтов

Антиалиасинг присутствует в X11 начиная с XFree86(TM), версии 4.0.2. Однако настройка шрифтов была довольно громоздка вплоть до появления XFree86(TM) 4.3.0. Начиная с версии XFree86(TM) 4.3.0, все шрифты, расположенные в каталогах [.filename]#/usr/local/lib/X11/fonts/# и [.filename]#~/.fonts/#, автоматически становятся доступными для применения антиалиасинга в приложениях, использующих Xft. Не все приложения могут использовать Xft, но во многих его поддержка присутствует. Примерами приложений, использующих Xft, является Qt версий 2.3 и более поздних (это инструментальный пакет для оболочки KDE), GTK+ версий 2.0 и более поздних (это инструментальный пакет для оболочки GNOME), а также Mozilla версий 1.2 и более поздних.

Для применения к шрифтам антиалиасинга, а также для настройки параметров антиалиасинга, создайте (или отредактируйте, если он уже существует) файл [.filename]#/usr/local/etc/fonts/local.conf#. Некоторые мощные возможности системы шрифтов Xft могут быть настроены при помощи этого файла; в этом разделе описаны лишь некоторые простые возможности. Для выяснения всех деталей, пожалуйста, обратитесь к man:fonts-conf[5].

Этот файл должен быть сформирован в формате XML. Обратите особое внимание на регистр символов, и удостоверьтесь, что все тэги корректно закрыты. Файл начинается обычным заголовком XML, за которым следуют DOCTYPE и тэг `<fontconfig>`:

[.programlisting]
....

        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
        <fontconfig>
....

Как и говорилось ранее, все шрифты из каталога [.filename]#/usr/local/lib/X11/fonts/#, а также [.filename]#~/.fonts/# уже доступны для приложений, использующих Xft. Если вы хотите добавить каталог, отличный от этих двух, добавьте строчку, подобную следующей, в файл [.filename]#/usr/local/etc/fonts/local.conf#:

[.programlisting]
....
<dir>/path/to/my/fonts</dir>
....

После добавления новых шрифтов, и особенно новых каталогов со шрифтами, вы должны выполнить следующую команду для перестроения кэшей шрифтов:

[source,shell]
....
# fc-cache -f
....

Антиалиасинг делает границы несколько размытыми, что делает очень мелкий текст более читабельным и удаляет "лесенки" из текста большого размера, но может вызвать нечёткость при применении к тексту обычного размера. Для исключения размеров шрифтов, меньших 14, из антиалиасинга, добавьте такие строки:

[.programlisting]
....
        <match target="font">
            <test name="size" compare="less">
                <double>14</double>
            </test>
            <edit name="antialias" mode="assign">
                <bool>false</bool>
            </edit>
        </match>
        <match target="font">
            <test name="pixelsize" compare="less" qual="any">
                <double>14</double>
            </test>
            <edit mode="assign" name="antialias">
                <bool>false</bool>
            </edit>
        </match>
....

Для некоторых моноширинных шрифтов антиалиасинг может также оказаться неприменимым при определении межсимвольного интервала. В частности, эта проблема возникает с KDE. Одним из возможных решений для этого является жесткое задание межсимвольного интервала в 100. Добавьте следующие строки:

[.programlisting]
....
       <match target="pattern" name="family">
           <test qual="any" name="family">
               <string>fixed</string>
           </test>
           <edit name="family" mode="assign">
               <string>mono</string>
           </edit>
        </match>
        <match target="pattern" name="family">
            <test qual="any" name="family">
                <string>console</string>
            </test>
            <edit name="family" mode="assign">
                <string>mono</string>
            </edit>
        </match>
....

(это создаст алиасы `"mono"` для других общеупотребительных имён шрифтов фиксированного размера), а затем добавьте:

[.programlisting]
....
         <match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>mono</string>
             </test>
             <edit name="spacing" mode="assign">
                 <int>100</int>
             </edit>
         </match>
....

С некоторыми шрифтами, такими, как Helvetica, при антиалиасинге могут возникнуть проблемы . Обычно это проявляется в виде шрифта, который наполовину вертикально обрезан. Хуже того, это может привести к сбоям таких приложений, как Mozilla. Во избежание этого следует добавить следующее в файл [.filename]#local.conf#:

[.programlisting]
....
         <match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>Helvetica</string>
             </test>
             <edit name="family" mode="assign">
                 <string>sans-serif</string>
             </edit>
         </match>
....

После того, как вы закончите редактирование [.filename]#local.conf#, удостоверьтесь, что файл завершен тэгом `</fontconfig>`. Если этого не сделать, ваши изменения будут проигнорированы.

Набор шрифтов по умолчанию, поставляемый с X11, не очень подходит, если включается антиалиасинг. Гораздо лучший набор шрифтов, используемых по умолчанию, можно найти в порте package:x11-fonts/bitstream-vera[]. Этот порт установит файл [.filename]#/usr/local/etc/fonts/local.conf#, если такого ещё не существует. Если файл существует, то порт создаст файл [.filename]#/usr/local/etc/fonts/local.conf-vera#. Перенесите содержимое этого файла в [.filename]#/usr/local/etc/fonts/local.conf#, и шрифты Bitstream автоматически заменят используемые по умолчанию в X11 шрифты Serif, Sans Serif и Monospaced.

Наконец, пользователи могут добавлять собственные наборы посредством персональных файлов [.filename]#.fonts.conf#. Для этого каждый пользователь должен просто создать файл [.filename]#~/.fonts.conf#. Этот файл также должен быть в формате XML.

И последнее замечание: при использовании дисплея LCD может понадобиться включение разбиения точек. При этом компоненты красного, зелёного и голубого цветов (разделяемые по горизонтали), рассматриваются как отдельные точки для улучшения разрешения экрана по горизонтали; результат может оказаться потрясающим. Для включения этого механизма добавьте такую строчку где-нибудь в файле [.filename]#local.conf#:

[.programlisting]
....

        <match target="font">
            <test qual="all" name="rgba">
                <const>unknown</const>
            </test>
            <edit name="rgba" mode="assign">
                <const>rgb</const>
            </edit>
        </match>
....

[NOTE]
====
В зависимости от типа дисплея, `rgb` может потребоваться заменить на `bgr`, `vrgb` или `vbgr`: пробуйте и смотрите, что работает лучше.
====

Антиалиасинг должен быть включен при следующем запуске X-сервера. Однако программы должны знать, как использовать его преимущества. В настоящее время инструментальный пакет Qt умеет ими пользоваться, так что вся оболочка KDE может использовать шрифты с антиалиасингом. GTK+ и GNOME также можно заставить использовать антиалиасинг посредством капплета "Font" (обратитесь к <<x11-wm-gnome-antialias>> для выяснения всех подробностей). По умолчанию Mozilla версий 1.2 и выше будет автоматически использовать антиалиасинг. Для отмены использования антиалиасинга перестройте Mozilla с флагом `-DWITHOUT_XFT`.

[[x-xdm]]
== Менеджеры экранов (Display Managers) X

=== Вступление

Менеджер Экранов X (XDM) это необязательный компонент X Window System, который используется для управления входом пользователей в систему. Это полезно в ряде ситуаций, например для минимальных "X Терминалов", десктопов, больших сетевых серверов экранов. Так как X Window System не зависит от сетей и протоколов, то существует множество различных конфигураций для X клиентов и серверов, запущенных на различных компьютерах, подключенных к сети. XDM предоставляет графический интерфейс для выбора сервера, к которому вы желаете подключится, и введения информации, авторизующей пользователя, например комбинации логина и пароля.

XDM можно рассматривать как аналог программы man:getty[8], предоставляющий такие же возможности для пользователей (смотрите crossref:serialcomms[term-config,Настройка] для подробной информации). И это именно так, XDM производит вход в систему для подключенного пользователя и запускает управляющую сессию для пользователя (обычно это менеджер окон X). После этого XDM ожидает завершения приложения, означающее завершение пользователем работы и отключает управляющую сессию. Затем XDM может снова вывести приглашение к входу в систему и ожидать входа другого пользователя. 

=== Использование XDM

Программой даемона XDM является [.filename]#/usr/local/bin/xdm#. Эта программа может быть запущена от пользователя `root` в любой момент, и она начнёт управлять дисплеем X на локальной машине. Если XDM нужно запускать в фоновом режиме каждый раз при запуске компьютера, то наиболее правильный способ - это добавить новую запись в [.filename]#/etc/ttys#. Для более подробной информации о формате и использовании этого файла смотрите crossref:serialcomms[term-etcttys,Добавление строки в /etc/ttys]. Вот строка, которую необходимо добавить в файл [.filename]#/etc/ttys# для того, чтобы запустить даемон XDM на виртуальном терминале:

[source,shell]
....
ttyv8	"/usr/local/bin/xdm -nodaemon"	xterm	off secure
....

По умолчанию эта запись отключена; для её включения нужно заменить пятое поле с `off` на `on` и перезапустить man:init[8], используя метод, описанный в crossref:serialcomms[term-hup,Добавление строки в /etc/ttys]. Первое поле это название терминала, которым будет управлять программа, `ttyv8`. Это означает, что XDM будет запущен на 9ом виртуальном терминале.

=== Конфигурирование XDM

Конфигурационные файлы XDM находятся в каталоге [.filename]#/usr/local/lib/X11/xdm#.
В нём размещаются несколько файлов, которые используются для изменения поведения и внешнего вида XDM. Обычно это следующие файлы:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Файл
| Описание

|[.filename]#Xaccess#
|Правила авторизации клиентов.

|[.filename]#Xresources#
|Значения ресурсов X по умолчанию.

|[.filename]#Xservers#
|Список локальных и удаленных экранов.

|[.filename]#Xsession#
|Сценарий сессии по умолчанию.

|[.filename]#Xsetup_#*
|Скрипт для запуска приложений до появления приглашения к входу в систему.

|[.filename]#xdm-config#
|Глобальный конфигурационный файл для всех экранов запущенных на локальной машине

|[.filename]#xdm-errors#
|Ошибки сгенерированные серверной программой.

|[.filename]#xdm-pid#
|ID процесса запущенного XDM.
|===

В этом каталоге также находятся несколько командных сценариев и программ, используемых для настройки рабочего стола (desktop) при запуске XDM. Назначение каждого из этих файлов будет вкратце описано. Точный синтаксис и информация по их использованию находятся в man:xdm[1].

В конфигурации по умолчанию выводится простое прямоугольное окно приглашения ко входу в систему с именем компьютера, написанным сверху большим шрифтом, и строками ввода "Login:" и "Password:" внизу. Это хорошая отправная точка для изменения внешнего вида экранов XDM.

==== Xaccess

Протокол, по которому происходит подключение дисплеев, управляемых XDM, называется X Display Manager Connection Protocol (XDMCP). Этот файл представляет собой набор правил для управления XDMCP соединениями с удалёнными машинами. Он игнорируется, пока стандартный файл [.filename]#xdm-config# не содержит указаний по обслуживанию удалённых соединений.

==== Xresources

Это файл содержит установки по умолчанию для приложений, запущенных в экране выбора серверов и экране приглашения к входу в систему. В нем может быть изменён вид программы входа в систему. Формат этого файла идентичен файлу app-defaults, описанному в документации к X11.

==== Xservers

Это список удаленных экранов, которые XDM должен предоставить как варианты для входа в систему.

==== Xsession

Этот файл представляет из себя командный сценарий по умолчанию для пользователей, вошедших в систему с использованием XDM. Обычно каждый пользователь имеет собственный сценарий входа в файле [.filename]#~/.xsession#, который используется вместо этого сценария.

==== Xsetup_*

Они запускаются автоматически перед тем, как показывается экран выбора сервера или экран входа в систему. Для каждого экрана (display) есть свой сценарий с именем [.filename]#Xsetup_#, за которым следует локальный номер экрана (например, [.filename]#Xsetup_0#). Обычно эти сценарии запускают одну или две программы в фоновом режиме, например `xconsole`.

==== xdm-config

Здесь содержатся настройки в формате app-defaults, которые применимы ко всем экранам данного компьютера.

==== xdm-errors

Здесь находится выдача X серверов, которые XDM пытается запустить. Если экран, который XDM пытается открыть, отключается по некоторым причинам, то это хорошее место для поиска сообщений об ошибках. Эти сообщения также записываются в пользовательский файл [.filename]#~/.xsession-errors# для каждого сеанса.

=== Использование сетевого сервера дисплеев

Для того, чтобы позволить другим клиентам подключаться к серверу дисплеев, необходимо отредактировать правила контроля доступа и включить обслуживание сетевых соединений. По умолчанию они выключены, что является хорошим решением с точки зрения обеспечения безопасности. Для того, чтобы позволить XDM принимать сетевые соединения, в первую очередь закомментируйте строку в файле [.filename]#xdm-config#:

[source,shell]
....
! БЕЗОПАСНОСТЬ: do not listen for XDMCP or Chooser requests
! Закомментируйте эти линии, если вы хотите управлять X терминалами с xdm
DisplayManager.requestPort:     0
....

и потом перезапустите XDM. Помните, что комментарии в файлах app-defaults начинаются с символа "!", а не как обычно, "\#". Может потребоваться более жёсткий контроль доступа - взгляните на примеры из [.filename]##Xaccess## и обратитесь к странице справочника man:xdm[1] за дальнейшей информацией.

=== Замены для XDM

Существует несколько программ, заменяющих XDM. Одна из них, kdm (поставляемая вместе с KDE), описана далее в этой главе. В kdm имеется много визуальных и косметических улучшений, а также функциональность, позволяющая пользователям выбирать собственные оконные менеджеры во время входа в систему.

[[x11-wm]]
== Графические оболочки

В этом разделе описываются различные графические оболочки, доступные в X для FreeBSD. Термин "графическая оболочка" может использоваться для чего угодно, от простого менеджера окон до полнофункционального набора приложений для рабочего стола, типа KDE или GNOME.

[[x11-wm-gnome]]
=== GNOME

[[x11-wm-gnome-about]]
==== О GNOME

GNOME является дружественной к пользователю графической оболочкой, позволяющей пользователям легко использовать и настраивать свои компьютеры. В GNOME имеется панель (для запуска приложений и отображения их состояния), рабочий стол (где могут быть размещены данные и приложения), набор стандартных инструментов и приложений для рабочего стола, а также набор соглашений, облегчающих совместную работу и согласованность приложений. Пользователи других операционных систем или оболочек при использовании такой мощной графической оболочки, какую обеспечивает GNOME, должны чувствовать себя в родной среде. Дополнительную информацию относительно GNOME во FreeBSD можно найти на сайте http://www.FreeBSD.org/gnome[FreeBSD GNOME Project]. Web сайт также содержит достаточно исчерпывающие FAQ'и, касающиеся установки, конфигурирования и управления GNOME.

[[x11-wm-gnome-install]]
==== Установка GNOME

Программу проще всего установить из пакета или коллекции портов:

Для установки пакета GNOME из сети, просто наберите:

[source,shell]
....
# pkg_add -r gnome2
....

Для построения GNOME из исходных текстов используйте дерево портов:

[source,shell]
....
# cd /usr/ports/x11/gnome2
# make install clean
....

После установки GNOME нужно указать X-серверу на запуск GNOME вместо стандартного оконного менеджера.

Самый простой путь запустить GNOME - это использовать GDM (GNOME Display Manager).
GDM, который устанавливается как часть GNOME (но отключён по умолчанию), может быть включён путём добавления параметра `gdm_enable="YES"` в [.filename]#/etc/rc.conf#.
После перезагрузки GDM запустится автоматически.

Кроме того, для активации всех сервисов GNOME при запуске GDM добавьте параметр `gnome_enable="YES"` в файл [.filename]#/etc/rc.conf#.

GNOME может быть также запущен из командной строки с помощью конфигурирования файла [.filename]#.xinitrc#. Если файл [.filename]#.xinitrc# уже откорректирован, то просто замените строку, в которой запускается используемый менеджер окон, на ту, что вызовет /usr/local/bin/gnome-session. Если в конфигурационном файле нет ничего особенного, то будет достаточно просто набрать:

[source,shell]
....
% echo "/usr/local/bin/gnome-session" > ~/.xinitrc
....

Теперь наберите `startx`, и будет запущена графическая оболочка GNOME.

[NOTE]
====
Если используется более старый менеджер дисплеев типа XDM, то это не сработает. Вместо этого создайте выполнимый файл [.filename]#.xsession# с той же самой командой в нём. Для этого отредактируйте файл, заменив существующую команду запуска оконного менеджера на /usr/local/bin/gnome-session:
====

[source,shell]
....
% echo "#!/bin/sh" > ~/.xsession
% echo "/usr/local/bin/gnome-session" >> ~/.xsession
% chmod +x ~/.xsession
....

Ещё одним вариантом является настройка менеджера дисплеев таким образом, чтобы он позволял выбирать оконный менеджер во время входа в систему; в разделе о <<x11-wm-kde-details,KDE в подробностях>> описывается, как сделать это для kdm, менеджера дисплеев из KDE.

[[x11-wm-gnome-antialias]]
==== Шрифты с антиалиасингом и GNOME

X11 поддерживает антиалиасинг посредством своего расширения "RENDER". GTK+ 2.0 и более поздние версии (это инструментальный пакет, используемый GNOME) могут использовать такую функциональность. Настройка антиалиасинга описана в <<antialias>>. Таким образом, при наличии современного GNOME, возможно использование антиалиасинга. Просто перейдите в menu:Applications[Desktop Preferences > Font] и выберите либо btn:[Best shapes], btn:[Best contrast], либо btn:[Subpixel smoothing (LCDs)]. Для приложений GTK+, которые не являются частью оболочки GNOME, задайте в качестве значения переменной окружения `GDK_USE_XFT``1` перед запуском программы.

[[x11-wm-kde]]
=== KDE

[[x11-wm-kde-about]]
==== О KDE

KDE является простой в использовании современной графической оболочкой. Вот лишь некоторые из преимуществ, которые даёт пользователю KDE:

* Прекрасный современный рабочий стол
* Рабочий стол, полностью прозрачный для работы в сети
* Интегрированная система помощи, обеспечивающая удобный и согласованный доступ к системе помощи по использованию рабочего стола KDE и его приложений
* Единообразный внешний вид и управление во всех приложениях KDE
* Стандартизированные меню и панели инструментов, комбинации клавиш, цветовые схемы и так далее.
* Интернационализация: в KDE поддерживается более 40 языков
* Централизованное единообразное конфигурирование рабочего стола в диалоговом режиме
* Большое количество полезных приложений для KDE

Совместно с KDE поставляется веб-браузер под названием Konqueror, который является серьезным соперником другим браузерам для UNIX(R)-систем. Дополнительную информацию о KDE можно найти на веб-сайте http://www.kde.org/[KDE в FreeBSD]. Для получения информации и информационных ресурсов, специфичных для KDE во FreeBSD, обратитесь к сайту команды http://freebsd.kde.org/[FreeBSD-KDE team].

Имеется две версии KDE доступные на FreeBSD. Версия 3 была доступна очень долгое время и она является очень зрелой. Версия 4 - это следующее поколение, также доступное через Коллекцию Портов. Обе версии могут быть инсталлированы одновременно.

[[x11-wm-kde-install]]
==== Установка KDE

Как и в случае с GNOME или любой другой графической оболочкой, программное обеспечение можно легко установить из пакета или из Коллекции Портов:

Для установки пакета KDE3 из сети, просто наберите:

[source,shell]
....
# pkg_add -r kde
....

Для установки пакета KDE4 из сети, просто наберите:

[source,shell]
....
# pkg_add -r kde4
....

man:pkg_add[1] автоматически загрузит самую последнюю версию приложения.

Для построения KDE3 из исходных текстов, воспользуйтесь деревом портов:

[source,shell]
....
# cd /usr/ports/x11/kde3
# make install clean
....

Для построения KDE4 из исходных текстов, воспользуйтесь деревом портов:

[source,shell]
....
# cd /usr/ports/x11/kde4
# make install clean
....

После установки KDE нужно указать X-серверу на запуск этого приложения вместо оконного менеджера, используемого по умолчанию. Это достигается редактированием файла [.filename]#.xinitrc#:

Для KDE3:

[source,shell]
....
% echo "exec startkde" > ~/.xinitrc
....

Для KDE4:

[source,shell]
....
% echo "exec /usr/local/kde4/bin/startkde" > ~/.xinitrc
....

Теперь при вызове X Window System по команде `startx` в качестве оболочки будет использоваться KDE.

При использовании менеджера дисплеев типа XDM настройка несколько отличается. Вместо этого нужно отредактировать файл [.filename]#.xsession#. Указания для kdm описаны далее в этой главе.

[[x11-wm-kde-details]]
=== Более подробно о KDE

Теперь, когда KDE установлена в системе, можно узнать много нового из её справочных страниц или просто указанием и щелканьем по различным меню. Пользователи Windows(R) или Mac(R) будут чувствовать себя как дома.

Лучшим справочником по KDE является онлайновая документация. KDE поставляется с собственным веб-браузером, который называется Konqueror, десятками полезных приложений и подробной документацией. В оставшейся части этого раздела обсуждаются технические вопросы, трудные для понимания при случайном исследовании.

[[x11-wm-kde-kdm]]
==== Менеджер дисплеев KDE

Администратору многопользовательской системы может потребоваться графический экран для входа пользователей в систему. Вы можете использовать <<x-xdm,XDM>>, как это описано ранее. Однако в KDE имеется альтернативный менеджер kdm, который был разработан более привлекательным и с большим количеством настраиваемых опций для входа в систему. В частности, пользователи могут легко выбирать (посредством меню), какую оболочку (KDE, GNOME или что-то ещё) запускать после входа в систему.

Для того, чтобы разрешить запуск kdm, измените в файле [.filename]#/etc/ttys# строку, относящуюся к консоли `ttyv8`:

Для KDE3:

[.programlisting]
....
ttyv8 "/usr/local/bin/kdm -nodaemon" xterm on secure
....

Для KDE4:

[.programlisting]
....
ttyv8 "/usr/local/kde4/bin/kdm -nodaemon" xterm on secure
....

[[x11-wm-xfce]]
=== XFce

[[x11-wm-xfce-about]]
==== О XFce

XFce является графической оболочкой, построенной на основе инструментального пакета GTK+, используемого в GNOME, но она гораздо легче и предназначена для тех, кому нужен простой, эффективно работающий рабочий стол, который легко использовать и настраивать. Визуально он выглядит очень похоже на CDE, который есть в коммерческих UNIX(R)-системах. Вот некоторые из достоинств XFce:

* Простой, лёгкий в обращении рабочий стол
* Полностью настраиваемый при помощи мыши, с интерфейсом drag and drop и так далее
* Главная панель похожа на CDE, с меню, апплетами и возможностями по быстрому запуску приложений
* Интегрированный оконный менеджер, менеджер файлов, управление звуком, модуль совместимости с GNOME и прочее
* Возможность использования тем (так как использует GTK+)
* Быстрый, легкий и эффективный: идеален для устаревших/слабых машин или для машин с ограниченной памятью

Дополнительную информацию о XFce можно найти на http://www.xfce.org/[сайте XFce].

[[x11-wm-xfce-install]]
==== Установка XFce

Для XFce имеется (на момент написания этого текста) бинарный пакет. Для его установки просто наберите:

[source,shell]
....
# pkg_add -r xfce4
....

Либо, в случае построения из исходных текстов, используйте Коллекцию Портов: 

[source,shell]
....
# cd /usr/ports/x11-wm/xfce4
# make install clean
....

Теперь укажите X-серверу на запуск XFce при следующем запуске X. Просто наберите:

[source,shell]
....
% echo "/usr/local/bin/startxfce4" > ~/.xinitrc
....

При следующем запуске X в качестве рабочего стола будет использоваться XFce. Как сказано выше, если используется менеджер дисплеев, такой, как [.filename]#XDM#, создайте файл [.filename]#.xsession# так, как это описано в разделе о <<x11-wm-gnome,GNOME>>, но с командой [.filename]#/usr/local/bin/startxfce4#, либо настройте менеджер дисплеев так, чтобы он разрешил выбор рабочего стола во время входа в систему, как это описано в разделе о <<x11-wm-kde-kdm,kdm>>.
