//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (05.03.2023): 8cd114521263d52494afebc6d74472f9f38a99ab
//

---
title: Глава 6. X Window System
part: Часть I. В начале
prev: books/handbook/ports
next: books/handbook/wayland
description: Эта глава описывает установку и настройку во FreeBSD системы с открытым кодом Xorg, являющейся реализацией X Window System и обеспечивающей графический интерфейс
tags: ["X11", "Xorg", "TrueType", "Intel", "AMD", "NVIDIA", "Anti-Aliased", "VESA", "SCFB"]
showBookMenu: true
weight: 7
path: "/books/handbook/"
---

[[x11]]
= X Window System
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 5
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/x11/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[x11-synopsis]]
== Обзор

Процедура установки FreeBSD при помощи bsdinstall не предусматривает автоматической установки графического пользовательского интерфейса.
Эта глава описывает процесс установки и настройки пакета Xorg, предоставляющий X Window System с открытым кодом, обеспечивающий графическую среду работы.
Затем она объясняет, как найти и установить оболочку рабочего стола или оконный менеджер.

Перед тем, как прочесть эту главу, вы должны:
* Знать, как устанавливать дополнительное программное обеспечение сторонних разработчиков, как это описано в разделе crossref:ports[ports,Установка Приложений: Пакеты и Порты].

После чтения этой главы вы будете знать:

* Различные компоненты X Window System и их взаимодействие.
* Как установить и настроить Xorg.
* Как установить и настроить несколько оконных менеджеров и оболочек рабочего стола.
* Как использовать шрифты TrueType(R) в Xorg.
* Как настроить вашу систему на графический интерфейс входа (XDM).

[[x-install]]
== Установка Xorg

Во FreeBSD Xorg может быть установлен как пакет или как порт.

Бинарный мета-пакет может быть установлен быстрее, но он даёт меньше опций для настройки:

[source,shell]
....
# pkg install xorg
....

Любой из этих методов приводит к установке полной системы Xorg.

Текущий пользователь должен быть членом группы `video`.
Для добавления пользователя в группу `video` выполните следующую команду:

[source,shell]
....
# pw groupmod video -m username
....

[TIP]
====
Более компактная версия X, подходящая для опытных пользователей, доступна в пакете package:x11/xorg-minimal.
При его выборе подавляющее большинство документов, библиотек и приложений не будут устанавливаться.
Некоторым приложениям для работы требуются эти дополнительные компоненты.
====

[TIP]
====
Графические адаптеры, мониторы и устройства ввода распознаются автоматически и не требуют каких-либо ручных настроек.
Не создавайте `xorg.conf` и не выполняйте шаг `-configure`, если автоматическая настройка происходит нормально.
====

[[x-graphic-card-drivers]]
== Драйверы графических адаптеров

В таблице ниже перечисляются различные графические адаптеры, поддерживаемые FreeBSD, а также пакеты, которые должны быть установлены и соответствующие модули.

.Пакеты для графических адаптеров
[options="header", cols="1,1,1,1"]
|===
| Производитель | Тип | Пакет | Модуль

| Intel(R)
| Открытый код
| drm-kmod
| `i915kms`

| AMD(R)
| Открытый код
| drm-kmod
| `amdgpu` и `radeonkms`

| NVIDIA(R)
| Закрытый код
| nvidia-driver
| `nvidia` или `nvidia-modeset`

| VESA
| Открытый код
| xf86-video-vesa
| vesa

| SCFB
| Открытый код
| xf86-video-scfb
| scfb

| Virtualbox
| Открытый код
| virtualbox-ose-additions
| Дополнения Virtualbox OSE включают драйвер `vboxvideo`.

| VMware(R)
| Открытый код
| xf86-video-vmware
| vmwgfx

|===

Для идентификации графического адаптера, установленного в системе, можно воспользоваться следующей командой:

[source,shell]
....
% pciconf -lv|grep -B4 VGA
....

Выдаваемый результат должен быть подобен следующему:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
    subclass   = VGA
....

[WARNING]
====
Если графический адаптер не поддерживается драйверами Intel(R), AMD(R) или NVIDIA(R), то должны использоваться модули VESA или SCFB.
Модуль VESA должен использоваться при загрузке в режиме BIOS, а модуль SCFB должен быть использован при загрузке в режиме UEFI.

Для уточнения режима загрузки можно использовать эту команду:

[source,shell]
....
% sysctl machdep.bootmethod
....

Результат должен быть подобен следующему:

[.programlisting]
....
machdep.bootmethod: BIOS
....
====

[[x-configuration-intel]]
=== Intel(R)

Intel(R) Graphics означает класс графических микросхем, интегрированных в тот же кристалл, что и Intel(R) CPU.
Wikipedia содержит link:https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units[хороший обзор разновидностей и обозначений, используемых для поколений Intel HD Graphics].

Пакет package:graphics/drm-kmod[] неявным образом предоставляет линейку модулей ядра для использования с адаптерами Intel(R) Graphics.
Драйвер Intel(R) может быть установлен при помощи следующей команды:

[source,shell]
....
# pkg install drm-kmod
....

Затем добавьте этот модуль в файл `/etc/rc.conf`, выполнив следующую команду:

[source,shell]
....
# sysrc kld_list+=i915kms
....

[TIP]
====
Если наблюдается высокая нагрузка на CPU или чрезмерное количество артефактов в видео HD, то может помочь установка пакета package:multimedia/libva-intel-driver[].

Для установки пакета выполните следующую команду:

[source,shell]
....
# pkg install libva-intel-driver mesa-libs mesa-dri
....
====

[[x-configuration-amd]]
=== AMD(R)

Пакет package:graphics/drm-kmod[] неявным образом предоставляет набор модулей ядра для использования с графическими адаптерами AMD(R) Graphics.
В зависимости от поколения оборудования могут быть использованы модули `amdgpu` и `radeonkms`.
Проект FreeBSD поддерживает в актуальном состоянии link:https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[матрицу поддержки графики AMD, указывающую на необходимый к использованию драйвер].

Драйвер AMD(R) можно установить, выполнив следующую команду:

[source,shell]
----
# pkg install drm-kmod
----

Для графических адаптеров, выпущенных позже HD7000 или Tahiti, добавьте этот модуль в файл `/etc/rc.conf` при помощи следующей команды:

[source,shell]
----
# sysrc kld_list+=amdgpu
----

Для более старых графических адаптеров (до HD7000 или до Tahiti) добавьте этот модуль в файл `/etc/rc.conf` при помощи запуска следующей команды:

[source,shell]
----
# sysrc kld_list+=radeonkms
----

[[x-configuration-nvidia]]
=== NVIDIA(R)

FreeBSD поддерживает различные версии проприетарного драйвера NVIDIA(R).
Пользователи более новых графических адаптеров должны установить пакет package:x11/nvidia-driver[].
Тем, кто использует более старые адаптеры, необходимо будет уточнить по списку ниже, какие версии их поддерживают.

.Поддерживаемые версии драйверов NVIDIA(R)
[options="header", cols="1,1"]
|===
| Пакет | Поддерживаемое оборудование

| x11/nvidia-driver-304
| link:https://www.nvidia.com/Download/driverResults.aspx/123712/en-us/[поддерживаемое оборудование]

| x11/nvidia-driver-340
| link:https://www.nvidia.com/Download/driverResults.aspx/156167/en-us/[поддерживаемое оборудование]

| x11/nvidia-driver-390
| link:https://www.nvidia.com/Download/driverResults.aspx/191122/en-us/[поддерживаемое оборудование]

| x11/nvidia-driver-470
| link:https://www.nvidia.com/Download/driverResults.aspx/191234/en-us/[поддерживаемое оборудование]

| x11/nvidia-driver
| link:https://www.nvidia.com/Download/driverResults.aspx/187164/en-us/[поддерживаемое оборудование]

|===

[WARNING]
====
Версия 304 драйверов графики NVIDIA(R) (nvidia-driver-304) не поддерживает xorg-server версии 1.20 и выше.
====

Самый последний драйвер NVIDIA(R) можно установить, выполнив следующую команду:

[source,shell]
----
# pkg install nvidia-driver
----

Затем добавьте этот модуль в файл `/etc/rc.conf`, выполнив следующую команду:

[source,shell]
....
# sysrc kld_list+=nvidia-modeset
....

[WARNING]
====
Драйвер `nvidia` должен использоваться в случае, если установлен пакет x11/nvidia-driver-304 или x11/nvidia-driver-340.

[source,shell]
....
# sysrc kld_list+=nvidia
....
====

[[x-config]]
== Настройка Xorg

Xorg поддерживает большинство распространённых графических адаптеров, клавиатур и устройств позиционирования.

[WARNING]
====
Графические адаптеры, мониторы и устройства ввода распознаются автоматически и не требуют никакого ручного вмешательства.
Не создавайте файл [.filename]#xorg.conf# и не запускайте шаг `Xorg -configure`, если автоматическая настройка завершилась успешно.
====

[[x-config-files]]
=== Конфигурационные Файлы

Xorg использует несколько каталогов для размещения конфигурационных файлов.
Для FreeBSD каталог [.filename]#/usr/local/etc/X11/# является *рекомендованным* для таких файлов.
Использование этого каталога помогает размещать файлы приложений отдельно от файлов операционной системы.

[[x-config-files-single-or-multi]]
=== Один Файл или Несколько

Использовать несколько файлов вместо традиционно единственного [.filename]#xorg.conf# легче, так как каждый из них содержит специфичные настройки.
Эти файлы размещаются в подкаталоге [.filename]#/usr/local/etc/X11/xorg.conf.d/#.

[TIP]
====
Использование традиционного единого файла [.filename]#xorg.conf# также поддерживается, но это не так гибко и не так прозрачно, как использование нескольких файлов в подкаталоге [.filename]#/usr/local/etc/X11/xorg.conf.d/#.
====

[[x-config-video-cards]]
=== Графические Адаптеры

Драйвер для графического адаптера может быть указан в каталоге [.filename]#/usr/local/etc/X11/xorg.conf.d/#.

Для настройки драйвера Intel(R) в конфигурационном файле:

[[x-config-video-cards-file-intel]]
.Выберите драйвер видео Intel(R) в файле

[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-intel.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "intel"
EndSection
....
====

Для настройки драйвера AMD(R) в конфигурационном файле:
[[x-config-video-cards-file-amd]]
.Выберите драйвер видео AMD(R) в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-radeon.conf#

[.programlisting]
....
Section "Device"
        Identifier "Card0"
	Driver     "radeon"
EndSection
....
====

Для настройки драйвера NVIDIA(R) в конфигурационном файле:

[[x-config-video-cards-file-nvidia]]
.Выберите драйвер видео NVIDIA(R) в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-nvidia.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "nvidia"
EndSection
....
====

Для настройки драйвера VESA в конфигурационном файле:

[[x-config-video-cards-file-vesa]]
.Выберите драйвер видео VESA в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-vesa.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "vesa"
EndSection
....
====

Для настройки драйвера SCFB в конфигурационном файле:

[[x-config-video-cards-file-sfcb]]
.Выберите драйвер видео SCFB в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-scfb.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "scfb"
EndSection
....
====

Для настройки нескольких видеоадаптеров может быть добавлена шина `BusID`.
Список ``ID`` шин графических адаптеров может быть выдан при помощи команды:

[source,shell]
....
% pciconf -lv | grep -B3 display
....

Результат должен выглядить подобно следующему:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
--
vgapci1@pci0:0:2:1:     class=0x038000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a43 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
....

[[x-config-video-cards-file-multiple]]
.Выберите драйвера видео Intel(R) и NVIDIA(R) в файле
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/20-drivers.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "intel"
       BusID     "pci0:0:2:0"
EndSection

Section "Device"
       Identifier "Card0"
       Driver     "nvidia"
       BusID     "pci0:0:2:1"
EndSection
....
====

[[x-config-monitors]]
=== Мониторы

Практически все мониторы поддерживают стандарт Extended Display Identification Data (EDID).
Xorg использует EDID для работы с монитором и выявления поддерживаемых разрешений и частот обновления.
Затем система выбирает комбинацию параметров, наиболее подходящую к использованию с данным монитором.

Другие разрешения, поддерживаемые данным монитором, могут быть установлены указанием требуемого разрешения в конфигурационных файлах либо после запуска X-сервера при помощи man:xrandr[1].

[[x-config-monitors-xrandr]]
==== Использование RandR (изменение размера и поворот)

Запустите man:xrandr[1] без каких-либо параметров, чтобы посмотреть список устройств и выявленные режимы работы мониторов:

[source,shell]
....
% xrandr
....

Выдаваемый результат должен быть похож на следующий:

[.programlisting]
....
Screen 0: minimum 320 x 200, current 2560 x 960, maximum 8192 x 8192
LVDS-1 connected 1280x800+0+0 (normal left inverted right x axis y axis) 261mm x 163mm
   1280x800      59.99*+  59.81    59.91    50.00
   1280x720      59.86    59.74
   1024x768      60.00
   1024x576      59.90    59.82
   960x540       59.63    59.82
   800x600       60.32    56.25
   864x486       59.92    59.57
   640x480       59.94
   720x405       59.51    58.99
   640x360       59.84    59.32
VGA-1 connected primary 1280x960+1280+0 (normal left inverted right x axis y axis) 410mm x 257mm
   1280x1024     75.02    60.02
   1440x900      74.98    60.07
   1280x960      60.00*
   1280x800      74.93    59.81
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   640x480       75.00    72.81    66.67    59.94
   720x400       70.08
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
....

Здесь показано, что выход `VGA-1` используется для выдачи изображения с разрешением 1280x960 точек с частотой обновления 60 Гц.
`LVDS-1` используется как второй монитор для выдачи изображения с разрешением 1280x800 пикселей с частотой обновления около 60 Гц.
К разъёмам `HDMI-1`, `HDMI-2`, `DP-1`, `DP-2` и `DP-3` мониторы не подключены.

При помощи man:xrandr[1] могут быть выбраны любые другие режимы работы дисплея.
К примеру, для переключения в режим 1280x1024 на частоте 60 Гц запустите следующую команду:

[source,shell]
....
$ xrandr --output LVDS-1 --mode 1280x720 --rate 60
....

[[x-config-monitors-files]]
==== Использование конфигурационного файла Xorg

Настройка монитора может быть также задана в конфигурационном файле.

Для того, чтобы задать разрешение 1024x768 в конфигурационном файле:

.Определение разрешения экрана в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/10-monitor.conf#

[.programlisting]
....
Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	SubSection "Display"
	Modes "1024x768"
	EndSubSection
EndSection
....
====

[[x-config-input]]
=== Устройства ввода

Xorg обеспечивает поддержку подавляющего большинства устройств ввода при помощи пакета package:x11/libinput[].

[TIP]
====
Некоторые графические оболочки (такие как KDE Plasma) предоставляют графический пользовательский интерфейс для настройки этих параметров.
Уточните это до того, как приступать к редактированию настроек в ручном режиме.
====

[[x-config-input-keyboard-layout]]
К примеру, для настройки раскладки клавиатуры:

.Настройка Раскладки Клавиатуры
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/00-keyboard.conf#

[.programlisting]
....
Section "InputClass"
        Identifier "Keyboard1"
        MatchIsKeyboard "on"
        Option "XkbLayout" "es, fr"
        Option "XkbModel" "pc104"
        Option "XkbVariant" ",qwerty"
        Option "XkbOptions" "grp:win_space_toggle"
EndSection
....
====

[[x-fonts]]
== Использование Шрифтов в Xorg

Шрифты, используемые по умолчанию и распространяемые вместе с Xorg, вряд ли можно назвать идеально подходящими для применения в обычных издательских приложениях.
Большие презентационные шрифты выглядят рвано и непрофессионально, а мелкие шрифты вообще невозможно разобрать.
Однако есть некоторое количество свободно распространяемых высококачественных шрифтов Type1 (PostScript(R)), которые можно без изменений использовать с Xorg.

[[type1]]
=== Шрифты Type1

В набор шрифтов URW (package:x11-fonts/urwfonts[]) включены высококачественные версии стандартных шрифтов type1 (Times Roman(TM), Helvetica(TM), Palatino(TM) и другие).
В набор Freefonts (package:x11-fonts/freefonts[]) включено ещё больше шрифтов, однако большинство из них предназначено для использования в программном обеспечении для работы с графикой, например, Gimp, и они не вполне пригодны для использования в качестве экранных шрифтов.
Кроме того, Xorg с минимальными усилиями может быть настроена на использование шрифтов TrueType(R).
Более подробную информацию можно найи на странице справочной системы man:X[7] или в <<truetype>>.

Для установки вышеупомянутых коллекций шрифтов Type1 из бинарных пакетов выполните следующие команды:

[source,shell]
....
# pkg install urwfonts
....

То же самое нужно будет сделать для коллекции freefont и других.
Чтобы X-сервер мог обнаружить эти шрифты, добавьте соответствующую строку в файл настройки X сервера ([.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf#), которая должна выглядеть так:

[.programlisting]
....
Section "Files"
  FontPath "/usr/local/share/fonts/urwfonts/"
EndSection
....

Либо из командной строки при работе с X выполните:

[source,shell]
....
% xset fp+ /usr/local/share/fonts/urwfonts
% xset fp rehash
....

Это сработает, но будет потеряно, когда сеанс работы с X будет закрыт, если эта команда не будет добавлена в начальный файл ([.filename]#~/.xinitrc# в случае обычного сеанса через `startx` или [.filename]#~/.xsession# при входе через графический менеджер типа XDM).
Третий способ заключается в использовании нового файла [.filename]#/usr/local/etc/fonts/local.conf#, как это показано в разделе <<antialias>>.

[[truetype]]
=== Шрифты TrueType(R)

В Xorg имеется встроенная поддержка шрифтов TrueType(R).
Имеются два различных модуля, которые могут обеспечить эту функциональность.
В нашем примере используется модуль freetype, потому что он в большей степени похож на другие механизмы для работы с шрифтами.
Для включения модуля freetype достаточно в раздел `"Module"` файла [.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf# добавить следующую строчку.

[.programlisting]
....
Load  "freetype"
....

Теперь создайте каталог для шрифтов TrueType(R) (к примеру, [.filename]#/usr/local/share/fonts/TrueType#) и скопируйте все шрифты TrueType(R) в этот каталог.
Имейте в виду, что напрямую перенести шрифты TrueType(R) с Apple(R) Mac(R) нельзя; для использования с Xorg они должны быть в формате UNIX(R)/MS-DOS(R)/Windows(R).
После того, как файлы будут скопированы в этот каталог, воспользуйтесь приложением mkfontscale для создания [.filename]#fonts.dir#, который подскажет подсистеме вывода шрифтов X, что эти новые файлы были установлены.
`mkfontscale` может быть установлено как пакет:

[source,shell]
....
# pkg install mkfontscale
....

После этого создайте индексный файл шрифтов X в каталоге:

[source,shell]
....
# cd /usr/local/share/fonts/TrueType
# mkfontscale
....

Теперь добавьте каталог со шрифтами TrueType(R) к маршруту поиска шрифтов.
Это делается точно так же, как описано в <<type1>>:

[source,shell]
----
% xset fp+ /usr/local/share/fonts/TrueType
% xset fp rehash
----

или добавьте строку `FontPath` в файл [.filename]#xorg.conf#.

Теперь Gimp, LibreOffice и все остальные приложения для X должны обнаружить установленные шрифты TrueType(R).
Очень маленькие (как текст веб-страницы на дисплее с высоким разрешением) и очень большие (в LibreOffice) шрифты теперь будут выглядеть гораздо лучше.

[[antialias]]
=== Шрифты с антиалиасингом

Все шрифты Xorg, расположенные в каталогах [.filename]#/usr/local/share/fonts/# и [.filename]#~/.fonts/#, автоматически становятся доступными для применения антиалиасинга в приложениях, использующих Xft.
Большинство современных приложений умеет работать с Xft, в том числе KDE, GNOME и Firefox.

Для управления применением антиалиасинга к шрифтам, а также для настройки параметров антиалиасинга, создайте (или отредактируйте, если он уже существует) файл [.filename]#/usr/local/etc/fonts/local.conf#.
Некоторые мощные возможности системы шрифтов Xft могут быть настроены при помощи этого файла; в этом разделе описаны лишь некоторые простые возможности.
Для выяснения всех деталей, пожалуйста, обратитесь к man:fonts-conf[5].

Этот файл должен иметь формат XML.
Обратите особое внимание на регистр символов, и удостоверьтесь, что все тэги корректно закрыты.
Файл начинается обычным заголовком XML, за которым следуют DOCTYPE и тэг `<fontconfig>`:

[.programlisting]
....

        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
        <fontconfig>
....

Как и говорилось ранее, все шрифты из каталога [.filename]#/usr/local/share/fonts/#, а также [.filename]#~/.fonts/# уже доступны для приложений, использующих Xft.
Чтобы добавить каталог, отличный от этих двух, добавьте строчку, подобную следующей, в файл [.filename]#/usr/local/etc/fonts/local.conf#:

[.programlisting]
....
<dir>/path/to/my/fonts</dir>
....

После добавления новых шрифтов, и особенно новых каталогов со шрифтами, перестройте кэши шрифтов:

[source,shell]
....
# fc-cache -f
....

Антиалиасинг делает границы несколько размытыми, что делает очень мелкий текст более читабельным и удаляет "лесенки" из текста большого размера, но может вызвать нечёткость при применении к тексту обычного размера.
Для исключения размеров шрифтов, меньших 14, из антиалиасинга, добавьте такие строки:

[.programlisting]
....
	<match target="font">
            <test name="size" compare="less">
                <double>14</double>
            </test>
            <edit name="antialias" mode="assign">
                <bool>false</bool>
            </edit>
        </match>
        <match target="font">
            <test name="pixelsize" compare="less" qual="any">
                <double>14</double>
            </test>
            <edit mode="assign" name="antialias">
                <bool>false</bool>
            </edit>
        </match>
....

Может оказаться, что для некоторых моноширинных шрифтов определение межсимвольного интервала при использовании антиалиасинга будет работать некорректно.
В частности, эта проблема возникает с KDE.
Одним из возможных решений этой проблемы является явное указание межсимвольного интервала равным 100.
Добавьте следующие строки:

[.programlisting]
....
	<match target="pattern" name="family">
           <test qual="any" name="family">
               <string>fixed</string>
           </test>
           <edit name="family" mode="assign">
               <string>mono</string>
           </edit>
        </match>
        <match target="pattern" name="family">
            <test qual="any" name="family">
                <string>console</string>
            </test>
            <edit name="family" mode="assign">
                <string>mono</string>
            </edit>
        </match>
....

(это создаст алиасы `"mono"` для других общеупотребительных имён шрифтов фиксированного размера), а затем добавьте:

[.programlisting]
....
         <match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>mono</string>
             </test>
             <edit name="spacing" mode="assign">
                 <int>100</int>
             </edit>
         </match>
....

С некоторыми шрифтами, такими, как Helvetica, при антиалиасинге могут возникнуть проблемы.
Обычно это проявляется в виде шрифта, который наполовину вертикально обрезан.
Хуже того, это может привести к сбоям подобных приложений.
Во избежание этого следует добавить следующее в файл [.filename]#local.conf#:

[.programlisting]
....
	<match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>Helvetica</string>
             </test>
             <edit name="family" mode="assign">
                 <string>sans-serif</string>
             </edit>
         </match>
....

После корректировки файла [.filename]#local.conf# удостоверьтесь, что файл завершён тэгом `</fontconfig>`.
Если этого не сделать, изменения будут проигнорированы.

Пользователи могут добавлять персонифицированные настройки посредством создания собственных файлов [.finename]#~/.config/fontconfig/fonts.conf#.
Эти файлы имеют тот же самый формат XML, что описан выше.

И последнее замечание: при использовании дисплея LCD может понадобиться включение разбиения точек.
При этом компоненты красного, зелёного и голубого цветов (разделяемые по горизонтали), рассматриваются как отдельные точки для улучшения разрешения экрана по горизонтали; результат может оказаться потрясающим.
Для включения этого механизма добавьте такую строчку где-нибудь в файле [.filename]#local.conf#:

[.programlisting]
....
	<match target="font">
            <test qual="all" name="rgba">
                <const>unknown</const>
            </test>
            <edit name="rgba" mode="assign">
                <const>rgb</const>
            </edit>
        </match>
....

[NOTE]
====
В зависимости от типа дисплея, `rgb` может потребоваться заменить на `bgr`, `vrgb` или `vbgr`: пробуйте и смотрите, что работает лучше.
====

Для получения более полной информации об установке и настройке шрифтов во FreeBSD, пожалуйста, прочтите статью link:{fonts}[Шрифты и FreeBSD].
