//
// The FreeBSD Russian Documentation Project
//
// Original EN revision: SVN r49376
// Synced with Russian version (SVN 52803) from official repository
//

---
title: Глава 6. X Window System
part: Часть I. В начале
prev: books/handbook/ports
next: books/handbook/partii
showBookMenu: true
weight: 8
path: "/books/handbook/"
---

[[x11]]
= X Window System
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/x11/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[x11-synopsis]]
== Обзор

Процедура установки FreeBSD при помощи bsdinstall не предусматривает автоматической установки графического пользовательского интерфейса.
Эта глава описывает процесс установки и настройки пакета Xorg, предоставляющий X Window System с открытым кодом, обеспечивающий графическую среду работы.
Затем она объясняет, как найти и установить оболочку рабочего стола или оконный менеджер.

[TIP]
====
Пользователи, предпочитающие метод установки, при котором Xorg настраивается автоматически и предлагаются варианты выбора оконных менеджеров, должны обратить внимание на веб-сайт link:http://www.pcbsd.org/[pcbsd.org].
====

Для получения дополнительной информации об оборудовании, которое поддерживается в Xorg, обратитесь к веб-сайту link:http://www.x.org/[x.org].

После чтения этой главы вы будете знать:

* О различных компонентах X Window System и их взаимодействии.
* Как установить и настроить Xorg.
* Как установить и настроить несколько оконных менеджеров и оболочек рабочего стола.
* Как установить и использовать различные оконные менеджеры.
* Как использовать шрифты TrueType(R) в Xorg.
* Как настроить вашу систему на графический интерфейс входа (XDM).

Перед чтением этой главы вам требуется:

* Знать, как устанавливать дополнительное программное обеспечение сторонних разработчиков в соответствии с описанием в разделе crossref:ports[ports, Установка приложений. Порты и пакеты].

[[x-understanding]]
== Терминология

Хотя нет необходимости вникать во все тонкости различных компонент X Window System и взаимодействия между ними, некоторые базовые знания об этих компонентах могут быть полезными.

X-сервер::
X изначально разрабатывалась, чтобы быть системой, ориентированной на работу в сети, и использует модель "клиент-сервер".
В этой модели "X-сервер" работает на компьютере с клавиатурой, монитором и мышью.
Область ответственности сервера включает управление дисплеем, обработку ввода с клавиатуры и мыши, а также обработку ввода и вывода с других устройств, таких, как планшет или видеопроектор.
Некоторых это запутывает, потому что терминология X в точности противоположна тому, что они ожидают.
Они полагают, что "X-сервером" будет являться большая мощная машина в конце коридора, а "X-клиентом" выступает компьютер на их рабочем столе.

X-клиент::
Каждое X-приложение, такое, как XTerm или Firefox, является "клиентом".
Клиент посылает сообщения серверу, такие, как "Пожалуйста, нарисуй окно со следующими координатами", а сервер посылает в ответ сообщения типа "Пользователь только что щёлкнул мышью на кнопке OK".

При использовании дома или в офисе, сервер и клиенты X, как правило, работают на том же самом компьютере.
Однако можно также запустить X-сервер на более слабом компьютере, а приложения X запускать на более мощной системе.
При таком сценарии коммуникации между X-клиентом и сервером осуществляются по сети.

оконный менеджер::
X не определяет, в каком виде окна должны быть представлены на экране, как их двигать мышью, какие комбинации клавиш должны использоваться для переключения между окнами, как должны выглядеть заголовки окон, должны ли в них быть кнопки для закрытия и так далее.
Вместо этого X делегирует ответственность за это отдельному приложению управления окнами.
Существуют link:http://xwinman.org/[десятки оконных менеджеров].
Каждый оконный менеджер реализует собственный внешний вид и подход к управлению: некоторые поддерживают виртуальные рабочие столы, некоторые позволяют изменять назначения комбинаций клавиш для управления рабочим окружением, в некоторых есть кнопка "Пуск", а некоторые поддерживают "темы", позволяя полностью менять образ рабочего окружения.
Оконные менеджеры находятся в категории [.filename]#x11-wm# Коллекции Портов.

Каждый оконный менеджер использует собственный механизм настройки.
Некоторые предполагают наличие вручную созданного конфигурационного файла, тогда как другие предоставляют графические инструменты для выполнения большинства задач по настройке.

оболочки рабочего стола::
KDE и GNOME рассматриваются как оболочки для организации рабочего стола, так как они включают в себя полный набор приложений для выполнения повседневной работы.
Сюда могут входить офисные пакеты, web-браузеры и игры.

политика фокусирования::
Менеджер окон отвечает за политику фокусирования мыши.
Эта политика предоставляет некоторый механизм, который определяет, какое окно активно обрабатывает нажатия клавиш, а также визуально отображает, какое окно является в настоящий момент активным.

Одна из политик фокусирования называется "фокусирование по щелчку".
В такой модели окно становится активным после получения щелчка мыши.
В политике "фокус следует за мышью" фокус получает окно, находящееся под указателем мыши, и этот фокус меняется при указании на другое окно.
Если мышь находится поверх корневого окна, то фокусирование производится на этом окне.
В модели "нечёткого фокусирования" при перемещении мыши на корневое окно фокус остаётся на последнем используемом окне.
При нечётком фокусовании фокус меняется только при перемещении курсора на новое окно, и не меняется при выходе из текущего окна.
В политике "фокусирования по щелчку" активное окно появится поверх всех других окон.
Все нажатия клавиш при этом будут направляться в это окно, даже если указатель переместился на другое окно.

Разные оконные менеджеры поддерживают разные модели фокусирования.
Все они поддерживают фокусирование по щелчку, и большинство также поддерживает другие политики.
Обратитесь к документации по оконному менеджеру для выяснения доступности моделей фокусирования.

виджеты::
Виджет - это термин, употребляемый для любых объектов пользовательского интерфейса, на которые можно щёлкать или которыми можно манипулировать каким-либо образом.
Сюда включаются кнопки, зависимые и независимые опции, иконки и списки.
Библиотека виджетов представляет собой набор виджетов, используемых для создания графических приложений.
Существует несколько популярных библиотек виджетов, среди которых Qt, используемый в KDE, и GTK+, применяемый в GNOME.
В результате приложения будут иметь разный внешний вид в зависимости от того, какая библиотека использовалась для создания приложения.

[[x-install]]
== Установка Xorg

Во FreeBSD Xorg может быть установлен как пакет или как порт.

Для построения и установки из Коллекции портов выполните следующие команды:

[source,shell]
....
# cd /usr/ports/x11/xorg
# make install clean
....

Откомпилированный пакет может быть установлен быстрее, но он даёт меньше опций для настройки:

[source,shell]
....
# pkg install xorg
....

Любой из этих методов приводит к установке полной системы Xorg и является наилучшим подходом для большинства пользователей.

Более компактная версия X, подходящая для опытных пользователей, доступна в пакете package:x11/xorg-minimal.
При его выборе подавляющее большинство документов, библиотек и приложений не будут устанавливаться.
Некоторым приложениям для работы требуются эти дополнительные компоненты.

[[x-config]]
== Настройка Xorg

[[x-config-quick-start]]
=== Быстрый запуск

Xorg поддерживает большинство распространённых графических адаптеров, клавиатур и устройств позиционирования.
Эти устройства распознаются автоматически и не требуют ручной настройки.

Если Xorg использовалась ранее на этом компьютере, перенесите или удалите все существующие конфигурационные файлы:

[source,shell]
----
# mv /etc/X11/xorg.conf ~/xorg.conf.etc
# mv /usr/local/etc/X11/xorg.conf ~/xorg.conf.localetc
----

Добавьте пользователя, который будет запускать Xorg, к группе `video` или
`wheel` для обеспечения возможности использования 3D-ускорения при его
доступности.
Чтобы добавить пользователя jru к одной из указанных групп, выполните следующую команду:

[source,shell]
----
# pw groupmod video -m jru || pw groupmod wheel -m jru
----

По умолчанию в поставку включён оконный менеджер TWM.
Он запускается вместе с запуском Xorg следующей командой:

[source,shell]
----
# startx
----

В некоторых более старых версиях FreeBSD для того, чтобы обратное переключение в текстовый режим работало корректно, в качестве системной консоли должно использоваться устройство man:vt[4].
Для получения более полной информации обратитесь к разделу link:{handbook}#x-config-kms.

[[x-config-user-group]]
=== Пользовательская группа для графики с ускорением

Для включения 3D-ускорения на графических адаптерах необходим доступ к устройству [.filename]#/dev/dri#.
Как правило, проще всего добавить пользователя, который будет запускать X, в группу `video` или `wheel`.
Для включения пользователя slurms в группу `video` или в группу `wheel` в случае отсутствия группы `video` в команде ниже используется man:pw[8]:

[source,shell]
----
# pw groupmod video -m slurms || pw groupmod wheel -m slurms
----

[[x-config-kms]]
=== Настройка режима ядра (KMS)

Когда компьютер переключает консоль в режим более высокого разрешения для работы X, он должен задать _режим_ выдачи видео.
Последние версии Xorg используют систему внутри ядра для переключения этих режимов более эффективно.
Более старые версии FreeBSD используют устройство man:sc[4], которое не работает с KMS.
В итоге после закрытия сеанса X системная консоль пуста, хотя продолжает функционировать.
Более новое консольное устройство man:vt[4] не имеет этой проблемы.

Для активации man:vt[4] добавьте в файл [.filename]#/boot/loader.conf# следующую строку:

....
kern.vty=vt
....

[[x-config-files]]
=== Конфигурационные файлы

[[x-config-files-directory]]
==== Каталог

Xorg использует несколько каталогов для размещения конфигурационных файлов.
Для FreeBSD каталог [.filename]#/usr/local/etc/X11/# является рекомендованным для таких файлов.
Использование этого каталога помогает размещать файлы прикладной системы отдельно от файлов операционной системы.

Размещение конфигурационных файлов в когда-то традиционном каталоге [.filename]#/etc/X11/# всё ещё поддерживается.
Однако это приводит к смешиванию файлов прикладной системы со стандартными файлами FreeBSD, что не рекомендуется.

[[x-config-files-single-or-multi]]
==== Один файл или несколько

Использовать несколько файлов вместо традиционно единственного [.filename]#xorg.conf# легче, так как каждый из них содержит специфичные настройки.
Эти файлы размещаются в подкаталоге [.filename]#xorg.conf.d/# основного каталога, содержащего конфигурационные файлы.
Полный маршрут обычно выглядит как [.filename]#/usr/local/etc/X11/xorg.conf.d/#.

Примеры таких файлов приведены в этом разделе ниже.

Использование традиционного единого файла [.filename]#xorg.conf# также поддерживается, но это не так гибко и не так прозрачно, как использование нескольких файлов в подкаталоге [.filename]#xorg.conf.d/#.

[[x-config-video-cards]]
=== Графические адаптеры

[[x-config-video-cards-intel]]
Intel(R)::
Ускорение 3D-графики поддерживается для большинства графических адаптеров Intel(R), вплоть по Ivy Bridge (HD Graphics 2500, 4000 и P4000), включая Iron Lake (HD Graphics) и Sandy Bridge (HD Graphics 2000).

Название драйвера: `intel`

Для получения справочной информации обратитесь к странице link:https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units[].

[[x-config-video-cards-radeon]]
AMD(R) Radeon::
Ускорение 2D и 3D поддерживается для адаптеров Radeon вплоть по и включая линейку HD6000.

Название драйвера: `radeon`

Для получения справочной информации обратитесь к странице link:https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units[].

[[x-config-video-cards-nvidia]]
NVIDIA(R)::
В категории [.filename]#x11# Коллекции Портов доступно несколько драйверов NVIDIA.  Установите драйвер, соответствующий графическому адаптеру.

Для получения справочной информации обратитесь к странице link:https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units[].

[[x-config-video-cards-hybrid]]
Смешанные комбинации графических адаптеров::
В некоторые ноутбуки добавляют дополнительные модули обработки графики дополнительно к тем, что встроены в набор микросхем или процессор.
_Optimus_ комбинирует оборудование Intel(R) и NVIDIA.
_Переключаемая графика_ или _Гибридная графика_ являются комбинацией процессора Intel(R) или AMD(R) и графического процессора AMD(R) Radeon.

Реализации подобных гибридных графических систем разнообразны, и Xorg во FreeBSD не имеет возможности отслеживать все их варианты.

Некоторые компьютеры имеют возможность отключить один из графических адаптеров в BIOS или выбрать режим _discrete_, который может быть использован в комбинации с одним из стандартных драйверов видеокарт.
К примеру, иногда возможно отключить GPU от NVIDIA в системе Optimus.
В таком случае возможно использовать адаптер Intel(R) вместе с драйвером от Intel(R).

Настройки BIOS зависят от модели компьютера.
В некоторых ситуациях оба графических процессора могут оставаться активированными, при этом для того, чтобы обеспечить работоспособность такой системы, достаточно создания конфигурационного файла, использующего в разделе `Device` только основной GPU.

[[x-config-video-cards-other]]
Прочие видеокарты::
В каталоге [.filename]#x11-drivers# Коллекции Портов можно найти драйверы для некоторых реже встречающихся графических адаптеров.

Адаптеры, которые не поддерживаются специализированным драйвером, всё же могут использоваться совместно с драйвером package:x11-drivers/xf86-video-vesa[].
Этот драйвер устанавливается вместе с пакетом package:x11/xorg[].
Также его можно установить в ручном режиме как пакет package:x11-drivers/xf86-video-vesa[].
Xorg пытается использовать этот драйвер в тех случаях, когда для установленного графического адаптера специализированный драйвер не может быть найден.

package:x11-drivers/xf86-video-scfb[] представляет собой подобный неспециализированный драйвер видео, работающий со многими компьютерами UEFI и ARM(R).

[[x-config-video-cards-file]]
Настройка драйвера видео в файле::

Для настройки драйвера Intel(R) в конфигурационном файле:

[[x-config-video-cards-file-intel]]
.Выберите драйвер видео Intel(R) в файле
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/driver-intel.conf#

[.programlisting]
....
Section "Device"
        Identifier "Card0"
        Driver     "intel"
        # BusID    "PCI:1:0:0"
EndSection
....

Если присутствует больше одного видеоадаптера, то можно снять комментирование с идентификатора `BusID` и задать желаемый адаптер.
Список ID шин видеокарт можно просмотреть командой `pciconf -lv | grep -B3 display`.
====

Для настройки драйвера Radeon в конфигурационном файле:

[[x-config-video-cards-file-radeon]]
.Выберите драйвер видео Radeon в файле
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/driver-radeon.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "radeon"
EndSection
....
====

Для настройки драйвера VESA в конфигурационном файле:

[[x-config-video-cards-file-vesa]]
.Выберите драйвер видео VESA в файле
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/driver-vesa.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "vesa"
EndSection
....
====

Для настройки драйвера `scfb` к использованию с UEFI или на компьютере ARM(R):

[[x-config-video-cards-file-scfb]]
.Выберите драйвер видео `scfb` в файле
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/driver-scfb.conf#

[.programlisting]
....
Section "Device"
       Identifier "Card0"
       Driver     "scfb"
EndSection
....
====

[[x-config-monitors]]
=== Мониторы

Практически все мониторы поддерживают стандарт Extended Display Identification Data (EDID).
Xorg использует EDID для работы с монитором и выявления поддерживаемых разрешений и частот обновления.
Затем система выбирает комбинацию параметров, наиболее подходящую к
использованию с данным монитором.

Другие разрешения, поддерживаемые данным монитором, могут быть установлены указанием требуемого разрешения в конфигурационных файлах либо после запуска X-сервера при помощи man:xrandr[1].

[[x-config-monitors-xrandr]]
Использование man:xrandr[1]::
Запустите man:xrandr[1] без каких-либо параметров, чтобы посмотреть список устройств и выявленные режимы работы мониторов:

[source,shell]
----
$ xrandr
Screen 0: minimum 320 x 200, current 3000 x 1920, maximum 8192 x 8192
DVI-0 connected primary 1920x1200+1080+0 (normal left inverted right x axis y axis) 495mm x 310mm
   1920x1200     59.95*+
   1600x1200     60.00
   1280x1024     85.02    75.02    60.02
   1280x960      60.00
   1152x864      75.00
   1024x768      85.00    75.08    70.07    60.00
   832x624       74.55
   800x600       75.00    60.32
   640x480       75.00    60.00
   720x400       70.08
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
----

Этот текст показывает, что устройство `DVI-0` используется для организации экрана разрешением 1920x1200 точек с частотой обновления около 60 Гц.
К соединениям `DisplayPort-0` и `HDMI-0` мониторы не подключены.

При помощи man:xrandr[1] могут быть выбраны любые другие режимы работы дисплея.
К примеру, для переключения в режим 1280x1024 на частоте 60 Гц запустите следующую команду:

[source,shell]
----
$ xrandr --mode 1280x1024 --rate 60
----

Часто решаемой задачей является использование внешнего видеовыхода на ноутбуке для подключения видеопроектора.

Типы и количество выходов видео у различных устройств отличаются, и наименование, которое даётся каждому видеовыходу, отличаются у разных драйверов.
То, что в одном драйвере обозначается как `HDMI-1`, в другом может называться `HDMI1`.
Поэтому первым шагом является запуск man:xrandr[1] для выдачи списка всех доступных устройств вывода:

[source,shell]
----
$ xrandr
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
LVDS1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1366x768      60.04*+
   1024x768      60.00
   800x600       60.32    56.25
   640x480       59.94
VGA1 connected (normal left inverted right x axis y axis)
   1280x1024     60.02 +  75.02
   1280x960      60.00
   1152x864      75.00
   1024x768      75.08    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   640x480       75.00    72.81    66.67    60.00
   720x400       70.08
HDMI1 disconnected (normal left inverted right x axis y axis)
DP1 disconnected (normal left inverted right x axis y axis)
----

Было обнаружено четыре видеоустройства: встроенная панель `LVDS1` и внешние подключения `VGA1`, `HDMI1` и `DP1`.

Проектор оказался подключенным к устройству `VGA1`.
Теперь используем man:xrandr[1] для приведения настроек этого устройства к стандартному разрешению проектора и добавления дополнительного пространства к рабочему столу справа:

[source,shell]
----
$ xrandr --output VGA1 --auto --right-of LVDS1
----

Параметр `--auto` задаёт выбор разрешения и частоты обновления, выявленному через EDID.
Если разрешение определяется некорректно, вместо параметра `--auto` при помощи опции `--mode` может быть задано фиксированное значение.
К примеру, большинство проекторов могут работать с разрешением 1024x768, что задаётся параметром `--mode 1024x768`.

man:xrandr[1] часто запускается из [.filename]#.xinitrc# для того, чтобы задать подходящий режим при запуске X.

[[x-config-monitors-files]]
Настройка разрешения монитора в файле::
Для того, чтобы задать разрешение 1024x768 в конфигурационном файле:

.Указание разрешения экрана в файле
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/screen-resolution.conf#

....
Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	SubSection "Display"
	Modes "1024x768"
	EndSubSection
EndSection
....
====

То небольшое количество моделей мониторов, не поддерживающих EDID, может быть настроены указанием параметров `HorizSync` и `VertRefresh` в границах частот, поддерживаемых монитором.

==== Ручная настройка частот монитора

[.filename]#/usr/local/etc/X11/xorg.conf.d/monitor0-freq.conf#

[.programlisting]
....
Section "Monitor"
        Identifier   "Monitor0"
	HorizSync    30-83   # kHz
	VertRefresh  50-76   # Hz
EndSection
....

[[x-config-input]]
=== Устройства ввода

[[x-config-input-keyboard]]
==== Клавиатуры

[[x-config-input-keyboard-layout]]
Раскладка клавиатуры::
Стандартизованное размещение клавиш на клавиатуре называется раскладкой (_layout_).
Раскладки и другие настраиваемые параметры перечислены в man:xkeyboard-config[7].

По умолчанию применяется раскладка United States (Соединённые Штаты).
Для выбора альтернативной раскладки задайте параметры `XkbLayout` и `XkbVariant` в `InputClass`.
Они будут применяться ко всем устройствам ввода этого класса.

В данном примере выбирается раскладка клавиатуры French (французская) в варианте `oss`.

.Настройка раскладки клавиатуры
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/keyboard-fr-oss.conf#

[.programlisting]
....
Section "InputClass"
       Identifier      "KeyboardDefaults"
       Driver          "keyboard"
       MatchIsKeyboard "on"
       Option          "XkbLayout" "fr"
       Option          "XkbVariant" "oss"
EndSection
....
====

.Настройка нескольких раскладок клавиатуры
[example]
====
Установка клавиатурных раскладок Соединённых Штатов, Испании и Украины.
Последовательное переключение между ними выполняется нажатием kbd:[Alt+Shift].
Для улучшения управления переключениями между раскладками и отображения текущей раскладки можно использовать пакеты package:x11/xxkb[] или package:x11/sbxkb[].

[.filename]#/usr/local/etc/X11/xorg.conf.d/kbd-layout-multi.conf#

[.programlisting]
....
Section "InputClass"
       Identifier      "All Keyboards"
       MatchIsKeyboard "yes"
       Option          "XkbLayout" "us, es, ua"
EndSection
....
====

[[x-config-input-keyboard-zap]]
Завершение работы Xorg c клавиатуры::
Работа X может быть завершена нажатием определённой комбинации клавиш.
По умолчанию эта комбинация не задана, так как эта возможность конфликтует с клавиатурными командами некоторых приложений.
Включение этой функции требует внесения изменений в раздел настройки клавиатуры `InputDevice`:

.Активация завершения работы X с клавиатуры
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/keyboard-zap.conf#

[.programlisting]
....
Section "InputClass"
       Identifier      "KeyboardDefaults"
       Driver          "keyboard"
       MatchIsKeyboard "on"
       Option          "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection
....
====

[[x11-input-mice]]
==== Мыши и устройства позиционирования

Многие характеристики работы мыши могут быть изменены конфигурационными параметрами.
Для получения полного списка обратитесь к man:mousedrv[4x].

[[x11-input-mice-buttons]]
Кнопки мыши::

.Количество кнопок мыши может быть задано в разделе `InputDevice` о мыши файла [.filename]#xorg.conf#.
Для задания количества кнопок, равного 7:

.Установка количества кнопок мыши
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/mouse0-buttons.conf#

[.programlisting]
....
Section "InputDevice"
       Identifier  "Mouse0"
       Option      "Buttons" "7"
EndSection
....
====

[[x-config-manual-configuration]]
=== Ручная настройка

В некоторых случая функция автоматической настройки Xorg не работает с определённым аппаратным обеспечением, либо имеется потребность в других настройках.
Для таких ситуаций может быть создан специальный конфигурационный файл.

Файл с настройками может быть сгенерирован при помощи Xorg на основании информации о выявленном оборудовании.
Этот файл зачастую оказывается полезной отправной точкой для специальных конфигураций.

Генерация [.filename]#xorg.conf#:

[source,shell]
----
# Xorg -configure
----

Конфигурационный файл сохраняется в [.filename]#/root/xorg.conf.new#.
Внесите любые требуемые изменения, затем проверьте этот файл следующей командой:

[source,shell]
----
# Xorg -config /root/xorg.conf.new
----

После того, как новая конфигурация откорректирована и проверена, её можно разделить на файлы меньшего размера и разместить в обычном месте, [.filename]#/usr/local/etc/X11/xorg.conf.d/#.

[[x-fonts]]
== Использование шрифтов в Xorg

[[type1]]
=== Шрифты Type1

Шрифты, используемые по умолчанию и распространяемые вместе с Xorg, вряд ли можно назвать идеально подходящими для применения в обычных издательских приложениях.
Большие презентационные шрифты выглядят рвано и непрофессионально, а мелкие шрифты вообще невозможно разобрать.
Однако есть некоторое количество свободно распространяемых высококачественных шрифтов Type1 (PostScript(R)), которые можно без изменений использовать с Xorg.
К примеру, в наборе шрифтов URW (package:x11-fonts/urwfonts[]) имеются высококачественные версии стандартных шрифтов type1 (Times Roman(TM), Helvetica(TM), Palatino(TM) и другие).
В набор Freefonts (package:x11-fonts/freefonts[]) включено ещё больше шрифтов, однако большинство из них предназначено для использования в программном обеспечении для работы с графикой, например, Gimp, и они не вполне пригодны для использования в качестве экранных шрифтов.
Кроме того, Xorg с минимальными усилиями может быть настроена на использование шрифтов TrueType(R).
Более подробную информацию можно найи на странице справочной системы man:X[7] или в <<truetype>>.

Для установки вышеупомянутых коллекций шрифтов Type1 из Коллекции Портов выполните следующие команды:

[source,shell]
....
# cd /usr/ports/x11-fonts/urwfonts
# make install clean
....

То же самое нужно будет сделать для коллекции freefont и других. Чтобы X-сервер обнаруживал этих шрифты, добавьте соответствующую строку в файл настройки X сервера ([.filename]#/etc/X11/xorg.conf#), которая должна выглядеть так:

[.programlisting]
....
FontPath "/usr/local/share/fonts/urwfonts/"
....

Либо из командной строки при работе с X выполните:

[source,shell]
....
% xset fp+ /usr/local/share/fonts/urwfonts
% xset fp rehash
....

Это сработает, но будет потеряно, когда сеанс работы с X будет закрыт, если эта команда не будет добавлена в начальный файл ([.filename]#~/.xinitrc# в случае обычного сеанса через `startx` или [.filename]#~/.xsession# при входе через графический менеджер типа XDM).
Третий способ заключается в использовании нового файла [.filename]#/usr/local/etc/fonts/local.conf#, как это показано в разделе <<antialias>>.

[[truetype]]
=== Шрифты TrueType(R)

В Xorg имеется встроенная поддержка шрифтов TrueType(R). Имеются два модуля, которые могут обеспечить эту функциональность. В нашем примере используется модуль freetype, потому что он в большей степени похож на другие механизмы для работы с шрифтами. Для включения модуля freetype достаточно в раздел `"Module"` файла [.filename]#/etc/X11/xorg.conf# добавить следующую строчку.

[.programlisting]
....
Load  "freetype"
....

Теперь создайте каталог для шрифтов TrueType(R) (к примеру, [.filename]#/usr/local/share/fonts/TrueType#) и скопируйте все шрифты TrueType(R) в этот каталог.
Имейте в виду, что напрямую использовать шрифты TrueType(R) с Apple(R) Mac(R) нельзя; для использования с Xorg они должны быть в формате UNIX(R)/MS-DOS(R)/Windows(R).
После того, как файлы будут скопированы в этот каталог, воспользуйтесь утилитой mkfontdir для создания [.filename]#fonts.dir#, который подскажет подсистеме вывода шрифтов X, что эти новые файлы были установлены.
`mkfontdir` может быть установлена как пакет:

[source,shell]
....
# pkg install mkfontdir
....

После этого создайте индексный файл шрифтов X в каталоге:

[source,shell]
....
# cd /usr/local/share/fonts/TrueType
# mkfontdir
....

Теперь добавьте каталог со шрифтами TrueType(R) к маршруту поиска шрифтов.
Это делается точно так же, как описано в <<type1>>:

[source,shell]
----
% xset fp+ /usr/local/share/fonts/TrueType
% xset fp rehash
----

или добавьте строку `FontPath` в файл [.filename]#xorg.conf#.

Теперь Gimp, Apache OpenOffice и все остальные приложения для X должны обнаружить установленные шрифты TrueType(R).
Очень маленькие (как текст веб-страницы на дисплее с высоким разрешением) и очень большие (в StarOffice(TM)) шрифты теперь будут выглядеть гораздо лучше.

[[antialias]]
=== Шрифты с антиалиасингом

Все шрифты Xorg, расположенные в каталогах [.filename]#/usr/local/share/fonts/# и [.filename]#~/.fonts/#, автоматически становятся доступными для применения антиалиасинга в приложениях, использующих Xft.
Большинство современных приложений умеет работать с Xft, в том числе KDE, GNOME и Firefox.

Для управления применением антиалиасинга к шрифтам, а также для настройки параметров антиалиасинга, создайте (или отредактируйте, если он уже существует) файл [.filename]#/usr/local/etc/fonts/local.conf#. Некоторые мощные возможности системы шрифтов Xft могут быть настроены при помощи этого файла; в этом разделе описаны лишь некоторые простые возможности. Для выяснения всех деталей, пожалуйста, обратитесь к man:fonts-conf[5].

Этот файл должен быть сформирован в формате XML. Обратите особое внимание на регистр символов, и удостоверьтесь, что все тэги корректно закрыты. Файл начинается обычным заголовком XML, за которым следуют DOCTYPE и тэг `<fontconfig>`:

[.programlisting]
....

        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
        <fontconfig>
....

Как и говорилось ранее, все шрифты из каталога [.filename]#/usr/local/share/fonts/#, а также [.filename]#~/.fonts/# уже доступны для приложений, использующих Xft.
Чтобы добавить каталог, отличный от этих двух, добавьте строчку, подобную следующей, в файл [.filename]#/usr/local/etc/fonts/local.conf#:

[.programlisting]
....
<dir>/path/to/my/fonts</dir>
....

После добавления новых шрифтов, и особенно новых каталогов со шрифтами, перестройте кэши шрифтов:

[source,shell]
....
# fc-cache -f
....

Антиалиасинг делает границы несколько размытыми, что делает очень мелкий текст более читабельным и удаляет "лесенки" из текста большого размера, но может вызвать нечёткость при применении к тексту обычного размера. Для исключения размеров шрифтов, меньших 14, из антиалиасинга, добавьте такие строки:

[.programlisting]
....
        <match target="font">
            <test name="size" compare="less">
                <double>14</double>
            </test>
            <edit name="antialias" mode="assign">
                <bool>false</bool>
            </edit>
        </match>
        <match target="font">
            <test name="pixelsize" compare="less" qual="any">
                <double>14</double>
            </test>
            <edit mode="assign" name="antialias">
                <bool>false</bool>
            </edit>
        </match>
....

Может оказаться, что для некоторых моноширинных шрифтов определение межсимвольного интервала при использовании антиалиасинга будет работать некорректно.
В частности, эта проблема возникает с KDE.
Одним из возможных решений этой проблемы является явное указание межсимвольного интервала равным 100.
Добавьте следующие строки:

[.programlisting]
....
 <match target="pattern" name="family">
           <test qual="any" name="family">
               <string>fixed</string>
           </test>
           <edit name="family" mode="assign">
               <string>mono</string>
           </edit>
        </match>
        <match target="pattern" name="family">
            <test qual="any" name="family">
                <string>console</string>
            </test>
            <edit name="family" mode="assign">
                <string>mono</string>
            </edit>
        </match>
....

(это создаст алиасы `"mono"` для других общеупотребительных имён шрифтов фиксированного размера), а затем добавьте:

[.programlisting]
....
         <match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>mono</string>
             </test>
             <edit name="spacing" mode="assign">
                 <int>100</int>
             </edit>
         </match>
....

С некоторыми шрифтами, такими, как Helvetica, при антиалиасинге могут возникнуть проблемы . Обычно это проявляется в виде шрифта, который наполовину вертикально обрезан. Хуже того, это может привести к сбоям подобных приложений.
Во избежание этого следует добавить следующее в файл [.filename]#local.conf#:

[.programlisting]
....
         <match target="pattern" name="family">
             <test qual="any" name="family">
                 <string>Helvetica</string>
             </test>
             <edit name="family" mode="assign">
                 <string>sans-serif</string>
             </edit>
         </match>
....

После корректировки файла [.filename]#local.conf# удостоверьтесь, что файл завершён тэгом `</fontconfig>`. Если этого не сделать, изменения будут проигнорированы.

Пользователи могут добавлять персонифицированные настройки посредством создания собственных файлов [.finename]#~/.config/fontconfig/fonts.conf#.
Эти файлы имеют тот же самый формат XML, что описан выше.

И последнее замечание: при использовании дисплея LCD может понадобиться включение разбиения точек. При этом компоненты красного, зелёного и голубого цветов (разделяемые по горизонтали), рассматриваются как отдельные точки для улучшения разрешения экрана по горизонтали; результат может оказаться потрясающим. Для включения этого механизма добавьте такую строчку где-нибудь в файле [.filename]#local.conf#:

[.programlisting]
....
	<match target="font">
            <test qual="all" name="rgba">
                <const>unknown</const>
            </test>
            <edit name="rgba" mode="assign">
                <const>rgb</const>
            </edit>
        </match>
....

[NOTE]
====
В зависимости от типа дисплея, `rgb` может потребоваться заменить на `bgr`, `vrgb` или `vbgr`: пробуйте и смотрите, что работает лучше.
====

[[x-xdm]]
== Менеджер экранов (X Display Manager)

=== Вступление

Xorg включает в себя менеджер графических дисплеев, XDM, который может использоваться для управления сеансами входа.
XDM обеспечивает графический интерфейс для выбора сервера дисплеев, к которому вы хотите подключиться, а также для ввода авторизационной информации, такой, как комбинация учётной записи и пароля.

В этом разделе показывается, как настроить X Display Manager во FreeBSD.
Некоторые графические оболочки имеют собственные графические менеджеры, управляющие входом в систему.
Обратитесь к <<x11-wm-gnome>> для получения инструкций по настройке GNOME Display Manager и <<x11-wm-kde>> для получения инструкций по настройке KDE Display Manager.

=== Настройка XDM

Для установки XDM используйте пакадж или порт package:x11/xdm[].
После установки XDM может быть настроен для запуска при загрузке системы путём редактирования следующей строки в [.filename]#/etc/ttys#:

[source,shell]
----
ttyv8    "/usr/local/bin/xdm -nodaemon"  xterm   off secure
----

Замените `off` на `on` и сохраните откорректированную версию.
`ttyv8` в этой строке указывает на то, что XDM будет запускаться на девятом виртуальном терминале.

Каталог с конфигурационными файлами XDM находится в [.filename]#/usr/local/lib/X11/xdm#.
Он содержит несколько файлов, используемых для изменения поведения и внешнего вида XDM, а также небольшой набор скриптов и программ, применяемых для настройки рабочего стола при запуске XDM.
В <<xdm-config-files>> кратко описывается предназначение каждого из этих файлов.
Точный синтаксис и использование этих файлов описывается в man:xdm[1].

[[xdm-config-files]]
.Конфигурационные файлы XDM
[cols="1,1", frame="none", options="header"]
|===
|Файл
|Описание

|[.filename]#Xaccess#
|Протокол для подключения к XDM называется X Display Manager Connection Protocol (XDMCP).  Данный файл является набором правил для авторизации клиентов, контролирующий XDMCP-соединения с удалённых машин.  По умолчанию этот файл не разрешает подключаться никаким удалённым клиентам.

|[.filename]#Xresources#
|Этот файл управляет внешним видом и поведением экранов той части XDM, которая отвечает за выбор дисплеев и вход в систему.  Настройки по умолчанию соответствуют прямоугольному окну входа в систему с хост-именем машины, отображаемым вверху крупным шрифтом, с приглашениями "Login:" и "Password:" ниже.  Формат этого файла идентичен файлу app-defaults, описанному в документации к Xorg.

|[.filename]#Xsession#
|Сценарий, который XDM запускает по умолчанию после входа пользователя в систему.  Как правило, у каждого пользователя будет иметься собственный сценарий в файле [.filename]#~/.xsession#, который имеет более высокий приоритет.

|[.filename]#Xsetup_#*
|Скрипт для автоматического запуска приложений до перехода к интерфейсам диспетчера дисплеев или входа в систему.  Для каждого используемого дисплея имеется собственный скрипт с названием [.filename]#Xsetup_*#, где `*` обозначает локальный номер дисплея. Обычно эти скрипты запускают в фоновом режиме одну или две программы, например, `xconsole`.

|[.filename]#xdm-config#
|Глобальный конфигурационный файл для всех экранов, запущенных на локальной машине.

|[.filename]#xdm-errors#
|Содержит ошибки, сгенерированные серверной программой.  Если попытки XDM запустить дисплей оканчиваются неудачно, поищите в этом файле сообщения об ошибках.  Эти сообщения также записываются в пользовательский файл [.filename]#~/.xsession-errors# для каждого подключения.

|[.filename]#xdm-pid#
|ID исполняющегося процесса XDM.

|===

=== Настройка удалённого доступа

По умолчанию только пользователи этой же системы могут входить в неё средствами XDM.  Чтобы разрешить пользователям других систем подключаться к серверу дисплеев, отредактируйте правила управления доступом и включите обработку входящих соединений.

Для настройки XDM на обработку любых соединений с удалённых систем, закомментируйте строку `DisplayManager.requestPort` файла [.filename]#/usr/local/lib/X11/xdm/xdm-config#, указав `!` в её начале:

[source,shell]
....
! SECURITY: do not listen for XDMCP or Chooser requests
! Comment out this line if you want to manage X terminals with xdm
DisplayManager.requestPort:     0
....

Сохраните отредактированное и перезапустите XDM.  Чтобы ограничить удалённый доступ, посмотрите пример записей в файле [.filename]#/usr/local/lib/X11/xdm/Xaccess# и обратитесь к man:xdm[1] для получения дополнительной информации.

[[x11-wm]]
== Графические оболочки

В этом разделе описывается порядок установки трёх популярных графических оболочек на систему FreeBSD.
Под графической оболочка может пониматься что угодно, от простого менеджера окон до полнофункционального набора приложений для рабочего стола.
В Коллекции Портов в категории [.filename]#x11-wm# доступно более сотни таких оболочек.

[[x11-wm-gnome]]
=== GNOME

GNOME является графической оболочкой с дружественным пользовательским интерфейсом.
В ней имеется панель для запуска приложений и отображения состояния, рабочий стол, набор инструментов и приложений, а также набор соглашений, облегчающих совместную работу и взаимную согласованность приложений.
Дополнительную информацию относительно GNOME во FreeBSD можно найти на сайте link:http://www.FreeBSD.org/gnome[http://www.FreeBSD.org/gnome].
Этот сайт содержит дополнительную документацию по установке, настройке и управлению GNOME во FreeBSD.

Эту графическую оболочку можно установить из пакета:

[source,shell]
----
# pkg install gnome3
----

Вместо этого можно построить GNOME из портов при помощи команды ниже. GNOME является большим приложением, его компиляция займёт определённое время даже на быстром компьютере.

[source,shell]
----
# cd /usr/ports/x11/gnome3
# make install clean
----

GNOME требует наличия смонтированной файловой системы [.filename]#/proc#.
Добавьте следующую строку в [.filename]#/etc/fstab# для автоматического монтирования этой файловой системы при запуске системы:

[.programlisting]
....
proc           /proc       procfs  rw  0   0
....

GNOME использует D-Bus и HAL для реализации шины передачи сообщений и уровня аппаратной абстракции.
Эти приложения устанавливаются автоматически как зависимости для GNOME.
Активируйте их в файле [.filename]#/etc/rc.conf#, чтобы они запускались при загрузке системы:

[.programlisting]
....
dbus_enable="YES"
hald_enable="YES"
....

После установки настройте Xorg на запуск GNOME.
Самый простой способ сделать это заключается в активации GDM, Менеджера дисплеев GNOME, который устанавливается в составе пакета или порта GNOME.
Его можно активировать, добавив следующую строку в [.filename]#/etc/rc.conf#:

[.programlisting]
....
gdm_enable="YES"
....

Зачастую желательно также запустить все сервисы GNOME.
Для этого добавьте вторую строку в [.filename]#/etc/rc.conf#:

[.programlisting]
....
gnome_enable="YES"
....

GDM запустится автоматически при загрузке системы.

Вторым способом запуска GNOME является набор команды `startx` в командной строке после настройки [.filename]#~/.xinitrc#.
Если указанный файл уже существует, то замените строку, в которой запускается используемый менеджер окон, на ту, что вызовет [.filename]#/usr/local/bin/gnome-session#.
Если такой файл отсутствует, создайте его следующей командой:

[source,shell]
----
% echo "exec /usr/local/bin/gnome-session" > ~/.xinitrc
----

Третий метод заключается в использовании XDM в качестве менеджера дисплеев.
В этом случае создайте выполнимый файл [.filename]#~/.xsession#:

[source,shell]
----
% echo "#!/bin/sh" > ~/.xsession
% echo "exec /usr/local/bin/gnome-session" >> ~/.xsession
% chmod +x ~/.xsession
----

[[x11-wm-kde]]
=== KDE

KDE является ещё одной простой в использовании графической оболочкой.
В неё включён набор приложений с общим визуальным и пользовательским подходом, стандартное меню и панели инструментов, короткие комбинации клавиш, цветовые схемы, интернационализация и централизованное управление настройками рабочего стола в диалоговом режиме.
Дополнительную информацию о KDE можно найти на сайте link:http://www.kde.org/[http://www.kde.org/].
Поищите информацию, специфичную для FreeBSD, на сайте link:http://freebsd.kde.org/[http://freebsd.kde.org].

Для установки пакета KDE наберите:

[source,shell]
----
# pkg install x11/kde4
----

Вместо этого можно построить KDE как порт при помощи команды ниже.
Процедура установки предусматривает меню для выбора компонентов для установки.
KDE является большим приложением, для его компиляции потребуется определённое время даже на быстром компьютере.

[source,shell]
----
# cd /usr/ports/x11/kde4
# make install clean
----

KDE требует наличия смонтированной файловой системы [.filename]#/proc#.
Добавьте вот такую строку в [.filename]#/etc/fstab# для автоматического монтирования этой файловой системы при запуске:

[.programlisting]
....
proc           /proc       procfs  rw  0   0
....

KDE использует D-Bus и HAL для реализации шины передачи сообщений и уровня аппаратной абстракции.
Эти приложения устанавливаются автоматически как зависимости для KDE.
Активируйте их в файле [.filename]#/etc/rc.conf#, чтобы они запускались при загрузке системы:

[.programlisting]
....
dbus_enable="YES"
hald_enable="YES"
....

В установочный набор KDE входит KDM, Менеджер Дисплеев KDE (KDE Display Manager).
Для его активации добавьте следующую строку в [.filename]#/etc/rc.conf#:

[.programlisting]
....
kdm4_enable="YES"
....

Другим способом запуска KDE является ввод команды `startx` из командной строки.
Чтобы это работало, в файле [.filename]#~/.xinitrc# должна быть следующая строка:

[.programlisting]
....
exec /usr/local/bin/startkde
....

Третьим способом запуска KDE является использование XDM.
Чтобы это сделать, создайте выполнимый файл [.filename]#~/.xsession# следующим образом:

[source,shell]
----
% echo "#!/bin/sh" > ~/.xsession
% echo "exec /usr/local/bin/startkde" >> ~/.xsession
% chmod +x ~/.xsession
----

После запуска KDE дополнительную информацию о порядке использования её различных меню и приложений можно найти во встроенной системе помощи.

[[x11-wm-xfce]]
== XFce

Xfce является графической оболочкой, построенной на основе инструментального пакета GTK+, используемого в GNOME.
Однако она гораздо легче и реализует простой, эффективно работающий и лёгкий в использовании рабочий стол.
Она полностью настраиваема, имеет главную панель с меню, апплетами и кнопками быстрого запуска приложений, включает в себя менеджер файлов и звуковой менеджер, а также поддерживает темы рабочего стола.
Так как оболочка является быстродействующей, лёгкой и эффективной, она идеально подходит для более старых или медленных машин с ограниченной оперативной памятью.
Дополнительную информацию о Xfce можно найти на сайте link:http://www.xfce.org/[http://www.xfce.org].

Для установки пакета Xfce:
[source,shell]
----
# pkg install xfce
----

Либо для построения порта:

[source,shell]
----
# cd /usr/ports/x11-wm/xfce4
# make install clean
----

В отличие от GNOME или KDE, Xfce не имеет собственного менеджера регистрации.
Для того, чтобы запустить Xfce из командной строки, набрав `startx`, сначала добавьте соответствующую запись в [.filename]#~/.xinitrc#:

[source,shell]
----
% echo "exec /usr/local/bin/startxfce4 --with-ck-launch" > ~/.xinitrc
----

Альтернативным способом является использование XDM.
Для того, чтобы воспользоваться этим методом, создайте исполнимый файл [.filename]#~/.xsession#:

[source,shell]
----
% echo "#!/bin/sh" > ~/.xsession
% echo "exec /usr/local/bin/startxfce4 --with-ck-launch" >> ~/.xsession
% chmod +x ~/.xsession
----

[[x-compiz-fusion]]
== Установка Compiz Fusion

Одним из способов сделать работу с настольным компьютером более приятной является использование красивых 3D-эффектов.

Установить пакет Compiz Fusion легко, однако его настройка требует выполнения нескольких шагов, не описанных в документации к порту.

[[x-compiz-video-card]]
=== Настройка драйвера nVidia для FreeBSD

Эффекты на рабочем стале могут вызывать достаточно высокую нагрузку на графический адаптер.
Для обеспечения хорошей производительности графических адаптеров, основанных на решениях nVidia, требуется проприетарный драйвер.
Пользователи других графических адаптеров могут пропустить этот раздел и продолжить с этапа настройки [.filename]#xorg.conf#.

Для определения требуемого драйвера nVidia обратитесь к link:http://www.FreeBSD.org/ru/books/faq/x.html#idp59950544[вопросу FAQ по этой теме].

После определения корректного драйвера для использования с вашим адаптером его установка проста так же, как и установка любого другого пакета.

Например, для установки самой последней версии драйвера:

[source,shell]
....
# pkg install x11/nvidia-driver
....

Драйвер создаст модуль ядра, который должен быть загружен при запуске системы.
Добавьте следующую строку в файл [.filename]#/boot/loader.conf#:

[.programlisting]
....
nvidia_load="YES"
....

[NOTE]
====
Несмотря на то, что модуль ядра можно загрузить в работающее ядро немедленно при помощи команды типа `kldload nvidia`, следует отметить, что некоторые версии Xorg работают некорректно, если драйвер был загружен не во время запуска системы.
После редактирования файла [.filename]#/boot/loader.conf# рекомендуется выполнить перезагрузку.
====

При наличии загруженного модуля ядра, как правило, для включения проприетарного драйвера вам требуется изменить только одну строку в файле [.filename]#xorg.conf#:

Найдите следующую строку в файле [.filename]#/etc/X11/xorg.conf#:

[.programlisting]
....
Driver      "nv"
....

и замените её на:

[.programlisting]
....
Driver      "nvidia"
....

Запустите графический интерфейс обычным образом, и вы должны увидеть приветственную заставку от nVidia.
Всё должно работать в обычном режиме.

[[xorg-configuration]]
== Конфигурирование xorg.conf для получения эффектов на рабочем столе

Для активирования Compiz Fusion необходимо изменить файл [.filename]#/etc/X11/xorg.conf#:

Добавьте следующий раздел для включения эффектов композиций:

[.programlisting]
....
Section "Extensions"
    Option         "Composite" "Enable"
EndSection
....

Найдите раздел "Screen", который должен выглядеть похожим на текст ниже:

[.programlisting]
....
Section "Screen"
    Identifier     "Screen0"
    Device         "Card0"
    Monitor        "Monitor0"
    ...
....

и добавьте следующие две строки (они будут следовать за "Monitor"):

[.programlisting]
....
DefaultDepth    24
Option         "AddARGBGLXVisuals" "True"
....

Найдите подраздел "Subsection", указывающий на разрешение экрана, которое вы хотите использовать.
Например, если вы желаете использовать 1280x1024, поищите подраздел, приведённый ниже.
Если требуемого разрешения нет ни в одном подразделе, вы можете добавить соответствующую запись вручную:

[.programlisting]
....
SubSection     "Display"
    Viewport    0 0
    Modes      "1280x1024"
EndSubSection
....

Для настольных цветовых композиций требуется глубина цвета в 24 бита, измените подраздел выше на следующий:

[.programlisting]
....
SubSection     "Display"
    Viewport    0 0
    Depth       24
    Modes      "1280x1024"
EndSubSection
....

Наконец, убедитесь, что загрузка модулей "glx" и "extmod" отражена в разделе "Module":

[.programlisting]
....
Section "Module"
    Load           "extmod"
    Load           "glx"
    ...
....

Предыдущие действия могут быть выполнены в автоматизированном режиме при помощи пакета package:x11/nvidia-xconfig[] запуском (в режиме пользователя root):

[source,shell]
....
# nvidia-xconfig --add-argb-glx-visuals
# nvidia-xconfig --composite
# nvidia-xconfig --depth=24
....

[[compiz-fusion]]
=== Установка и настройка Compiz Fusion

Установить Compiz Fusion так же просто, как и любой другой пакет:

[source,shell]
....
# pkg install x11-wm/compiz-fusion
....

После завершения установки запустите ваше графическое окружение и в терминальном режиме введите следующие команды (в режиме обычного пользователя):

[source,shell]
....
% compiz --replace --sm-disable --ignore-desktop-hints ccp &amp;
% emerald --replace &
....

Ваш экран померцает в течение нескольких секунд, пока ваш менеджер окон (например, Metacity при использовании GNOME) заменяется на Compiz Fusion.
Приложение emerald берёт на себя оформление окон (то есть кнопки закрытия, минимизации и максимизации, заголовки и так далее).

Вы можете преобразовать это в тривиальный скрипт и настроить его автоматическое выполнение при запуске (к примеру, добавив его в "Sessions" рабочего стола GNOME:

[.programlisting]
....
#! /bin/sh
compiz --replace --sm-disable --ignore-desktop-hints ccp &
emerald --replace &
....

Сохраните его в вашем домашнем каталоге под именем, например, [.filename]#start-compiz# и сделайте файл исполняемым:

[source,shell]
....
% chmod +x ~/start-compiz
....

После этого воспользуйтесь GUI для добавления в меню [.guimenuitem]#Startup Programs# (находится в [.guimenuitem]#System#, [.guimenuitem]#Preferences#, [.guimenuitem]#Sessions# на рабочем столе GNOME).

Для реального выбора всех желаемых эффектов и их настроек запустите (снова в режиме обычного пользователя) Compiz Config Settings Manager:

[source,shell]
....
% ccsm
....

[NOTE]
====
В GNOME это можно также найти в меню [.guimenuitem]#System#, [.guimenuitem]#Preferences#.
====

Если при компиляции вы выбрали "gconf support", то вы также сможете просмотреть эти настройки при помощи `gconf-editor` из `apps/compiz`.

[[x11-understanding]]
== Устранение неполадок

Если мышь не работает, то для продолжения работы её необходимо настроить.
В последних версиях Xorg разделы `InputDevice` в файле [.filename]#xorg.conf# игнорируются в пользу автоматического обнаружения устройств.
Для того, чтобы вернуть старое поведение, добавьте следующую строку в раздел `ServerLayout` или `ServerFlags` этого файла:

[.programlisting]
....
Option "AutoAddDevices" "false"
....

После этого устройства ввода могут быть настроены так же, как в предыдущих версиях, вместе с другими необходимыми параметрами (например, определяющими переключение раскладок клавиатуры).

[NOTE]
====
Как было объяснено выше, по-умолчанию даемон hald будет пытаться распознать вашу клавиатуру автоматически.
Есть вероятность, что раскладка вашей клавиатуры или её модель будут определены некорректно.
Такие оболочки, как GNOME, KDE или Xfce, содержат собственные инструменты для настройки клавиатуры.
Тем не менее, можно задать параметры клавиатуры явным образом с помощью утилиты man:setxkbmap[1] или через правило настройки hald.

Например, если требуется использовать клавиатуру стандарта PC 102 с французской раскладкой, то необходимо создать конфигурационный файл клавиатуры для hald под названием [.filename]#x11-input.fdi# и сохранить его в каталоге [.filename]#/usr/local/etc/hal/fdi/policy#.
Этот файл должен содержать следующие строки:

[.programlisting]
....
<?xml version="1.0" encoding="iso-8859-1"?>
<deviceinfo version="0.2">
  <device>
    <match key="info.capabilities" contains="input.keyboard">
      <merge key="input.x11_options.XkbModel" type="string">pc102</merge>
      <merge key="input.x11_options.XkbLayout" type="string">fr</merge>
    </match>
  </device>
</deviceinfo>
....

Если этот файл уже существует, просто скопируйте и добавьте в ваш файл строки, относящиеся к настройке клавиатуры.

Вы должны будете перезагрузить систему, чтобы заставить hald применить настройки.

Есть возможность выполнить эту же самую настройку из X терминала или скрипта следующей командой:

[source,shell]
....
% setxkbmap -model pc102 -layout fr
....

В файле [.filename]#/usr/local/share/X11/xkb/rules/base.lst# перечислены различные клавиатуры, доступные раскладки и опции.
====

Теперь конфигурационный файл [.filename]#xorg.conf.new# может быть тонко настроен на ваш вкус.
Откройте этот файл в текстовом редакторе, таком, как man:emacs[1] или man:ee[1].
Если модель монитора устарела или является нестандартной и не поддерживает автоматическое определение частот развёртки, то эти параметры могут быть добавлены в раздел `"Monitor"` файла [.filename]#xorg.conf.new#:

[.programlisting]
....
Section "Monitor"
       Identifier   "Monitor0"
       VendorName   "Monitor Vendor"
       ModelName    "Monitor Model"
       HorizSync    30-107
       VertRefresh  48-120
EndSection
....

Большинство мониторов поддерживают автоопределение частоты развёртки, что делает ручной ввод этих значений ненужным.
Для незначительного количества мониторов, не поддерживающих автоматическое определение, следует избегать потенциальной поломки и указывать только значения, предоставленные производителем.

X позволяет использовать возможности технологии DPMS (Energy Star) с поддерживающими её мониторами.
Программа man:xset[1] управляет временными задержками и может явно задавать режимы ожидания, останова и выключения.
Если вы хотите включить использование возможностей DPMS вашего монитора, вы должны добавить следующую строку в раздел, описывающий монитор:

[.programlisting]
....
Option       "DPMS"
....

Пока файл конфигурации [.filename]#xorg.conf.new# открыт в редакторе, выберите желаемые разрешение и глубину цвета, которые будут использоваться по умолчанию.
Они задаются в разделе `"Screen"`:

[.programlisting]
....
Section "Screen"
       Identifier "Screen0"
       Device     "Card0"
       Monitor    "Monitor0"
       DefaultDepth 24
       SubSection "Display"
               Viewport  0 0
               Depth     24
               Modes     "1024x768"
       EndSubSection
EndSection
....

Ключевое слово `DefaultDepth` описывает глубину цвета, которая будет применяться по умолчанию.
Это значение может быть переопределено при помощи параметра командной строки `-depth` для man:Xorg[1].
Ключевое слово `Modes` описывает разрешение, с которым нужно работать при данной глубине цвета.
Заметьте, что поддерживаются только те стандартные режимы VESA, что определены графическим оборудованием настраиваемой системы.
В примере выше глубина цвета по умолчанию равна двадцати четырём битам на точку.
При такой глубине цвета принимается разрешение в 1024 на 768 точек.

Наконец, запишите конфигурационный файл и протестируйте его при помощи тестового режима, описанного выше.

[NOTE]
====
В процессе решения проблем вам могут помочь файлы протоколирования Xorg, в которых находится информация о каждом устройстве, к которому подключается сервер Xorg.
Протокольным файлам Xorg названия даются в формате [.filename]#/var/log/Xorg.0.log#.
Конкретное название файла протокола может варьироваться от [.filename]#Xorg.0.log# до [.filename]#Xorg.8.log# и далее.
====

Если всё в порядке, то конфигурационный файл нужно установить в обычное место, где его сможет найти man:Xorg[1].
Как правило, это [.filename]#/etc/X11/xorg.conf# или [.filename]#/usr/local/etc/X11/xorg.conf#.

[source,shell]
....
# cp xorg.conf.new /etc/X11/xorg.conf
....

Теперь процесс настройки Xorg завершён.
Xorg теперь можно запустить утилитой man:startx[1].
Сервер Xorg может быть также запущен при помощи man:xdm[1].

=== Конфигурирование при работе с графическими чипсетами Intel(R) `i810`

Конфигурирование при работе с интегрированными наборами микросхем Intel(R) i810 требует наличия [.filename]#agpgart#, программного интерфейса AGP, посредством которого Xorg будет управлять адаптером.
Подробности смотрите на странице справочника man:agp[4].

Это позволит конфигурировать графическое оборудование точно так же, как и любой другой графический адаптер.
Заметьте, что для систем, у которых драйвер man:agp[4] в ядро не вкомпилирован, попытка загрузить модуль с помощью man:kldload[8] не сработает.
Этот драйвер должен быть в ядре во время загрузки, либо вкомпилированным, либо подгруженным посредством [.filename]#/boot/loader.conf#.

=== Добавление широкоэкранной панели

Этот раздел предполагает наличие определённых глубоких познаний в настройке.
Если попытки применить описанные выше инструменты настройки к созданию рабочей конфигурации не приводят, в файлах протоколов достаточно информации для доведения конфигурации до рабочего состояния.
Для настройки необходимо использовать текстовый редактор.

Существующие широкоэкранные стандарты (WSXGA, WSXGA+, WUXGA, WXGA, WXGA+ и так далее) поддерживают форматы изображения 16:10 и 10:9, которые могут быть проблемными.
Для формата 16:10, например, возможны следующие разрешения экрана:

* 2560x1600
* 1920x1200
* 1680x1050
* 1440x900
* 1280x800

Это так же легко, как добавить одно из этих разрешений в качестве доступного режима (`Mode`) в раздел `Section "Screen"` следующим образом:

[.programlisting]
....
Section "Screen"
Identifier "Screen0"
Device     "Card0"
Monitor    "Monitor0"
DefaultDepth 24
SubSection "Display"
	Viewport  0 0
	Depth     24
	Modes     "1680x1050"
EndSubSection
EndSection
....

Xorg достаточно умён, чтобы получить информацию о разрешении от монитора посредством I2C/DDC, так что у него есть данные, какие частоты и разрешения может поддерживать монитор.

Если эти `ModeLine` не определены в драйверах, может потребоваться дополнительная настройка Xorg.
Используя [.filename]#/var/log/Xorg.0.log#, можно извлечь достаточно информации для создания работающей строки `ModeLine` в ручном режиме.
Просто поищите информацию, похожую на такую:

[.programlisting]
....
(II) MGA(0): Supported additional Video Mode:
(II) MGA(0): clock: 146.2 MHz   Image Size:  433 x 271 mm
(II) MGA(0): h_active: 1680  h_sync: 1784  h_sync_end 1960 h_blank_end 2240 h_border: 0
(II) MGA(0): v_active: 1050  v_sync: 1053  v_sync_end 1059 v_blanking: 1089 v_border: 0
(II) MGA(0): Ranges: V min: 48  V max: 85 Hz, H min: 30  H max: 94 kHz, PixClock max 170 MHz
....

Это так называемая информация EDID.
Создание `ModeLine` из этих данных является вопросом расположения значений в правильном порядке:
 
[.programlisting]
....
ModeLine <name> <clock> <4 horiz. timings> <4 vert. timings>
....

Таким образом, для данного примера `ModeLine` в разделе `Section "Monitor"` будет выглядеть примерно так:

[.programlisting]
....
Section "Monitor"
Identifier      "Monitor1"
VendorName      "Bigname"
ModelName       "BestModel"
ModeLine        "1680x1050" 146.2 1680 1784 1960 2240 1050 1053 1059 1089
Option          "DPMS"
EndSection
....

После завершения этих простых шагов по редактированию настроек X должны запуститься на вашем новом широкоэкранном мониторе.

[[compiz-troubleshooting]]
=== Устранение неполадок Compiz Fusion

[[no-decorations]]
==== Я установил Compiz Fusion, но после запуска указанных вами команд мои окна остались без заголовков и кнопок.  Что пошло не так?

Вероятно, не хватает настроек в файле [.filename]#/etc/X11/xorg.conf#.
Внимательно проанализируйте этот файл, уделив особенное внимание директивам `DefaultDepth` и `AddARGBGLXVisuals`.

[[xorg-crash]]
==== Когда я выполняю команду для запуска Compiz Fusion, X-сервер аварийно прекращает работу и я снова оказываюсь в режиме консоли.  В чём ошибка?

Если вы проанализируете файл [.filename]#/var/log/Xorg.0.log#, то, вероятно, найдёте сообщения об ошибках при запуске X.  Самыми частыми могут быть следующие:

[source,shell]
....
(EE) NVIDIA(0):     Failed to initialize the GLX module; please check in your X
(EE) NVIDIA(0):     log file that the GLX module has been loaded in your X
(EE) NVIDIA(0):     server, and that the module is the NVIDIA GLX module.  If
(EE) NVIDIA(0):     you continue to encounter problems, Please try
(EE) NVIDIA(0):     reinstalling the NVIDIA driver.
....

Эти сообщения, как правило, возникают при обновлении Xorg.  Вам потребуется переустановить пакет package:x11/nvidia-driver[], чтобы glx был построен снова.
