#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: head/ru_RU.KOI8-R/books/Makefile.inc 39534 2012-09-14 12:11:19Z gabor $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/Makefile.inc,v 1.3 2001/07/25 10:34:22 phantom Exp $
#
# Original revision: r9587
#

DESTDIR?=	${DOCDIR}/ru_RU.KOI8-R/books/${.CURDIR:T}
