#
# The FreeBSD Russian Documentation Project
#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: head/ru_RU.KOI8-R/books/handbook/x11/Makefile 39631 2012-10-01 09:53:01Z gabor $
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/x11/Makefile,v 1.1 2001/07/11 16:40:17 phantom Exp $
#
# Original revision: r9773
#

CHAPTERS= 	x11/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
