---
title: "Исправления и дополнения FreeBSD 14.4-RELEASE"
sidenav: download
---

:release: 14.4-RELEASE
:releaseNext: 14.5-RELEASE
:releaseBranch: 14-STABLE

= Исправления и дополнения FreeBSD {release}

== Аннотация

В этом документе перечислены исправления и дополнения для FreeBSD {release}, содержащие важную информацию, обнаруженную после выпуска или слишком поздно в цикле выпуска, чтобы быть включённой в документацию выпуска.
Эта информация включает рекомендации по безопасности, а также новости, связанные с программным обеспечением или документацией, которые могут повлиять на его работу или удобство использования.
Перед установкой этой версии FreeBSD всегда следует обращаться к актуальной версии этого документа.

Этот документ исправлений и дополнений для FreeBSD {release} будет поддерживаться до выхода FreeBSD {releaseNext}.

== Содержание

* <<intro,Введение>>
* <<security,Бюллетени безопасности>>
* <<errata,Уведомления об исправлениях>>
* <<open-issues,Открытые проблемы>>
* <<late-news,Последние новости>>

[[intro]]
== Введение

Этот документ исправлений и дополнений содержит «последние новости» о FreeBSD {release}.
Перед установкой этой версии важно ознакомиться с этим документом, чтобы узнать о любых обнаруженных после выпуска проблемах, которые, возможно, уже были найдены и исправлены.

Любая версия этого документа исправлений и дополнений, фактически распространяемая с выпуском (например, на диске CDROM), по определению будет устаревшей, но другие копии поддерживаются в актуальном состоянии в Интернете и должны рассматриваться как «текущие исправления» для этого выпуска.
Эти другие копии исправлений находятся по адресу https://www.FreeBSD.org/ru/releases/, а также на любых сайтах, которые поддерживают актуальные зеркала этого расположения.

Исходные и бинарные промежуточные сборки FreeBSD {releaseBranch} также содержат актуальные копии этого документа (на момент создания промежуточной сборки).

Список всех рекомендаций по безопасности FreeBSD CERT доступен по адресу https://www.FreeBSD.org/ru/security/.

[[security]]
== Уведомления безопасности

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Бюллетень |Дата |Тема
| link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:06.tcp.asc[FreeBSD-SA-26:06.tcp]
| 26 марта 2026
| TCP: возможность дистанционной DoS-атаки (утечка mbuf)
| link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:08.rpcsec_gss.asc[FreeBSD-SA-26:08.rpcsec_gss]
| 26 марта 2026
| Дистанционное выполнение кода через проверку корректности пакета в RPCSEC_GSS
| link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:09.pf.asc[FreeBSD-SA-26:09.pf]
| 26 марта 2026
| pf игнорирует определённые правила, не сообщая об этом
|===

[[errata]]
== Уведомления об исправлениях

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Исправление |Дата |Тема

|Нет исправлений.||

|===

[[open-issues]]
== Открытые проблемы

1. Команды **man:freebsd-update[8]**, такие как `fetch` или `install`, могут зависать, если man:pkg[8] не инициализирован в системе. +
**Обходной путь**: выполните man:pkg[8] для установки инструмента управления пакетами, затем снова используйте man:freebsd-update[8]. +
**Статус**: открыто - https://bugs.freebsd.org/293516 +

2. **man:loader_lua[8]** Регрессия в скриптах загрузчика приводит к выбору неправильного ядра, если /boot/kernel является символической ссылкой. +
**Обходной путь**: Отключите автоматическое определение ядра, добавив kernels_autodetect="NO" в [.filename]#/boot/loader.conf#. +
**Статус**: исправлено в ветке main - https://bugs.freebsd.org/293654 +

[[late-news]]
== Актуальные новости

Актуальных новостей нет.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (26.03.2026): 9ab94ece171524958a016bf547e9b67ccaf529ed
//
