#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD: head/ru_RU.KOI8-R/htdocs/Makefile.inc 38826 2012-05-17 19:12:14Z hrs $
# $FreeBSDru: frdp/www/ru/Makefile.inc,v 1.4 2000/11/10 17:04:45 phantom Exp $
#
# Original revision: 1.8
#

WEBBASE?=	/data/ru
DOC_PREFIX?=	${.CURDIR}/../../..
