//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (SVN): r53806
//

---
title: Глава 1. Введение
part: Часть I. Начало работы
prev: books/handbook/parti
next: books/handbook/install
showBookMenu: true
weight: 3
path: "/books/handbook/"
---

[[introduction]]
= Введение
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/introduction/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-synopsis]]
== Краткий обзор

Мы благодарим вас за интерес к FreeBSD! Следующая глава расскажет о некоторых аспектах Проекта FreeBSD, таких как её история, цели, модель разработки, и прочее.

Из этой главы вы узнаете:

* Какое отношение имеет FreeBSD к другим операционным системам.
* Историю Проекта FreeBSD.
* Цели Проекта FreeBSD.
* Основы модели разработки FreeBSD с открытыми исходными текстами.
* И, конечно, откуда появилось название "FreeBSD".

[[nutshell]]
== Добро пожаловать во FreeBSD!

FreeBSD является Unix-подобной операционной системой с открытым кодом, соответствующей стандартам и предназначенной для компьютеров x86 (32 и 64 разряда), ARM, AArch64, RISC-V, MIPS, POWER, PowerPC и Sun UltraSPARC(R). В неё включены все возможности, которые в наше время принимаются как должные, в частности, вытесняющая многозадачность, защита областей оперативной памяти, виртуальная память, многопользовательские сервисы, поддержка SMP, все инструменты разработки с открытым кодом для различных языков и фреймворков, а также функции рабочего стола, построенные на X Window System, KDE или GNOME. В частности, её сильные стороны таковы:

* _Неограничивающая лицензия открытого кода_, которая предоставляет вам права на свободную модификацию и расширение её исходного кода, а также его включение как в проекты с открытым кодом, так и продукты с закрытыми исходными текстами, не накладывая при этом ограничений, свойственных copyleft-лицензиям, и исключая потенциальные проблемы с несовместимостью лицензий.
* _Мощная поддержка TCP/IP_ - во FreeBSD реализованы стандартные отраслевые протоколы с улучшенными показателями производительности и масштабируемости. Это позволяет FreeBSD выступать как в роли сервера, так и маршрутизатора или межсетевого экрана, и на практике многие компании и поставщики решений используют её именно в данном качестве.
* _Полностью интегрированная поддержка OpenZFS_, в том числе размещение корневой файловой системы в ZFS, технология ZFS Boot Environments, обработка аварийных ситуаций, делегирование администрирования, поддержка изоляторов, специфичная для FreeBSD документация и поддержка на уровне утилиты установки системы.
* _Обширный набор функций обеспечения безопасности_, от фреймворка Mandatory Access Control до механизмов управления возможностями Capsicum и песочниц.
* _Более 30 тысяч готовых пакетов_ для всех поддерживаемых архитектур, а также Коллекция Портов, которая делает простым построение собственных адаптированных версий.
* _Документация_ - кроме Руководства и книг различных авторов, покрывающих темы от системного администрирования до внутреннего устройства ядра, имеются также страницы справочника &man.man.1;, посвящённые не только даемонам пользовательского уровня, утилитам и конфигурационным файлам, но также и API драйверов ядра (раздел 9) и отдельным драйверам (раздел 4).
* _Простая и непротиворечивая структура репозитория исходных текстов и система построения_ - FreeBSD использует единое хранилище для всех своих компонентов, как пользовательского уровня, так и уровня ядра. Это, вместе с унифицированной и легко изменяемой системой компиляции, а также хорошо продуманного процесса разработки, позволяет легко интегрировать FreeBSD в инфраструктуру построения вашего собственного продукта.
* _Приверженность настоящей философии Unix_, в которой предпочтение отдаётся возможностям гибкого комбинирования компонентов, а не созданию монолитных даемонов `всё в одном` с жёстко запрограммированным поведением.
* _Двоичная совместимость_ c Linux, которая делает возможным запуск многих готовых программ для Linux без необходимости применения виртуализации.

FreeBSD основана на релизе 4.4BSD-Lite, выпущенном командой Computer Systems Research Group (CSRG) Калифорнийского Университета в Беркли, и продолжает славную традицию разработки BSD-систем. В дополнении к прекрасной работе, предоставленной CSRG, Проект FreeBSD вложил многие тысячи человеко-часов в развитие функциональности и тонкую настройку системы для обеспечения максимальной производительности и надёжности в ситуациях реальной рабочей нагрузки. FreeBSD обеспечивает уровень производительности и надёжности, сопоставимый с другими решениям с открытым кодом и коммерческими решениями, вкупе с передовыми возможностями, недоступными более нигде.

[[os-overview]]
=== Что может делать FreeBSD?

Применение FreeBSD в действительности ограничено только вашим воображением. От разработки программного обеспечения до автоматизации производства, от складского учёта до дистанционной коррекции азимутов спутниковых антенн; если задачи можно решить с помощью коммерческих UNIX(R)-систем, скорее всего, они решаемы и с помощью FreeBSD! FreeBSD также существенно выигрывает за счёт буквально тысяч высококачественных приложений, разработанных исследовательскими центрами и университетами во всём мире и доступных по минимальной стоимости или бесплатно.

Поскольку исходные тексты FreeBSD общедоступны, система может быть оптимизирована в почти невероятной степени для специальных приложений или проектов, а это, обычно, невозможно при использовании операционных систем от большинства коммерческих производителей. Вот несколько примеров того, как сейчас используется FreeBSD:

* _Интернет-службы:_ мощнейший TCP/IP стек делает FreeBSD идеальной платформой для большинства Интернет-приложений, таких как:

** Веб-серверы
** Маршрутизация IPv4 и IPv6
** Межсетевые экраны (firewalls) и шлюзы NAT ("IP-маскарадинг")
** FTP-серверы
** Почтовые серверы
** и многое другое...

* _Образование:_ Вы студент и ваше образование связано с информационными технологиями или похожими инженерными дисциплинами? Нет лучшего пути начать изучение операционных систем, компьютерной архитектуры и сетевых технологий, чем практические освоение их скрытой механики, которое доступно во FreeBSD. Количество свободно доступных пакетов САПР, математических и графических пакетов также делают её чрезвычайно полезной для тех, кто использует компьютер как инструмент для выполнения _другой_ работы!
* _Исследования:_ За счёт доступности исходных текстов для всей системы, FreeBSD - превосходная платформа как для изучения операционных систем и исследований в других областях компьютерных наук. Свободная природа FreeBSD позволяет удалённым группам сотрудничать, обмениваться идеями и совместными разработками, не беспокоясь о наличии специальных лицензий или ограничений на то, что может обсуждаться в открытых форумах.
* _Работа в сети:_ Нужен новый маршрутизатор? Сервер имён (DNS)? Межсетевой экран, защищающий от проникновения извне в вашу сеть? FreeBSD может легко превратить стоящий в углу и давно не использующийся ПК в современный маршрутизатор с продвинутыми возможностями фильтрации пакетов.
* _Встраиваемые решения:_ FreeBSD является прекрасной платформой для построения встраиваемых систем на её основе. С поддержкой архитектур ARM(R), MIPS и PowerPC, дополненной надёжным стеком сетевых технологий, передовыми возможностями и link:{faq}#bsd-license-restrictions[разрешающей лицензией], FreeBSD является прекрасной основой для построения встраиваемых маршрутизаторов, межсетевых экранов и других устройств.
* _Рабочая станция:_ FreeBSD является прекрасным выбором, если вам нужен недорогая рабочая станция, использующая свободно распространяемый сервер X11. FreeBSD ппозволяет сделать выбор между многими свободно распространяемыми оболочками рабочего стола, включая стандартные графические оболочки GNOME и KDE. FreeBSD может даже загружаться в "бездисковом" режиме с центрального сервера, что делает рабочую станцию ещё дешевле и проще в администрировании.
* _Разработка программного обеспечения:_ Базовая поставка FreeBSD распространяется с полным набором инструментов для разработки, включая полный инструментальный пакет компилятора и отладчика C/C++. Имеется поддержка многих других языков посредством коллекции портов и пакетов.

FreeBSD доступна к скачиванию без дополнительной оплаты, либо её можно получить на CD-ROM или DVD. Подробнее о том, как получить FreeBSD, см. в crossref:mirrors[mirrors, Получение FreeBSD].

[[introduction-nutshell-users]]
=== Кто использует FreeBSD?

FreeBSD известна своими возможностями по обеспечению работы веб-серверов, и в списке тех, что используют FreeBSD, можно найти
link:https://news.ycombinator.com/[Hacker News],
link:http://www.netcraft.com/[Netcraft],
link:http://www.163.com/[NetEase],
link:https://signup.netflix.com/openconnect[Netflix],
link:http://www.sina.com/[Sina],
link:http://www.sony.co.jp/[Sony Japan],
link:http://www.rambler.ru/[Rambler],
link:http://www.yahoo.com/[Yahoo!] и
link:http://www.yandex.ru/[Yandex].

Передовые возможности FreeBSD, признанная безопасность, предсказуемый цикл выпуска версий и неограничивающей лицензией способствовали её использованию в качестве платформы для построения многих готовых решений, устройств и продуктов, как коммерческих, так и открытых. FreeBSD используется многими крупнейшими ИТ-компаниями мира:

* http://www.apache.org/[Apache] - Публично доступная инфраструктура The Apache Software Foundation, включая, возможно, один из самых крупных репозиториев SVN в мире с более чем 1,4 миллионами коммитов, большей частью работает под управлением FreeBSD.
* http://www.apple.com/[Apple] - OS X очень многое взяла из FreeBSD в части сетевого стека, виртуальной файловой системы и многих пользовательских компонентов. Apple iOS также содержит элементы, позаимствованные из FreeBSD.
* http://www.cisco.com/[Cisco]  - Готовые решения IronPort в области сетевой безопасности и защиты от спама работают под управлением модифицированной версии ядра FreeBSD.
* http://www.citrix.com/[Citrix] - Линейка готовых решений в области безопасности NetScaler реализует функции балансировки нагрузки на уровнях 4-7, кэширования контента, межсетевого экрана для приложений, защищённого VPN и мобильного доступа к сетевым облакам, вместе со всей мощью оболочки FreeBSD.
* https://www.emc.com/isilon[Dell EMC Isilon] - Устройства Isilon для организации корпоративных систем хранения базируются на FreeBSD. Чрезвычайно либеральная лицензия FreeBSD позволила Isilon интегрировать собственные результаты интеллектуальной деятельности в ядро и сфокусироваться на создании продукта, а не операционной системы.
* http://www.quest.com/KACE[Quest KACE] - Устройства управления системами KACE работают под управлением FreeBSD ввиду её надёжности, масштабируемости и наличия сообщества, поддерживающего её развитие.
* http://www.ixsystems.com/[iXsystems] - Линейка унифицированных устройств хранения данных основана на FreeBSD. Кроме собственных коммерческих продуктов, iXsystems также управляет разработкой проектов с открытым кодом TrueOS и FreeNAS.
* http://www.juniper.net/[Juniper] - Операционная система JunOS, управляющая всеми сетевыми устройствами Juniper (в том числе маршрутизаторами, коммутаторами, сетевыми продуктами и продуктами обеспечения безопасности) основана на FreeBSD. Juniper является одним из многих вендоров, демонстрирующих взаимовыгодные отношения между проектом и поставщиком коммерческих продуктов. Улучшения, создаваемые в Juniper, передаются во FreeBSD для того, чтобы в будущем снизить сложность интеграции новых возможностей FreeBSD обратно в JunOS.
* http://www.mcafee.com/[McAfee] - SecurOS, основа корпоративных межсетевых экранов, в том числе Sidewinder, базируется на FreeBSD.
* http://www.netapp.com/[NetApp] - Линейка устройств хранения Data ONTAP GX основана на FreeBSD. Кроме того, NetApp передал во FreeBSD много новых функций, в том числе bhyve, новый гипервизор с лицензией BSD.
* http://www.netflix.com/[Netflix] - Устройство OpenConnect, которое используется Netflix для трансляции фильмов своим подписчикам, основано на FreeBSD.  Netflix внесла существенный вклад в код и работы, направленные на поддержание нулевых отличий от основной ветки FreeBSD. Через устройства Netflix OpenConnect обеспечивается доставка более чем 32% всего трафика Интернет в Северной Америке.
* http://www.sandvine.com/[Sandvine] - Sandvine использует FreeBSD в качестве основы для своих высокопроизводительных платформ обработки сетевого трафика реального времени, являющихся ядром их продуктов интеллектуального контроля сетевых политик.
* http://www.sony.com/[Sony] - Игровая консоль PlayStation 4 работает под управлением модифицированной версии FreeBSD.
* http://www.sophos.com/[Sophos] - Продукт Sophos Email Appliance, основанный на защищённом варианте FreeBSD, предназначен для сканирования входящей почты на предмет спама и вирусов с одновременным мониторингом исходящей почты на наличие вредоносных программ и случайных утечек чувствительной информации.
* http://www.spectralogic.com/[Spectra Logic] - Линейка устройств хранения данных архивного класса nTier использует FreeBSD и OpenZFS.
* https://www.stormshield.eu[Stormshield] - Устройства Stormshield Network Security построены на версии FreeBSD с усиленной защитой.  Лицензия BSD позволяет им интегрировать их результаты интеллектуальной деятельности в систему, одновременно с этим делясь большим количеством интересных разработок с сообществом.
* http://www.weather.com/[The Weather Channel] - Устройство IntelliStar, устанавливаемое в головном узле каждого местного оператора кабельного телевидения, отвечает за включение местного прогноза погоды в расписание передач телеканалов и работает под управлением FreeBSD.
* http://www.verisign.com/[Verisign] - Verisign отвечает за работу регистров корневых доменов .com и .net, а также соответствующей инфраструктуры DNS. Они опираются на несколько различных сетевых операционных систем, в том числе FreeBSD, чтобы гарантировать отсутствие единой точки отказа в их инфраструктуре.
* http://www.voxer.com/[Voxer] - Мобильная платформа голосовых сообщений Voxer использует ZFS на FreeBSD.  Voxer перешла с системы, основанной на Solaris, на FreeBSD ввиду её отличного документации, более крупного и более активного сообщества, а также системного окружения, удобного разработчикам.  Дополнительно к таким критически важным функциям, как ZFS и DTrace, FreeBSD также обеспечивает поддержку TRIM для ZFS.
* https://fudosecurity.com/en/[Fudo Security] - Устройство защиты FUDO позволяет компаниям выполнять мониторинг, управление, запись и аудит контрагентов и администраторов, работающих в их системах. Оно применяет самые лучшие технологии защиты FreeBSD, в том числе ZFS, GELI, Capsicum, HAST и auditdistd.

FreeBSD также породила определённое количество связанных проектов с открытым кодом:

* http://bsdrp.net/[BSD Router] - Замена больших корпоративных маршрутизаторов, основанная на FreeBSD и спроектированная для работы на стандарных ПК.

* http://www.freenas.org/[FreeNAS] - Модифицированная FreeBSD, спроектированная для использования в качестве отдельного устройства, выступающего в роли сетевого файлового сервера. Имеет веб-интерфейс, построенный на python для упрощения управления как файловыми системами UFS, так и ZFS. Поддерживает NFS, SMB/CIFS, AFP, FTP и iSCSI. Включает в себя расширяемую систему плагинов, основанную на технологии изоляторов FreeBSD.

* https://ghostbsd.org/[GhostBSD] - основана на FreeBSD, использует парадигму GTK для создания красивой оболочки и обеспечения удобной работы с современной платформой BSD, предоставляющей естественное и оригинальное рабочее окружение Unix.

* http://mfsbsd.vx.sk/[mfsBSD] - Набор инструментов для построения образа FreeBSD, который работает полностью в оперативной памяти.

* http://www.nas4free.org/[NAS4Free] - Дистрибутив файлового сервера, основанного на FreeBSD c веб-интерфейсом, построенным на PHP.

* http://www.opnsense.org/[OPNSense] - OPNsense является простой в использовании и проектировании платформой для маршрутизации и межсетевого экранирования с открытым исходным кодом, основанной на FreeBSD. OPNsense содержит большинство возможностей, доступных в дорогих коммерческих межсетевых экранах, а во многих случаях их больше. Она обеспечивает богатый набор функций, присущих коммерческим решениям, сочетающийся с достоинствами открытого и верифицируемого исходного кода.

* http://www.trueos.org/[TrueOS] - TrueOS базируется на легендарной безопасности и стабильности FreeBSD. TrueOS соответствует FreeBSD-CURRENT, включая самые последние драйверы, обновления системы безопасности и пакетов.

* https://www.furybsd.org[FuryBSD] - является совершенно новым решением для рабочего стола FreeBSD с открытым кодом. FuryBSD отдаёт дань уважения проектам создания рабочих столов BSD прошлого, таким, как PC-BSD и TrueOS с их графическим интерфейсом, и включает дополнительные инструменты, подобные "живому" гибридному образу USB/DVD. FuryBSD полностью свободна для использования и распространения с лицензией BSD.

* https://www.midnightbsd.org[MidnightBSD] - является операционной системой, оснвоанной на FreeBSD и ориентированной на пользователей рабочих станций.  В неё включено всё программное обеспечение, которое вы бы ожидали для выполнения ежедневных задач: работа с электронной почтой, веб-сайтами, документами, игры и много больше сверх перечисленного.

* http://www.pfsense.org/[pfSense] - Дистрибутив межсетевого экрана, основанного на FreeBSD, с огромным набором функций и расширенной поддержкой IPv6.

* http://zrouter.org/[ZRouter] - Альтернативное микропрограммное обеспечение с открытым кодом для встраиваемых устройств, основанное на FreeBSD. Разработано для того, чтобы заменить закрытое микропрограммное обеспечение в стандартных маршрутизаторах.

На сайте Фонда FreeBSD можно найти список link:https://www.freebsdfoundation.org/about/testimonials/[отзывов от компаний, чьи продукты и сервисы основаны на FreeBSD].
В Wikipedia также ведётся link:https://en.wikipedia.org/wiki/List_of_products_based_on_FreeBSD[список решений, основанных на FreeBSD].

[[history]]
== О Проекте FreeBSD

В следующей части рассказывается о том, что из себя представляет проект, включая краткую историю, цели проекта и модель разработки проекта.

[[intro-history]]
=== Краткая история FreeBSD

Проект FreeBSD возник в начале 1993 года, частично как результат развития неофициального комплекта исправлений к 386BSD (Unofficial 386BSDPatchkit) последними тремя координаторами этой активности, которыми являлись Нэйт Уильямс (Nate Williams), Rod Grimes (Род Граймс) и Jordan Hubbard (Джордан Хаббард).

Изначальной задачей был выпуск промежуточной версии 386BSD, призванной исправить множество проблем, которые механизм patchkit (набор исправлений) не мог решить. Ранним рабочим названием этого проекта, указывающим на этот факт, было 386BSD 0.5 или 386BSD Interim.

386BSD была операционной системой Билла Джолитца, которая на тот момент сильно страдала от почти годичного пренебрежения к ней автора. Так как patchkit с каждым днём разрастался всё более и более непозволительно, они решили помочь Биллу, предоставив этот промежуточный "очистительный" снимок состояния системы. Эти планы были грубо разрушены, когда Билл внезапно решил прекратить поддержку проекта без каких-либо ясных комментариев, что должно быть сделано.

Троица полагала, что цель оставалась стоящей даже без поддержки Билла, и они приняли имя "FreeBSD", придуманное Дэвидом Гринмэном. Начальные цели были определены после консультаций с пользователями существовавшей системы, и как только стало понятно, что проект на пути к тому, чтобы стать реальностью, Джордан связался с компанией Walnut Creek CDROM и поделился идеями о путях последующего улучшения каналов распространения FreeBSD для множества пользователей без доступа к Internet. Компания Walnut Creek CDROM не только поддержала идею распространения FreeBSD на CD, но ещё и предоставила проекту компьютер для работы и быстрый доступ к Интернету. Без почти беспрецедентной веры Walnut Creek CDROM в этот, в то время, полностью неизвестный проект, вряд ли FreeBSD зашла бы так далеко и так быстро, как сегодня.

Первым дистрибутивом, распространяемым как на CD-ROM, так и в сети, стала FreeBSD 1.0, выпущенная в декабре 1993 года. Эта версия была выполнена на основе ленты 4.3BSD-Lite ("Net/2") из Калифорнийского Университета в Беркли, с многочисленными добавлениями из проекта 386BSD и Фонда Свободного Программного Обеспечения. Это был довольно внушительный успех для первой попытки, и они закрепили его выпуском FreeBSD 1.1 RELEASE в мае 1994 года.

В это же время, на горизонте сгустились тучи в связи с назревающим скандалом между Novell и Калифорнийским Университетом, Беркли. Это был вялотекущий судебный процесс о легальности версии Net/2 из Беркли. По условиям достигнутого соглашения, Калифорнийский Университет признавал, что большие куски Net/2 были "унаследованным" кодом, права на который принадлежат компании Novell, которая, в свою очередь, приобрела эти права ранее у AT&T. Взамен Беркли получил "благословение" Novell на то, что версия 4.4BSD-Lite после её выхода будет объявлена полностью "свободной", а всем пользователям Net/2 будет настоятельно рекомендовано перейти на неё. Это также касалось FreeBSD, и проекту было дано время до конца июля 1994 года для прекращения распространения его продукта, базирующегося на Net/2. На этих условиях проекту было разрешено выпустить последний релиз до окончания срока, и это была FreeBSD 1.1.5.1.

Тогда проект FreeBSD приступил к сложнейшей задаче буквально пересоздания с нуля на основе абсолютно новой и довольно неполной системы 4.4BSD-Lite. Версии "Lite" были в прямом смысле light (лёгкими) отчасти потому, что группа CSRG удалила большие куски кода, необходимого для создания реально загружающейся системы (по причине различных лицензионных требований), и фактически порт 4.4BSD для платформы Intel был очень неполным. Проекту потребовалось время почти до ноября 1994 года для того, чтобы выполнить этот переход, а в декабре 1994 года в мир была выпущена FreeBSD 2.0. Несмотря на множество "острых углов" в этой версии, она пользовалась значительным успехом и была продолжена более устойчивой и простой в установке FreeBSD 2.0.5, выпущенной в июне 1995 года.

С того времени было выпущена серия релизов FreeBSD, с каждым разом улучшающих её стабильность, быстродействие и набор возможностей по сравнению с предыдущими версиями.

На данный момент долгосрочные активности по разработке продолжаются в ветке 10.X-CURRENT, а промежуточные релизы версии 10.X постоянно размещаются на link:ftp://ftp.FreeBSD.org/pub/FreeBSD/snapshots/[сервере промежуточных релизов] по мере выполнения работ.

[[goals]]
=== Цели Проекта FreeBSD

Целью Проекта FreeBSD является предоставление программного обеспечения, которое может быть использовано для любых целей и без дополнительных ограничений. Многие из нас внесли значительный вклад в код (и проект) и совершенно не против получать за это иногда финансовую компенсацию, но мы определенно не собираемся ее требовать. Мы верим, что первая и основная наша "миссия" это предоставление кода для всех, кому он необходим, и для любых целей, так чтобы этот код становился всё более распространённым и предоставлял самые широкие возможности. Это, я верю, является одной из наиболее фундаментальных целей Свободного Программного Обеспечения, и мы с энтузиазмом поддерживаем её.

Тот код в нашем дереве исходных текстов, который попадает под Стандартную Общественную Лицензию GNU (GPL) или Стандартную Общественную Лицензию Ограниченного Применения GNU (LGPL), предоставляется с дополнительными условиями, хотя они обеспечивают только возможность доступа, а не его ограничение. По причине дополнительных сложностей, которые могут появится при коммерческом использовании GPL-продуктов, мы предпочитаем ПО, предоставленное под более свободной лицензией BSD, когда это возможно.

[[development]]
=== Модель Разработки FreeBSD

Разработка FreeBSD - это очень открытый и гибкий процесс. FreeBSD в буквальном смысле создана из кода, предоставленного тысячами людей со всего мира, в чём вы можете убедиться, взглянув на extref:{contributors}[список этих людей]. Инфраструктура разработки FreeBSD позволяет этим тысячам контрибуторов сотрудничать с помощью Интернета. Мы постоянно ищем новых разработчиков и новые идеи, и те, кто заинтересован в более тесном взаимодействии и хочет принять участие в проекте, должны просто связаться с нами в рассылке link:{freebsd-hackers-url}[freebsd-hackers]. Для тех, кто желает уведомить других пользователей FreeBSD об основных направлениях работы, доступен {freebsd-announce}.

Для независимой работы или тесного сотрудничества, полезно знать о проекте и процессе разработки FreeBSD следующее:

Репозитории SVN[[development-cvs-repository]]::
В течение нескольких лет основное дерево исходных текстов FreeBSD поддерживалось с помощью link:http://www.nongnu.org/cvs/[CVS] (Concurrent Versions System), свободно распространяемой системы управления исходным кодом. В июне 2008 года Проект перешёл на использование link:https://subversion.apache.org/[SVN] (Subversion).  Переключение признавалось неизбежным, так как технические ограничения, накладываемые CVS, становились всё более очевидными ввиду быстрого расширения дерева исходного кода и размера уже сохранённой истории.  Репозитории Проекта документирования и Коллекции портов также были переведены с CVS на SVN в мае и июле 2012 года, соответственно.  Пожалуйста, обратитесь к разделу crossref:cutting-edge[synching,Синхронизация дерева исходных текстов] для получения дополнительной информации о том, как получить хранилище `src/` FreeBSD, и разделу crossref:ports[ports-using,Использование Коллекции портов] для уточнения подробностей о получении Коллекции портов FreeBSD.

Список коммиттеров[[development-committers]]::
_Коммиттеры_ - это люди, которые имеют права на _запись_ в дереве Subversion и авторизованы на внесение изменений в исходный код FreeBSD (термин "коммиттер" произошёл от команды управления исходным кодом `commit`, используемой для сохранения новых изменений в репозитории). Кто угодно может отправить сообщение об ошибке в link:https://bugs.FreeBSD.org/submit/[Базу данных об ошибках]. До отправки сообщения об ошибке можно воспользоваться списками рассылки FreeBSD, каналами IRC или форумами, которые могут помочь удостовериться в том, что проблема действительно является ошибкой.

Core-группа FreeBSD [[development-core]]::
_Core-группа FreeBSD_ могла бы быть эквивалентом Совета Директоров, если бы Проект FreeBSD был компанией. Главная задача Core-группы - гарантировать, что проект в целом в хорошем состоянии и движется в правильном направлении. Приглашение постоянных и ответственных разработчиков присоединиться к группе коммиттеров - одна из функций Core-группы, так же, как и приглашение новых членов в Core-группу по мере того, как другие уходят. Нынешний состав команды был выбран из рядов коммиттеров путем общего голосования в июле 2018 года. Выборы проходят каждые 2 года.
+
[NOTE]
====
Как и большинство разработчиков, большинство из членов Core-группы являются добровольными участниками процесса разработки, не получающими никакой финансовой выгоды от участия в проекте, поэтому вы не должны рассматривать возложенную на них "ответственность" как "гарантированную поддержку". Аналогия с "советом директоров" не очень точна и, вероятно, гораздо правильнее будет сказать, что это люди, которые посвятили себя FreeBSD, хотя и достойны лучшей участи!
====

Внешняя помощь::
Последней, но однозначно не менее значимой, и наибольшей группой разработчиков являются сами пользователи, которые предоставляют комментарии и исправления ошибок нам на почти постоянной основе. Основной путь участвовать в не централизованной разработке - это подписка на {freebsd-hackers}, где обсуждаются подобные вещи. Обратитесь к crossref:eresources[eresources, Ресурсы в интернет] за дальнейшей информацией о различных списках рассылки FreeBSD.
+
extref:{contributors}[Список участников проекта FreeBSD] очень длинный и постоянно растет, так почему бы вам не присоединится к нему, предоставив что-нибудь проекту FreeBSD сегодня?
+
Предоставление кода - не единственный способ помочь проекту; более полный список того, что необходимо сделать, можно найти на link:https://www.FreeBSD.org/ru/[Web-сайте проекта FreeBSD].

Вообще говоря, наша модель разработки организована как "нечеткий набор концентрированных колец". Централизованная модель разработана для удобства _пользователей_ FreeBSD, которые получают простую систему контроля за одной центральной базой кода, и позволяет не оставить за бортом проекта потенциальных помощников! Мы желаем предоставить стабильную операционную систему с большим количеством согласованных crossref:ports[ports,прикладных программ], которые пользователи смогут легко установить и использовать - наша модель очень хорошо подходит для решения этой задачи.

Всё, что мы просим от желающих присоединится к нам как разработчики, - хотя бы часть той преданности постоянному успеху FreeBSD, которой отличаются нынешние разработчики!

[[third-party-programs]]
=== Программное обеспечение сторонних разработчиков

В дополнение к базовой системе, FreeBSD предоставляет коллекцию портированого ПО, включающую тысячи популярных программ. На момент написания этого текста в ней было более {numports} портов! Список портированных приложений варьируется от серверов http до игр, языков программирования, текстовых редакторов и всего прочего. Полная Коллекция Портов требует приблизительно {ports-size} дискового пространства. Для компиляции приложения необходимо всего лишь перейти в каталог программы, которую вы хотите установить, набрать `make install` и дать системе сделать всю остальную работу. Полные исходные тексты для каждого порта, который вы устанавливаете, загружаются автоматически, поэтому вам нужно только дисковое пространство для сборки необходимых портов. Почти каждый порт предоставляется также как скомпилированный "пакет", который может быть установлен с помощью простой команды (`pkg install`) теми, кто предпочитает не компилировать порты из исходных текстов. Дополнительная информация о пакетах и портах находится в crossref:ports[ports, Установка приложений. порты и пакеты].

=== Дополнительная документация

Все поддерживаемые версии FreeBSD предоставляют возможность указать программе установки на копирование дополнительной документации в каталог [.filename]#/usr/local/share/doc/freebsd# во время первичной настройки системы.
Также документация может быть установлена в любой момент позже при помощи пакетов, как описано в <<doc-ports-install-package>>.
Вы можете просматривать локально установленные документы с помощью любого браузера, поддерживающего HTML, используя следующие ссылки:

Руководство FreeBSD::
link:file://localhost/usr/local/share/doc/freebsd/handbook/index.html[/usr/local/share/doc/freebsd/handbook/index.html]

FreeBSD FAQ (Часто задаваемые вопросы)::
link:file://localhost/usr/local/share/doc/freebsd/faq/index.html[/usr/local/share/doc/freebsd/faq/index.html]

Вы также можете просмотреть основные (и наиболее часто обновляемые) копии на https://www.FreeBSD.org/ru/[https://www.FreeBSD.org/ru/].
