//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (SVN): r42186
//

---
title: Глава 1. Введение
part: Часть I. Начало работы
prev: books/handbook/parti
next: books/handbook/install
showBookMenu: true
weight: 3
path: "/books/handbook/"
---

[[introduction]]
= Введение
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/introduction/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-synopsis]]
== Краткий обзор

Мы благодарим вас за интерес к FreeBSD! Следующая глава расскажет о некоторых аспектах Проекта FreeBSD, таких как её история, цели, модель разработки, и прочее.

Из этой главы вы узнаете:

* Какое отношение имеет FreeBSD к другим операционным системам.
* Историю Проекта FreeBSD.
* Цели Проекта FreeBSD.
* Основы модели разработки FreeBSD с открытыми исходными текстами.
* И, конечно, откуда появилось название "FreeBSD".

[[nutshell]]
== Добро пожаловать во FreeBSD!

FreeBSD - это операционная система, основанная на 4.4BSD-Lite и предназначенная для компьютеров Intel (x86 и Itanium(R)), AMD64 и Sun UltraSPARC(R). Ведётся работа по портированию и на другие архитектуры. Вы можете также прочесть об <<history,истории FreeBSD>>, или о <<relnotes,текущем релизе>>. Если вы заинтересованы в помощи проекту (разработками, оборудованием, финансированием), прочтите статью extref:{contributing}[Помощь FreeBSD].

=== Что может FreeBSD?

FreeBSD имеет заслуживающие внимания возможности. Некоторые из них:

* _Вытесняющая многозадачность_ с динамическим регулированием приоритетов, позволяющая плавно и справедливо распределить ресурсы компьютера между приложениями и пользователями, даже при тяжелейших нагрузках. 
* _Поддержка многопользовательской работы_, которая позволяет множеству людей использовать FreeBSD совместно для различных задач. Это значит, например, что системная периферия, такая как принтеры и ленточные устройства, правильно разделяется всеми пользователями в системе или сети, и что пользователям или группам пользователей могут быть установлены лимиты каждого ресурса, защищая критические системные ресурсы от перегрузок.
* Мощный _TCP/IP-стек_ с поддержкой таких промышленных стандартов, как SCTP, DHCP, NFS, NIS, PPP, SLIP, IPsec и IPv6. Это означает, что FreeBSD может легко взаимодействовать с другими системами, а также работать сервером масштаба предприятия, предоставляя жизненно важные функции, такие как NFS (удалённый доступ к файлам) и услуги электронной почты, или представить вашу организацию в Интернете, обеспечивая работу служб WWW, FTP, маршрутизацию и функции межсетевого экрана.
* _Защита памяти_ гарантирует, что приложения (или пользователи) не смогут чинить препятствия друг другу. Фатальная ошибка в выполнении одного приложения не скажется на работоспособности всей системы.
* Промышленный стандарт _X Window System_ (X11R7) обеспечивает графический интерфейс пользователя (GUI) для большинства VGA карт и мониторов, и поставляется с полным исходным кодом.
* _Двоичная совместимость_ с большинством программ, созданных для Linux, SCO, SVR4, BSDI и NetBSD.
* Тысячи _готовых к использованию_ приложений доступны из коллекций _портов_ и _пакетов_ FreeBSD. Зачем искать что-то в сети, когда вы можете найти всё прямо здесь?
* Тысячи других _легко адаптируемых_ приложений доступны в Интернете. FreeBSD совместима по исходным текстам с большинством популярных коммерческих UNIX(R)-систем и, таким образом, большинство приложений требуют лишь небольших изменений для сборки (или не требуют вообще).
* _Виртуальная память_ с поддержкой сброса неиспользуемых страниц по требованию и "объединение виртуальной памяти и буферного кэша" спроектированы так, чтобы максимально эффективно удовлетворить приложения с огромными аппетитами к памяти и, в то же время, сохранить интерактивность для остальных пользователей.
* Поддержка _симметричной многопроцессорности_ (SMP) для машин с несколькими процессорами.
* Полный комплект инструментов разработки для _C_ и _C++_. Множество дополнительных языков программирования для исследований и разработки также доступны из коллекций портов и пакетов.
* Доступность _исходных текстов_ всей системы означает, что вы имеете максимальный контроль над операционной средой. Зачем выбирать закрытые решения и уповать на милость производителя, когда вы можете получить по-настоящему открытую систему?
* Обширная _online-документация_.
* _И многое-многое другое!_

FreeBSD основана на 4.4BSD-Lite от Computer Systems Research Group (CSRG) Калифорнийского Университета, Беркли, и продолжает славную традицию разработки BSD-систем. В дополнении к прекрасной работе, предоставленной CSRG, Проект FreeBSD тратит многие тысячи часов для тонкой настройки системы для максимальной производительности и надёжности в условиях максимально приближенным к "боевым". Когда большинство коммерческих гигантов только пытаются достичь такого уровня возможностей, производительности и надежности операционных систем для ПК, FreeBSD может предложить все это прямо _сейчас_!

Применение FreeBSD в действительности ограничено только вашим воображением. От разработки программного обеспечения до автоматизации производства, от складского учета до дистанционной коррекции азимутов спутниковых антенн; если задачи можно решить с помощью коммерческих UNIX(R)-систем, скорее всего, они решаемы и с помощью FreeBSD! FreeBSD также существенно выигрывает за счет буквально тысяч высококачественных приложений, разработанных исследовательскими центрами и университетами во всём мире, и доступных за минимальную цену или даже бесплатно. Коммерческие приложения также доступны, и их с каждым днем становится всё больше.

Поскольку исходные тексты FreeBSD общедоступны, система может быть оптимизирована в почти невероятной степени для специальных приложений или проектов, а это, обычно, невозможно при использовании операционных систем от большинства коммерческих производителей. Вот несколько примеров того, как сейчас используется FreeBSD:

* _Интернет-службы:_ мощнейший TCP/IP стек делает FreeBSD идеальной платформой для большинства Интернет-приложений, таких как:

** FTP-серверы
** Серверы World Wide Web (как стандартные, так и защищённые [SSL])
** Маршрутизация IPv4 и IPv6
** Межсетевые экраны (firewalls) и шлюзы NAT ("IP-маскарадинг")
** Серверы электронной почты
** Серверы новостей или дискуссионных групп USENET
** и многое другое...
+
Вы можете начать своё знакомство с FreeBSD, используя недорогой ПК класса 386, а впоследствии увеличить её мощь до сервера масштаба предприятия с четырьмя процессорами Xeon и RAID контроллером.
* _Образование:_ Вы студент и ваше образование связано с информационными технологиями или похожими инженерными дисциплинами? Нет лучшего пути начать изучение операционных систем, компьютерной архитектуры и сетевых технологий, чем практические освоение их скрытой механики, которое доступно во FreeBSD. Количество свободно доступных пакетов САПР, математических и графических пакетов также делают её чрезвычайно полезной для тех, кто использует компьютер как инструмент для выполнения _другой_ работы!
* _Исследования:_ За счёт доступности исходных текстов для всей системы, FreeBSD - превосходная платформа как для изучения операционных систем и исследований в других областях компьютерных наук. Свободная природа FreeBSD позволяет удалённым группам сотрудничать, обмениваться идеями и совместными разработками, не беспокоясь о наличии специальных лицензий или ограничений на то, что может обсуждаться в открытых форумах.
* _Работа в сети:_ Нужен новый маршрутизатор? Сервер имён (DNS)? Межсетевой экран, защищающий от проникновения извне в вашу сеть? FreeBSD может превратить давно списанный и пылящийся в углу 386-й или 486-й ПК в мощный маршрутизатор с возможностью фильтрации пакетов.
* _Рабочая станция X Window:_ FreeBSD прекрасный выбор, если вам нужен недорогой X-терминал, использующий свободно распространяемый сервер X11. В отличие от X-терминала, на FreeBSD можно запускать множество приложений локально, если требуется, таким образом перенеся часть нагрузки с центрального сервера. FreeBSD может быть загружена "на бездисковой станции", что делает рабочую станцию ещё дешевле и проще в администрировании.
* _Разработка программного обеспечения:_ Базовая поставка FreeBSD распространяется с полным набором инструментов для разработки, включая знаменитые компилятор GNU C/C++ и отладчик.

FreeBSD доступна как в исходных текстах, так и в двоичном виде на CD-ROM, DVD и через анонимный доступ к FTP. Подробнее о том, как получить FreeBSD, см. в crossref:mirrors[mirrors, Получение FreeBSD].

[[introduction-nutshell-users]]
=== Кто использует FreeBSD?

FreeBSD используется как платформа в устройствах и продуктах многих крупнейших ИТ-компаний мира, в том числе:

* http://www.apple.com/[Apple]
* http://www.cisco.com/[Cisco]
* http://www.juniper.net/[Juniper]
* http://www.netapp.com/[NetApp]

FreeBSD также обеспечивает работу некоторых крупнейших сайтов Интернет, среди которых:

* http://www.yahoo.com/[Yahoo!]
* http://www.yandex.ru/[Yandex]
* http://www.apache.org/[Apache]
* http://www.rambler.ru/[Rambler]
* http://www.sina.com/[Sina]
* http://www.pair.com/[Pair Networks]
* http://www.sony.co.jp/[Sony Japan]
* http://www.netcraft.com/[Netcraft]
* http://www.163.com/[NetEase]
* http://www.weathernews.com/[Weathernews]
* http://www.telehouse.com/[TELEHOUSE America]
* http://www.experts-exchange.com/[Experts Exchange]

и многие другие.

[[history]]
== О Проекте FreeBSD

В следующей части рассказывается о том, что из себя представляет проект, включая краткую историю, цели проекта и модель разработки проекта.

[[intro-history]]
=== Краткая история FreeBSD

Проект FreeBSD возник в начале 1993 года, частично как результат развития неофициального комплекта исправлений к 386BSD (Unofficial 386BSDPatchkit) последними тремя координаторами этой активности, которыми являлись Нэйт Уильямс (Nate Williams), Rod Grimes (Род Граймс) и Jordan Hubbard (Джордан Хаббард).

Изначальной задачей был выпуск промежуточной версии 386BSD, призванной исправить множество проблем, которые механизм patchkit (набор исправлений) не мог решить. Ранним рабочим названием этого проекта, указывающим на этот факт, было 386BSD 0.5 или 386BSD Interim.

386BSD была операционной системой Билла Джолитца, которая на тот момент сильно страдала от почти годичного пренебрежения к ней автора. Так как patchkit с каждым днём разрастался всё более и более непозволительно, они решили помочь Биллу, предоставив этот промежуточный "очистительный" снимок состояния системы. Эти планы были грубо разрушены, когда Билл внезапно решил прекратить поддержку проекта без каких-либо ясных комментариев, что должно быть сделано.

Троица полагала, что цель оставалась стоящей даже без поддержки Билла, и они приняли имя "FreeBSD", придуманное Дэвидом Гринмэном. Начальные цели были определены после консультаций с пользователями существовавшей системы, и как только стало понятно, что проект на пути к тому, чтобы стать реальностью, Джордан связался с компанией Walnut Creek CDROM и поделился идеями о путях последующего улучшения каналов распространения FreeBSD для множества пользователей без доступа к Internet. Компания Walnut Creek CDROM не только поддержала идею распространения FreeBSD на CD, но ещё и предоставила проекту компьютер для работы и быстрый доступ к Интернету. Без почти беспрецедентной веры Walnut Creek CDROM в этот, в то время, полностью неизвестный проект, вряд ли FreeBSD зашла бы так далеко и так быстро, как сегодня.

Первым дистрибутивом, распространяемым как на CD-ROM, так и в сети, стала FreeBSD 1.0, выпущенная в декабре 1993 года. Эта версия была выполнена на основе ленты 4.3BSD-Lite ("Net/2") из Калифорнийского Университета в Беркли, с многочисленными добавлениями из проекта 386BSD и Фонда Свободного Программного Обеспечения. Это был довольно внушительный успех для первой попытки, и они закрепили его выпуском FreeBSD 1.1 RELEASE в мае 1994 года.

В это же время, на горизонте сгустились тучи в связи с назревающим скандалом между Novell и Калифорнийским Университетом, Беркли. Это был вялотекущий судебный процесс о легальности версии Net/2 из Беркли. По условиям достигнутого соглашения, Калифорнийский Университет признавал, что большие куски Net/2 были "унаследованным" кодом, права на который принадлежат компании Novell, которая, в свою очередь, приобрела эти права ранее у AT&T. Взамен Беркли получил "благословение" Novell на то, что версия 4.4BSD-Lite после её выхода будет объявлена полностью "свободной", а всем пользователям Net/2 будет настоятельно рекомендовано перейти на неё. Это также касалось FreeBSD, и проекту было дано время до конца июля 1994 года для прекращения распространения его продукта, базирующегося на Net/2. На этих условиях проекту было разрешено выпустить последний релиз до окончания срока, и это была FreeBSD 1.1.5.1.

Тогда проект FreeBSD приступил к сложнейшей задаче буквально пересоздания с нуля на основе абсолютно новой и довольно неполной системы 4.4BSD-Lite. Версии "Lite" были в прямом смысле light (лёгкими) отчасти потому, что группа CSRG удалила большие куски кода, необходимого для создания реально загружающейся системы (по причине различных лицензионных требований), и фактически порт 4.4BSD для платформы Intel был очень неполным. Проекту потребовалось время почти до ноября 1994 года для того, чтобы выполнить этот переход, и на этом этапе FreeBSD 2.0 была опубликована в сети и на CD-ROM (в конце декабря). Несмотря на множество "острых углов" в этой версии, она пользовалась значительным успехом и была продолжена более устойчивой и простой в установке FreeBSD 2.0.5, выпущенной в июне 1995 года.

С того времени было выпущена серия релизов FreeBSD, с каждым разом улучшающих её стабильность, быстродействие и набор возможностей по сравнению с предыдущими версиями.

На данный момент долгосрочные активности по разработке продолжаются в ветке 10.X-CURRENT, а промежуточные релизы версии 10.X постоянно размещаются на link:ftp://ftp.FreeBSD.org/pub/FreeBSD/snapshots/[сервере промежуточных релизов] по мере выполнения работ.

[[goals]]
=== Цели Проекта FreeBSD

Целью Проекта FreeBSD является предоставление программного обеспечения, которое может быть использовано для любых целей и без дополнительных ограничений. Многие из нас внесли значительный вклад в код (и проект) и совершенно не против получать за это иногда финансовую компенсацию, но мы определенно не собираемся ее требовать. Мы верим, что первая и основная наша "миссия" это предоставление кода для всех, кому он необходим, и для любых целей, так чтобы этот код становился всё более распространённым и предоставлял самые широкие возможности. Это, я верю, является одной из наиболее фундаментальных целей Свободного Программного Обеспечения, и мы с энтузиазмом поддерживаем её.

Тот код в нашем дереве исходных текстов, который попадает под Стандартную Общественную Лицензию GNU (GPL) или Стандартную Общественную Лицензию Ограниченного Применения GNU (LGPL), предоставляется с дополнительными условиями, хотя они обеспечивают только возможность доступа, а не его ограничение. По причине дополнительных сложностей, которые могут появится при коммерческом использовании GPL-продуктов, мы предпочитаем ПО, предоставленное под более свободной лицензией BSD, когда это возможно.

[[development]]
=== Модель Разработки FreeBSD

Разработка FreeBSD - это очень открытый и гибкий процесс. FreeBSD в буквальном смысле создана из кода, предоставленного сотнями людей со всего мира, в чем вы можете убедится, взглянув на extref:{contributors}[список этих людей]. Инфраструктура разработки FreeBSD позволяет этим сотням разработчиков сотрудничать с помощью Интернета. Мы постоянно ищем новых разработчиков и новые идеи, и те, кто заинтересован в более тесном взаимодействии и хочет принять участие в проекте, должны просто связаться с нами в рассылке link:{freebsd-hackers-url}[freebsd-hackers]. Для тех, кто желает уведомить других пользователей FreeBSD об основных направлениях работы, доступен {freebsd-announce}.

Для независимой работы или тесного сотрудничества, полезно знать о проекте и процессе разработки FreeBSD следующее:

Репозитории SVN[[development-cvs-repository]]::
В течение нескольких лет основное дерево исходных текстов FreeBSD поддерживалось с помощью link:http://www.nongnu.org/cvs/[CVS] (Concurrent Versions System), свободно распространяемой системы управления исходным кодом, которая поставляется вместе с FreeBSD. В июне 2008 года Проект перешёл на использование link:https://subversion.apache.org/[SVN] (Subversion).  Переключение признавалось неизбежным, так как технические ограничения, накладываемые CVS, становились всё более очевидными ввиду быстрого расширения дерева исходного кода и размера уже сохранённой истории.  Репозитории Проекта документирования и Коллекции портов также были переведены с CVS на SVN в мае и июле 2012 года, соответственно.  Пожалуйста, обратитесь к разделу crossref:cutting-edge[synching,Синхронизация дерева исходных текстов] для получения дополнительной информации о том, как получить хранилище `src/` FreeBSD, и разделу crossref:ports[ports-using,Использование Коллекции портов] для уточнения подробностей о получении Коллекции портов FreeBSD.

Список коммиттеров[[development-committers]]::
_Коммиттеры_ - это люди, которые имеют права на _запись_ в дереве Subversion и авторизованы на внесение изменений в исходный код FreeBSD (термин "коммиттер" произошёл от команды управления исходным кодом `commit`, используемой для сохранения новых изменений в репозитории). Лучший способ предоставить ваши соображения на рассмотрение коммиттеров - использовать команду man:send-pr[1]. Если что-то произошло с системой, вы можете достучаться до них посылкой письма по адресу {committers-name}.

Core-группа FreeBSD [[development-core]]::
_Core-группа FreeBSD_ могла бы быть эквивалентом Совета Директоров, если бы Проект FreeBSD был компанией. Главная задача Core-группы - гарантировать, что проект в целом в хорошем состоянии и движется в правильном направлении. Приглашение постоянных и ответственных разработчиков присоединиться к группе коммиттеров - одна из функций Core-группы, так же, как и приглашение новых членов в Core-группу по мере того, как другие уходят. Нынешний состав команды был выбран из рядов коммиттеров путем общего голосования в июле 2012 года. Выборы проходят каждые 2 года.
+
Некоторые члены Core-группы имеют особые области ответственности, то есть, они являются ответственными за работу отдельной большой части системы. Полный список разработчиков FreeBSD и областей их ответственности можно найти в extref:{contributors}[Списке участников].
+
[NOTE]
====
Большинство членов Core-группы - волонтёры, и не получают никакой финансовой выгоды от участия в проекте, поэтому вы не должны рассматривать возложенную на них "ответственность" как "гарантированную поддержку". Аналогия с "советом директоров" не очень точна и, вероятно, гораздо правильнее будет сказать, что это люди, которые посвятили себя FreeBSD, хотя и достойны лучшей участи!
====

Внешняя помощь::
Последней, но однозначно не менее значимой, и наибольшей группой разработчиков являются сами пользователи, которые предоставляют комментарии и исправления ошибок нам на почти постоянной основе. Основной путь участвовать в не централизованной разработке - это подписка на {freebsd-hackers}, где обсуждаются подобные вещи. Обратитесь к crossref:eresources[eresources, Ресурсы в интернет] за дальнейшей информацией о различных списках рассылки FreeBSD.
+
extref:{contributors}[Список участников проекта FreeBSD] очень длинный и постоянно растет, так почему бы вам не присоединится к нему, предоставив что-нибудь проекту FreeBSD сегодня?
+
Предоставление кода - не единственный способ помочь проекту; более полный список того, что необходимо сделать, можно найти на link:https://www.FreeBSD.org/ru/[Web-сайте проекта FreeBSD].

Вообще говоря, наша модель разработки организована как "нечеткий набор концентрированных колец". Централизованная модель разработана для удобства _пользователей_ FreeBSD, которые получают простую систему контроля за одной центральной базой кода, и позволяет не оставить за бортом проекта потенциальных помощников! Мы желаем предоставить стабильную операционную систему с большим количеством согласованных crossref:ports[ports,прикладных программ], которые пользователи смогут легко установить и использовать - наша модель очень хорошо подходит для решения этой задачи.

Всё, что мы просим от желающих присоединится к нам как разработчики, - хотя бы часть той преданности постоянному успеху FreeBSD, которой отличаются нынешние разработчики!

[[relnotes]]
=== Программное обеспечение сторонних разработчиков

В дополнение к базовой системе, FreeBSD предоставляет коллекцию портированого ПО, включающую тысячи популярных программ. На момент написания этого текста в ней было более {numports} портов! Список портированных приложений варьируется от серверов http до игр, языков программирования, текстовых редакторов и всего прочего. Полная Коллекция Портов требует приблизительно {ports-size} дискового пространства. Для компиляции приложения необходимо всего лишь перейти в каталог программы, которую вы хотите установить, набрать `make install` и дать системе сделать всю остальную работу. Полные исходные тексты для каждого порта, который вы устанавливаете, загружаются автоматически, поэтому вам нужно только дисковое пространство для сборки необходимых портов. Почти каждый порт предоставляется также как скомпилированный "пакет", который может быть установлен с помощью простой команды (`pkg_add`) теми, кто предпочитает не компилировать порты из исходных текстов. Дополнительная информация о пакетах и портах находится в crossref:ports[ports, Установка приложений. порты и пакеты].

=== Дополнительная документация

Все последние версии FreeBSD предоставляют возможность указать программе установки (&man.sysinstall.8; или &man.bsdinstall.8;) на копирование дополнительной документации в каталог [.filename]#/usr/local/share/doc/freebsd# во время первичной настройки системы.
Также документация может быть установлена в любой момент позже при помощи пакетов, как описано в <<doc-ports-install-package>>.
Вы можете просматривать локально установленные документы с помощью любого браузера, поддерживающего HTML, используя следующие ссылки:

Руководство FreeBSD::
link:file://localhost/usr/local/share/doc/freebsd/handbook/index.html[/usr/local/share/doc/freebsd/handbook/index.html]

FreeBSD FAQ (Часто задаваемые вопросы)::
link:file://localhost/usr/local/share/doc/freebsd/faq/index.html[/usr/local/share/doc/freebsd/faq/index.html]

Вы также можете просмотреть основные (и наиболее часто обновляемые) копии на http://www.FreeBSD.org/ru/[http://www.FreeBSD.org/ru/].
